{
  "sgfList": [{
    "url": "jubango_game1.sgf"
  },{
    "url": "jubango_game1.sgf",
    "initialPosition": "6",
    "showVariations": "NEVER"
  }, {
    "url": "jubango_game1.sgf",
    "initialPosition": "6.1",
    "widgetType": "REDUCED_GAME_VIEWER",
    "boardRegion": "BOTTOM"
  }, {
    "url": "jubango_game1.sgf",
    "initialPosition": "7"
  }, {
    "url": "jubango_game1.sgf",
    "initialPosition": "10",
    "showVariations": "NEVER"
  }, {
    "url": "jubango_game1.sgf",
    "initialPosition": "10.1",
    "showVariations": "NEVER",
    "boardRegion": "BOTTOM"
  }, {
    "url": "jubango_game1.sgf",
    "initialPosition": "10.2",
    "showVariations": "NEVER",
    "boardRegion": "BOTTOM"
  }, {
    "url": "jubango_game1.sgf",
    "initialPosition": "10.2.0",
    "showVariations": "NEVER",
    "boardRegion": "BOTTOM"
  }, {
    "url": "jubango_game1.sgf",
    "initialPosition": "10.2.0.0.0",
    "showVariations": "NEVER",
    "boardRegion": "BOTTOM"
  }, {
    "url": "jubango_game1.sgf",
    "initialPosition": "10.2.0.0.0.0",
    "showVariations": "NEVER",
    "boardRegion": "BOTTOM"
  }, {
    "url": "jubango_game1.sgf",
    "initialPosition": "10.2.0.0.0.0.0",
    "showVariations": "NEVER",
    "boardRegion": "BOTTOM"
  }, {
    "url": "jubango_game1.sgf",
    "initialPosition": "11",
    "showVariations": "NEVER"
  }, {
    "url": "jubango_game1.sgf",
    "initialPosition": "11.1",
    "showVariations": "NEVER"
  }, {
    "url": "jubango_game1.sgf",
    "initialPosition": "11.1.0",
    "showVariations": "NEVER"
  }, {
    "url": "jubango_game1.sgf",
    "initialPosition": "12",
    "showVariations": "NEVER"
  }],
  "theme": "DEFAULT",
  "divId": "glift_display",
  "sgfDefaults": {
    "widgetType": "EXAMPLE"
  }
}
