(function(){var a=window.glift||{};a.createDisplay=function(b){return a.displays.create(b)};a.createController=function(b){return a.controllers.create(b)};a.global={debugMode:!1};window.glift=a})();
glift.util={logz:function(a){var b=a;if("array"===glift.util.typeOf(a)||"object"===glift.util.typeOf(a))b=JSON.stringify(a);console.log(""+b);return glift.util.none},beget:function(a){var b=function(){};b.prototype=a;return new b},typeOf:function(a){var b=typeof a;"object"===b&&(a?a instanceof Array&&(b="array"):b="null");return b},isArray:function(a){return a&&"object"===typeof a&&a.constructor===Array},inBounds:function(a,b){return a<b&&0<=a},outBounds:function(a,b){return a>=b||0>a},intersection:function(a,
b){var c={},d;for(d in a)void 0!==b[d]&&(c[d]=1);return c},getKeyWithDefault:function(a,b,c){void 0===a[b]&&(a[b]=c);return a[b]},sizeOf:function(a){var b=0,c;for(c in a)b+=1;return b},varDefined:function(a,b){var c=b||"";if(void 0===a)throw"Argument cannot be undefined"+(""!==c?": "+c:c);},defined:function(){for(var a=0;a<arguments.length;a++)if(void 0===arguments[a])return!1;return!0},assertDefined:function(a,b){if(void 0===a)throw b;return glift.util.none},checkArgsDefined:function(a,b){for(var c=
0;c<b;c++)if(void 0===a[c])throw"Argument "+c+" of "+a.length+" must be defined, but is undefined";return glift.util.none},setMethods:function(a,b){for(var c in b)a[c]=b[c].bind(a);return a}};glift.util.debugl=function(a){glift.debugOn&&glift.util.log(a)};glift.util.log=function(a){("array"===glift.util.typeOf(a)||"object"===glift.util.typeOf(a))&&JSON.stringify(a);void 0!==console&&void 0!==console.log&&console.log(a)};
(function(){var a=function(){this.type="none"};a.prototype={toString:function(){return"None"}};glift.util.none=new a})();glift.util.colors={isLegalColor:function(a){return a===glift.enums.states.BLACK||a===glift.enums.states.WHITE||a===glift.enums.states.EMPTY},oppositeColor:function(a){return a===glift.enums.states.BLACK?glift.enums.states.WHITE:a===glift.enums.states.WHITE?glift.enums.states.BLACK:a}};
glift.enums={states:{BLACK:"BLACK",WHITE:"WHITE",EMPTY:"EMPTY"},directions:{LEFT:"LEFT",RIGHT:"RIGHT",TOP:"TOP",BOTTOM:"BOTTOM"},controllerMessages:{CONTINUE:"CONTINUE",DONE:"DONE",FAILURE:"FAILURE"},boardRegions:{LEFT:"LEFT",RIGHT:"RIGHT",TOP:"TOP",BOTTOM:"BOTTOM",TOP_LEFT:"TOP_LEFT",TOP_RIGHT:"TOP_RIGHT",BOTTOM_LEFT:"BOTTOM_LEFT",BOTTOM_RIGHT:"BOTTOM_RIGHT",ALL:"ALL"},marks:{CIRCLE:"CIRCLE",LABEL:"LABEL",SQUARE:"SQUARE",TRIANGLE:"TRIANGLE",XMARK:"XMARK",STONE_MARKER:"STONE_MARKER"},problemResults:{CORRECT:"CORRECT",
INCORRECT:"INCORRECT",INDETERMINATE:"INDETERMINATE"},controllerMessages:{CONTINUE:"CONTINUE",DONE:"DONE",FAILURE:"FAILURE"},controllerTypes:{BASE:"CONTROLLER_BASE",STATIC_PROBLEM_STUDY:"STATIC_PROBLEM_STUDY",DYNAMIC_PROBLEM_STUDY:"DYNAMIC_PROBLEM_STUDY",EXLORE_SOLUTIONS:"EXPLORE_SOLUTIONS",EXLORE_GAME:"EXPLORE_GAME"},svgElements:{BOARD_BASE:"board_base",BOARD_LINE:"board_line",BUTTON:"intersection_button",MARK:"mark",MARK_CONTAINER:"mark_container",GLIFT_ELEMENT:"glift_element",STARPOINT:"starpoint",
STONE:"stone",STONE_SHADOW:"stone_shadow"},mediums:{SVG:"SVG",CANVAS:"CANVAS"}};(function(){glift.errors={};glift.errors.ParseError=function(a){this.name="ParseError";this.message=a||""};glift.errors.ParseError.prototype=Error()})();glift.util._IdGenerator=function(a){this.seed=a||0};glift.util._IdGenerator.prototype={next:function(){var a=this.seed+"";this.seed+=1;return a}};glift.util.idGenerator=new glift.util._IdGenerator(0);
(function(){glift.logger=function(a,b){return new glift.Log(a,b)};glift.Log=function(a,b){this.name="#"+a;this.num=b;this.curMsgs=0};glift.Log.prototype.println=function(a){var b=a;if("array"===glift.util.typeOf(a)||"object"===glift.util.typeOf(a))b=JSON.stringify(a);$("<p>"+b+"</p>").appendTo(this.name);this.curMsgs++;this.curMsgs>this.num&&($(this.name).children("p:first").remove(),this.curMsgs-=1)};glift.Log.prototype.printv=function(){for(var a=arguments,b="",b=a[0],c=1;c<a.length;c++)b=b+","+
a[c];this.println(b)};glift.Log.prototype.log=glift.Log.prototype.println;glift.Log.prototype.printArr=function(a){for(var b=0;b<a.length;b++)this.println(a[b].toString());this.println("----")}})();glift.math={abs:function(a){return 0<=a?a:-1*a},max:function(a,b){return a>b?a:b},min:function(a,b){return a>b?b:a},isEven:function(a){return 0==a%2?!0:!1},getRandomInt:function(a,b){return Math.floor(Math.random()*(b-a+1))+a}};
(function(){glift.util.point=function(b,c){return new a(b,c)};glift.util.coordToString=function(b,a){return b+","+a};glift.util.pointFromString=function(b){try{var a=b.split(","),d=parseInt(a[0]),e=parseInt(a[1]);return glift.util.point(d,e)}catch(h){throw"Parsing Error! Couldn't parse a point from: "+b;}};glift.util.pointFromHash=function(b){return glift.util.pointFromString(b)};var a=function(b,a){this.x=function(){return b};this.y=function(){return a};this.equals=function(d){return b===d.x()&&
a===d.y()};this.toSgfCoord=function(){return String.fromCharCode(b+97)+String.fromCharCode(a+97)}};a.prototype={hash:function(){return this.toString()},toString:function(){return glift.util.coordToString(this.x(),this.y())},translate:function(b,a){return glift.util.point(this.x()+b,this.y()+a)},value:function(){return this.toString()},log:function(){glift.util.logz(this.toString())}}})();
glift.util.regions={getComponents:function(a){var b=glift.enums.boardRegions,c={};a===b.TOP_LEFT?(c[b.TOP]=1,c[b.LEFT]=1):a===b.TOP_RIGHT?(c[b.TOP]=1,c[b.RIGHT]=1):a===b.BOTTOM_LEFT?(c[b.BOTTOM]=1,c[b.LEFT]=1):a===b.BOTTOM_RIGHT&&(c[b.BOTTOM]=1,c[b.RIGHT]=1);return c}};glift.testUtil={assertFullDiv:function(a){ok(0!==d3.selectAll("#"+a+" svg")[0].length,"Div should contain contents")},assertEmptyDiv:function(a){deepEqual(d3.selectAll("#"+a+" svg")[0].length,0,"Div should not contain contents")}};
glift.themes={registered:{},get:function(a){var b=glift.themes.registered;return jQuery.extend(!0,{},!(a in b)?glift.util.none:b[a])},has:function(a){return a in glift.themes.registered},setGoBoardBackground:function(a,b){if(a)a.board.imagefill=b;else throw"Yikes! Not a theme: cannot set background image.";}};
glift.themes.registered.DEFAULT={board:{fill:"#f5be7e",stroke:"#000000"},starPoints:{sizeFraction:0.15,fill:"#000000"},lines:{stroke:"#000000"},stones:{marks:{"font-family":"sans-serif"},shadows:{stroke:"none",fill:"#222"},EMPTY:{fill:"blue",opacity:0,marks:{fill:"black",stroke:"black"}},BLACK:{fill:"black",opacity:1,"stroke-width":1,stroke:"black",marks:{fill:"white",stroke:"white"}},BLACK_HOVER:{fill:"black",opacity:0.5},WHITE:{stroke:"black",fill:"white",opacity:1,"stroke-width":1,marks:{fill:"white",
stroke:"white"}},WHITE_HOVER:{fill:"white",opacity:0.5}},icons:{DEFAULT:{fill:"90-#337-#55B"},DEFAULT_HOVER:{fill:"90-#337-#55D"}}};
glift.themes.registered.DEPTH={board:{fill:"#f5be7e",stroke:"#000000"},starPoints:{sizeFraction:0.15,fill:"#000000"},lines:{stroke:"#000000"},stones:{marks:{"font-family":"sans-serif"},shadows:{stroke:"none",fill:"#555"},EMPTY:{fill:"blue",opacity:0,marks:{fill:"black",stroke:"black"}},BLACK:{fill:"black",opacity:1,"stroke-width":0,stroke:"black",marks:{fill:"white",stroke:"white"}},BLACK_HOVER:{fill:"black",opacity:0.5},WHITE:{stroke:"white",fill:"white",opacity:1,"stroke-width":0,marks:{fill:"black",
stroke:"black"}},WHITE_HOVER:{fill:"white",opacity:0.5}}};glift.displays={create:function(a){a=glift.displays.processOptions(a);var b=glift.displays.environment.get(a),c=glift.themes.get(a.theme);""!==a.goBoardBackground&&glift.themes.setGoBoardBackground(c,a.goBoardBackground);return glift.displays.board.create(b,a.theme,c)}};
(function(){glift.displays.bboxFromPts=function(b,c){return new a(b,c)};glift.displays.bboxFromDiv=function(b){var a=document.getElementById(b);b=Math.max(a.clientHeight,isNaN(parseFloat(a.style.height))?0:parseFloat(a.style.height),a.offsetHeight);a=Math.max(a.clientWidth,isNaN(parseFloat(a.style.width))?0:parseFloat(a.style.width),a.offsetWidth);return glift.displays.bbox(glift.util.point(0,0),a,b)};glift.displays.bbox=function(b,c,d){return new a(b,glift.util.point(b.x()+c,b.y()+d))};var a=function(b,
a){this.topLeft=function(){return b};this.botRight=function(){return a};this.center=function(){return glift.util.point(glift.math.abs((a.x()-b.x())/2)+b.x(),glift.math.abs((a.y()-b.y())/2)+b.y())};this.width=function(){return a.x()-b.x()};this.height=function(){return a.y()-b.y()};this.top=function(){return b.y()};this.left=function(){return b.x()};this.bottom=function(){return a.y()};this.right=function(){return a.x()}};a.prototype={draw:function(b,a){b.rect(this.topLeft().x(),this.topLeft().y(),
this.width(),this.height()).attr({fill:a,opacity:0.5})},log:function(){glift.util.logz("TopLeft: "+JSON.stringify(this.topLeft()));glift.util.logz("BotRight: "+JSON.stringify(this.botRight()));glift.util.logz("Width: "+this.width());glift.util.logz("Height: "+this.height())},contains:function(b){return b.x()>=this.topLeft().x()&&b.x()<=this.botRight().x()&&b.y()>=this.topLeft().y()&&b.y()<=this.botRight().y()},equals:function(b){return b.topLeft()&&this.topLeft().equals(b.topLeft())&&b.botRight()&&
this.botRight().equals(b.botRight())},fixedScale:function(b){var a=this.height()*b;b*=this.width();return glift.displays.bbox(this.topLeft(),b,a)},toString:function(){return this.topLeft().toString()+","+this.botRight().toString()},translate:function(b,a){return glift.displays.bboxFromPts(glift.util.point(this.topLeft().x()+b,this.topLeft().y()+a),glift.util.point(this.botRight().x()+b,this.botRight().y()+a))}}})();
(function(){glift.displays.boardPoints=function(b,c,d){return new a(b,c,d)};glift.displays.boardPointsFromLineBox=function(b,a){for(var d=b.spacing,e=d/2,h=b.bbox,f=h.left()+b.extensionBox.left()*d,h=h.top()+b.extensionBox.top()*d,k=b.pointTopLeft.x(),l=b.pointTopLeft.y(),m={},n=0;n<=b.yPoints;n++)for(var r=0;r<=b.xPoints;r++){var q=f+r*d,s=h+n*d,p=glift.util.point(k+r,l+n),q=glift.util.point(q,s);m[p.hash()]={intPt:p,coordPt:q,bbox:glift.displays.bboxFromPts(glift.util.point(q.x()-e,q.y()-e),glift.util.point(q.x()+
e,q.y()+e))}}return glift.displays.boardPoints(m,d,a)};var a=function(b,a,d){this.points=b;this.spacing=a;this.radius=a/2;this.numIntersections=d};a.prototype={getCoords:function(){return this.points},getCoord:function(b){return this.points[b.hash()]},forEach:function(b){for(var a in this.points)b(this.points[a])},data:function(){var b=[];this.forEach(function(a){b.push(a)});return b},hasCoord:function(b){return void 0!==this.points[b.hash()]},starPoints:function(){for(var b=glift.util.point,a={9:[[2,
6],[4]],13:[[3,9],[6]],19:[[3,9,15]]}[this.numIntersections]||[],d=[],e=0;e<a.length;e++)for(var h=a[e],f=0;f<h.length;f++)for(var k=0;k<h.length;k++){var l=b(h[f],h[k]);this.hasCoord(l)&&d.push(l)}return d},_debugDraw:function(a,c){for(var d in this.points){var e=this.points[d].bbox.center().x(),h=this.points[d].bbox.center().y();a.circle(e,h,this.radius).attr({fill:c,opacity:0.3})}}}})();
(function(){glift.displays.cropbox={LINE_EXTENSION:0.5,DEFAULT_EXTENSION:0,OVERFLOW:1.5,create:function(b,c,d,e){return new a(b,c,d,e)},getFromRegion:function(a,c){var d=glift.util,e=glift.enums.boardRegions;a=a||e.ALL;var h=c-1,f=Math.ceil(h/2),k=0,l=0,m=h,n=h,r=this.DEFAULT_EXTENSION,q=this.DEFAULT_EXTENSION,s=this.DEFAULT_EXTENSION,p=this.DEFAULT_EXTENSION;switch(a){case e.LEFT:n=f+1;p=this.LINE_EXTENSION;break;case e.RIGHT:l=f-1;q=this.LINE_EXTENSION;break;case e.TOP:m=f+1;s=this.LINE_EXTENSION;
break;case e.BOTTOM:k=f-1;r=this.LINE_EXTENSION;break;case e.TOP_LEFT:m=f+1;s=this.LINE_EXTENSION;n=f+2;p=this.LINE_EXTENSION;break;case e.TOP_RIGHT:m=f+1;s=this.LINE_EXTENSION;l=f-2;q=this.LINE_EXTENSION;break;case e.BOTTOM_LEFT:k=f-1;r=this.LINE_EXTENSION;n=f+2;p=this.LINE_EXTENSION;break;case e.BOTTOM_RIGHT:k=f-1,r=this.LINE_EXTENSION,l=f-2,p=this.LINE_EXTENSION}e=glift.displays.bboxFromPts(d.point(l,k),d.point(n,m));d=glift.displays.bboxFromPts(d.point(q,r),d.point(p,s));return glift.displays.cropbox.create(e,
d,0,h)}};var a=function(a,c,d,e){var h=glift.displays.cropbox.OVERFLOW;this.cbox=function(){return a};this.extBox=function(){return c};this.xPoints=function(){return a.width()};this.yPoints=function(){return a.height()};this.widthMod=function(){return a.width()+c.topLeft().x()+c.botRight().x()+h};this.heightMod=function(){return a.height()+c.topLeft().y()+c.botRight().y()+h}}})();
(function(){glift.displays.environment={TOPBAR_SIZE:0.1,BOTTOMBAR_SIZE:0.1,get:function(b){return new a(glift.displays.processOptions(b))},getInitialized:function(a){return glift.displays.environment.get(a).init()},environmentCopy:function(b){return new a(glift.displays.processOptions({divId:b.divId,boardRegion:b.boardRegion,intersections:b.intersections}))}};var a=function(a){this.divId=a.divId;this.boardRegion=a.boardRegion;this.intersections=a.intersections;this.cropbox=a.displayConfig._cropbox||
glift.displays.cropbox.getFromRegion(this.boardRegion,this.intersections);this.widthOverride=this.heightOverride=!1;void 0!==a.displayConfig._divHeight&&(this.divHeight=a.displayConfig._divHeight,this.heightOverride=!0);void 0!==a.displayConfig._divWidth&&(this.divWidth=a.displayConfig._divWidth,this.widthOverride=!0)};a.prototype={init:function(){(!this.heightOverride||!this.widthOverride)&&this._resetDimensions();var a=this.divHeight,c=this.divWidth,d=this.cropbox,a=glift.displays.bboxFromPts(glift.util.point(0,
0),glift.util.point(c,a)),c=glift.displays.getResizedBox(a,d),d=glift.displays.getLineBox(c,d),e=glift.displays.boardPointsFromLineBox(d,this.intersections);this.divBox=a;this.goBoardBox=c;this.goBoardLineBox=d;this.boardPoints=e;return this},_resetDimensions:function(){var a=glift.displays.bboxFromDiv(this.divId);this.divHeight=a.height();this.divWidth=a.width();return this},_debugDrawAll:function(){var a=Raphael(this.divId,"100%","100%");this.divBox.draw(a,"yellow");this.resizedBox.draw(a,"red");
this.goBoardBox.draw(a,"orange");this.goBoardLineBox.bbox.draw(a,"red");this.goBoardLineBox._debugDrawLines(a,"blue");this.boardPoints._debugDraw(a,"green");this.lineSegments._debugDraw(a,"black")}}})();
(function(){glift.displays.getLineBox=function(b,c){var d=glift.displays.cropbox.OVERFLOW,e=b.width()/c.widthMod(),h=b.height()/c.heightMod(),f=h*d/2,k=e*d/2,l=h*(c.heightMod()-d/2),d=e*(c.widthMod()-d/2),m=b.topLeft().x(),n=b.topLeft().y(),f=glift.displays.bboxFromPts(glift.util.point(k+m,f+n),glift.util.point(d+m,l+n));return new a(f,e,h,c)};var a=function(a,c,d,e){this.bbox=a;this._xSpacing=c;this._ySpacing=d;this.spacing=c;this.extensionBox=e.extBox();this.pointTopLeft=e.cbox().topLeft();this.xPoints=
e.xPoints();this.yPoints=e.yPoints()};a.prototype={_debugDrawLines:function(a,c){for(var d=this.bbox.left(),e=this.bbox.top();d<=this.bbox.right();d+=this.spacing,e+=this.spacing)a.rect(d,e,this.spacing,this.spacing).attr({fill:c,opacity:0.5})}}})();
glift.displays.processOptions=function(a){var b={intersections:19,divId:"glift_display",theme:"DEFAULT",boardRegion:"ALL",displayConfig:{},goBoardBackground:"",medium:glift.enums.mediums.SVG},c;for(c in a){var d=a[c];switch(c){case "intersections":if("number"==glift.util.typeOf(d)&&0<d)b.intersections=d;else throw"Intersection value : "+c;break;case "theme":if(glift.themes.has(d))b.theme=d;else throw"Unknown theme: "+d;break;case "divId":if(null!==document.getElementById(d))b.divId=d;else throw"Could not find div with id: "+
d;break;case "boardRegion":if(void 0!==glift.enums.boardRegions[d])b.boardRegion=d;else throw"Unknown board region: "+d;break;case "displayConfig":if("object"===glift.util.typeOf(d))b.displayConfig=d;else throw"displayConfig not an object: "+d;break;case "goBoardBackground":if("string"===glift.util.typeOf(d))b.goBoardBackground=d;else throw"goBoardBackground not a string: "+d;break;case "medium":if(void 0!==glift.enums.mediums[d])b.medium=d;else throw"Unknown board region: "+d;}}return b};
glift.displays.getResizedBox=function(a,b){var c=glift.util,d=glift.displays.getCropDimensions(a.width(),a.height(),b),e=d.width(),h=d.height(),f=a.width()-e,k=a.height()-h,l=0===f?0:f/2,m=0===k?0:k/2,n=a.topLeft().x()+l,r=a.topLeft().y()+m,c=glift.displays.bbox(c.point(n,r),e,h);glift.global.debugMode&&(c._debugInfo=function(){return{newDims:d,newWidth:e,newHeight:h,xDiff:f,yDiff:k,xDelta:l,yDelta:m,newLeft:n,newTop:r}});return c};
glift.displays.getCropDimensions=function(a,b,c){var d=b/a;c=c.heightMod()/c.widthMod();var e=b,h=a;d>c?e=a*c:d<c&&(h=b/c);return{height:function(){return e},width:function(){return h}}};glift.displays.board={create:function(a,b,c){return(new glift.displays.board.Display(a,b,c)).draw()}};
glift.displays.board.Display=function(a,b,c){this._objectHistory=[];this._environment=a;this._themeName=b;this._theme=c;this._stones=void 0;this.stones=function(){return this._stones};this._intersections=this._svg=void 0;this.intersections=function(){return this._intersections};this.intersectionPoints=function(){return this._environment.intersections};this.boardPoints=function(){return this._environment.boardPoints};this.divId=function(){return this._environment.divId};this.theme=function(){return this._themeName};
this.boardRegion=function(){return this._environment.boardRegion};this.width=function(){return this._environment.goBoardBox.width()};this.height=function(){return this._environment.goBoardBox.height()}};
glift.displays.board.Display.prototype={init:function(){void 0===this._svg&&(this.destroy(),this._svg=d3.select("#"+this.divId()).style("-webkit-touch-callout","none").style("-webkit-user-select","none").style("-khtml-user-select","none").style("-moz-user-select","moz-none").style("-ms-user-select","none").style("user-select","none").style("cursor","default"),this._svg=d3.select("#"+this.divId()).append("svg").attr("width","100%").attr("height","100%"));this._environment.init();return this},draw:function(){this.init();
var a=glift.displays.board,b=this._environment,c=b.boardPoints,d=this._theme,e=this._svg,h=this.divId();a.initBlurFilter(h,e);a.createBoardBase(h,e,b.goBoardBox,d);var b=a.createLines(h,e,c,d),f=a.createStarPoints(h,e,c,d),k=a.createShadows(h,e,c,d),l=a.createStones(h,e,c,d),m=a.createMarkContainer(h,e,c,d),a=a.createButtons(h,e,c);this._intersections=glift.displays.board.createIntersections(h,e,{lineIds:b,starPointIds:f,stoneShadowIds:k,stoneIds:l,markIds:m,buttons:a},c,d);return this},destroy:function(){this.divId()&&
d3.select("#"+this.divId()).selectAll("svg").remove();this._intersections=this._svg=void 0;return this},recreate:function(a){this.destroy();a=glift.displays.processOptions(a);this._environment=glift.displays.environment.get(a);this._themeName=a.theme;this._theme=glift.themes.get(a.theme);return this},redraw:function(){this.draw()}};
glift.displays.board.createBoardBase=function(a,b,c,d){var e=glift.enums.svgElements.BOARD;a=glift.displays.board.svgutil.elementId(a,e);d.board.imagefill?b.selectAll("goBoardRect").data([e]).enter().append("svg:image").attr("x",c.topLeft().x()).attr("y",c.topLeft().y()).attr("width",c.width()).attr("height",c.height()).attr("stroke",d.board.stroke).attr("xlink:href",d.board.imagefill).attr("preserveAspectRatio","none").attr("id",a):b.selectAll("goBoardRect").data([e]).enter().append("rect").attr("x",
c.topLeft().x()+"px").attr("y",c.topLeft().y()+"px").attr("width",c.width()+"px").attr("height",c.height()+"px").attr("height",c.height()+"px").attr("fill",d.board.fill).attr("background-image",d.board.imagefill).attr("stroke",d.board.stroke).attr("id",a);return a};
glift.displays.board.createButtons=function(a,b,c){var d={},e=glift.displays.board.svgutil,h=glift.enums.svgElements.BUTTON;b.selectAll(h).data(c.data()).enter().append("svg:rect").attr("x",function(a){return a.coordPt.x()-c.radius}).attr("y",function(a){return a.coordPt.y()-c.radius}).attr("width",c.spacing).attr("height",c.spacing).attr("class",h).attr("opacity",0).attr("fill","red").attr("stroke","red").attr("stone_color","EMPTY").attr("id",function(b){var c=e.elementId(a,h,b.intPt);return d[b.intPt.hash()]=
c});return d};glift.displays.board.createIntersections=function(a,b,c,d,e){return new glift.displays.board._Intersections(a,b,c,d,e)};glift.displays.board._Intersections=function(a,b,c,d,e){this.divId=a;this.svg=b;this.theme=e;this.boardPoints=d;this.lineIds=c.lineIds;this.starPointIds=c.starPointIds;this.stoneShadowIds=c.stoneShadowIds;this.stoneIds=c.stoneIds;this.markIds=c.markIds;this.buttons=c.buttons;this.buttonsData=[];for(var h in this.buttons)this.buttonsData.push(glift.util.pointFromString(h))};
glift.displays.board._Intersections.prototype={setStoneColor:function(a,b){var c=a.hash();if(void 0===this.theme.stones[b])throw"Unknown color key ["+b+"]";if(void 0!==this.stoneIds[c]){var d=this.theme.stones[b];this.svg.select("#"+this.stoneIds[c]).attr("fill",d.fill).attr("stone_color",b).attr("opacity",d.opacity);void 0!==this.stoneShadowIds[c]&&(1===d.opacity?this.svg.select("#"+this.stoneShadowIds[c]).attr("opacity",1):this.svg.select("#"+this.stoneShadowIds[c]).attr("opacity",0))}return this},
addMarkPt:function(a,b,c){glift.displays.board.addMark(this.divId,this.svg,this.boardPoints,this.theme,a,b,c);return this},addMark:function(a,b,c,d){this.addMarkPt(glift.util.point(a,b),c,d);return this},clearMarks:function(){var a=glift.enums.svgElements;this.svg.selectAll("."+a.STARPOINT).attr("opacity",1);this.svg.selectAll("."+a.BOARD_LINE).attr("opacity",1);this.svg.selectAll("."+a.MARK).remove();return this},setEvent:function(a,b){this.svg.selectAll("rect."+glift.enums.svgElements.BUTTON).data(this.buttonsData).on(a,
function(a){b(a)})}};glift.displays.board.createLines=function(a,b,c,d){var e={},h=glift.displays.board.svgutil,f=glift.enums.svgElements.BOARD_LINE;b.selectAll(f).data(c.data()).enter().append("path").attr("d",function(a){return glift.displays.board.intersectionLine(a,c.radius,c.numIntersections,d)}).attr("stroke",d.lines.stroke).attr("class",f).attr("stroke-linecap","round").attr("id",function(b){var d=h.elementId(a,f,b.intPt);return e[b.intPt.hash()]=d});return e};
glift.displays.board.intersectionLine=function(a,b,c){var d=c-1;c=a.coordPt;var e=a.intPt;a=glift.displays.board.svgutil;var h=0===e.y()?c.y():c.y()-b,f=e.y()===d?c.y():c.y()+b,k=0===e.x()?c.x():c.x()-b;b=e.x()===d?c.x():c.x()+b;return a.svgMove(c.x(),h)+" "+a.svgLineAbs(c.x(),f)+" "+a.svgMove(k,c.y())+" "+a.svgLineAbs(b,c.y())};glift.displays.board.createMarkContainer=function(a,b,c,d){a=glift.enums.svgElements.MARK_CONTAINER;b.selectAll(a).data([1]).enter().append("g").attr("class",a);return{}};
glift.displays.board.addMark=function(a,b,c,d,e,h,f){var k=glift.displays.board.svgutil,l=glift.enums.svgElements,m=l.MARK,n=l.STONE,r=l.STARPOINT,q=l.BOARD_LINE,l=l.MARK_CONTAINER,s=glift.enums.marks,p=c.getCoord(e).coordPt;k.elementId(a,m,e);var y=b.select("#"+k.elementId(a,n,e)).attr("stone_color"),n=d.stones[y].marks;"EMPTY"===y&&h===s.LABEL&&(b.select("#"+k.elementId(a,r,e)).attr("opacity",0),b.select("#"+k.elementId(a,q,e)).attr("opacity",0));a=c.radius/8;h===s.LABEL?b.select("."+l).append("text").text(f).attr("fill",
n.fill).attr("stroke",n.stroke).attr("class",m).attr("text-anchor","middle").attr("dy",".35em").attr("x",p.x()).attr("y",p.y()).attr("font-family",d.stones.marks["font-family"]).attr("font-size",0.7*c.spacing):h===s.SQUARE?(c=c.radius/1.41421356237,k=c-a,b.select("."+l).append("rect").attr("x",p.x()-k).attr("y",p.y()-k).attr("width",2*k).attr("height",2*k).attr("fill","none").attr("stroke-width",2).attr("class",m).attr("stroke",n.stroke)):h===s.XMARK?(c=c.radius/1.41421356237,f=c-a,c=p.translate(-1*
f,-1*f),d=p.translate(f,-1*f),h=p.translate(-1*f,f),f=p.translate(f,f),b.select("."+l).append("path").attr("d",k.svgMovePt(p)+" "+k.svgLineAbsPt(c)+" "+k.svgMovePt(p)+" "+k.svgLineAbsPt(d)+" "+k.svgMovePt(p)+" "+k.svgLineAbsPt(h)+" "+k.svgMovePt(p)+" "+k.svgLineAbsPt(f)).attr("stroke-width",2).attr("class",m).attr("stroke",n.stroke)):h==s.CIRCLE?b.select("."+l).append("circle").attr("cx",p.x()).attr("cy",p.y()).attr("r",c.radius/2).attr("fill","none").attr("stroke-width",2).attr("class",m).attr("stroke",
n.stroke):h==s.STONE_MARKER?b.select("."+l).append("circle").attr("cx",p.x()).attr("cy",p.y()).attr("r",c.radius/3).attr("class",m).attr("opacity",0.6).attr("fill","blue"):h===s.TRIANGLE&&(h=c.radius-a,c=p.translate(0.866025403785*h,0.5*h),d=p.translate(-0.866025403785*h,0.5*h),p=p.translate(0,-1*h),b.select("."+l).append("path").attr("fill","none").attr("d",k.svgMovePt(p)+" "+k.svgLineAbsPt(d)+" "+k.svgLineAbsPt(c)+" "+k.svgLineAbsPt(p)).attr("stroke-width",2).attr("class",m).attr("stroke",n.stroke));
return this};glift.displays.board.createStarPoints=function(a,b,c,d){var e=d.starPoints.sizeFraction*c.spacing,h=c.starPoints(),f=glift.displays.board.svgutil,k=glift.enums.svgElements.STARPOINT,l={};b.selectAll(k).data(h).enter().append("circle").attr("cx",function(a){return c.getCoord(a).coordPt.x()}).attr("cy",function(a){return c.getCoord(a).coordPt.y()}).attr("r",e).attr("class",k).attr("fill",d.starPoints.fill).attr("id",function(b){var d=f.elementId(a,k,b);return l[b.hash()]=d});return l};
glift.displays.board.createStones=function(a,b,c,d){var e=glift.enums.svgElements.STONE,h=glift.displays.board.svgutil,f={};b.selectAll(e).data(c.data()).enter().append("circle").attr("cx",function(a){return a.coordPt.x()}).attr("cy",function(a){return a.coordPt.y()}).attr("r",c.radius-0.4).attr("opacity",0).attr("class",glift.enums.svgElements.GLIFT_ELEMENT).attr("stone_color","EMPTY").attr("fill","blue").attr("id",function(b){b=b.intPt;var d=h.elementId(a,e,b);return f[b.hash()]=d});return f};
glift.displays.board.createShadows=function(a,b,c,d){if(void 0===d.stones.shadows)return{};var e=glift.enums.svgElements.STONE_SHADOW,h=glift.displays.board.svgutil,f={};b.selectAll(e).data(c.data()).enter().append("circle").attr("cx",function(a){return a.coordPt.x()+c.radius/7}).attr("cy",function(a){return a.coordPt.y()+c.radius/7}).attr("r",c.radius-0.4).attr("opacity",0).attr("fill",d.stones.shadows.fill).attr("stroke",d.stones.shadows.stroke).attr("filter","url(#"+a+"_svg_blur)").attr("id",function(b){b=
b.intPt;var d=h.elementId(a,e,b);return f[b.hash()]=d});return f};glift.displays.board.initBlurFilter=function(a,b){b.append("svg:defs").append("svg:filter").attr("id",a+"_svg_blur").append("svg:feGaussianBlur").attr("stdDeviation",2)};
glift.displays.board.svgutil={elementId:function(a,b,c){a=a+"_"+b;return void 0!==c?a+"_"+c.x()+"_"+c.y():a},svgMove:function(a,b){return"M"+a+" "+b},svgMovePt:function(a){return glift.displays.board.svgutil.svgMove(a.x(),a.y())},svgLineRel:function(a,b){return"l"+a+" "+b},svgLineRelPt:function(a){return glift.displays.board.svgutil.svgLineRel(a.x(),a.y())},svgLineAbs:function(a,b){return"L"+a+" "+b},svgLineAbsPt:function(a){return glift.displays.board.svgutil.svgLineAbs(a.x(),a.y())}};
glift.displays.gui={};
glift.displays.gui.rowCenter=function(a,b,c,d,e,h){var f=a.width()-2*d,k=a.height()-2*c,l=[],m=[],n=0;0>=h&&(h=1E7);for(var r=0;r<b.length;r++){var q=b[r],s=k/q.height(),p={xScale:s,yScale:s},q=q.fixedScale(s);l.push(p);m.push(q);n+=q.width()+e}n-=e;for(r=[];f<n;)p=m.pop(),q=l.pop(),n-=p.width()+e,r.push(q);r=f-n;q=e=p=r/(l.length+1);p>h&&(e=h,q=(r-e*(l.length-1))/2);d=a.left()+d+q;a=a.top()+c;c=[];for(r=0;r<m.length;r++)q=m[r],p=l[r],h=a-q.top(),f=d-q.left(),p.xMove=f,p.yMove=h,c.push(q.translate(f,
h)),d+=q.width()+e;return{transforms:l,bboxes:c}};
glift.displays.gui.icons={cross:function(){return{string:"M24.778,21.419 19.276,15.917 24.777,10.415 21.949,7.585 16.447,13.087 10.945,7.585 8.117,10.415 13.618,15.917 8.116,21.419 10.946,24.248 16.447,18.746 21.948,24.248z",x:8.116,y:7.585,x2:24.778,y2:24.248,width:16.662,height:16.663}},check:function(){return{string:"M2.379,14.729 5.208,11.899 12.958,19.648 25.877,6.733 28.707,9.561 12.958,25.308z",x:2.379,y:6.733,x2:28.707,y2:25.308,width:26.328,height:18.575}},refresh:function(){return{string:"M24.083,15.5c-0.009,4.739-3.844,8.574-8.583,8.583c-4.741-0.009-8.577-3.844-8.585-8.583c0.008-4.741,3.844-8.577,8.585-8.585c1.913,0,3.665,0.629,5.09,1.686l-1.782,1.783l8.429,2.256l-2.26-8.427l-1.89,1.89c-2.072-1.677-4.717-2.688-7.587-2.688C8.826,3.418,3.418,8.826,3.416,15.5C3.418,22.175,8.826,27.583,15.5,27.583S27.583,22.175,27.583,15.5H24.083z",
x:3.416,y:3.415,x2:27.583,y2:27.583,width:24.167,height:24.168}},star3on:function(){return{string:"M22.441,28.181c-0.419,0-0.835-0.132-1.189-0.392l-5.751-4.247L9.75,27.789c-0.354,0.26-0.771,0.392-1.189,0.392c-0.412,0-0.824-0.128-1.175-0.384c-0.707-0.511-1-1.422-0.723-2.25l2.26-6.783l-5.815-4.158c-0.71-0.509-1.009-1.416-0.74-2.246c0.268-0.826,1.037-1.382,1.904-1.382c0.004,0,0.01,0,0.014,0l7.15,0.056l2.157-6.816c0.262-0.831,1.035-1.397,1.906-1.397s1.645,0.566,1.906,1.397l2.155,6.816l7.15-0.056c0.004,0,0.01,0,0.015,0c0.867,0,1.636,0.556,1.903,1.382c0.271,0.831-0.028,1.737-0.739,2.246l-5.815,4.158l2.263,6.783c0.276,0.826-0.017,1.737-0.721,2.25C23.268,28.053,22.854,28.181,22.441,28.181L22.441,28.181z",
x:2.27025872,y:2.821,x2:28.7268678,y2:28.181,width:26.45660907,height:25.36}},star3off:function(){return{string:"M28.631,12.359c-0.268-0.826-1.036-1.382-1.903-1.382h-0.015l-7.15,0.056l-2.155-6.816c-0.262-0.831-1.035-1.397-1.906-1.397s-1.645,0.566-1.906,1.397l-2.157,6.816l-7.15-0.056H4.273c-0.868,0-1.636,0.556-1.904,1.382c-0.27,0.831,0.029,1.737,0.74,2.246l5.815,4.158l-2.26,6.783c-0.276,0.828,0.017,1.739,0.723,2.25c0.351,0.256,0.763,0.384,1.175,0.384c0.418,0,0.834-0.132,1.189-0.392l5.751-4.247l5.751,4.247c0.354,0.26,0.771,0.392,1.189,0.392c0.412,0,0.826-0.128,1.177-0.384c0.704-0.513,0.997-1.424,0.721-2.25l-2.263-6.783l5.815-4.158C28.603,14.097,28.901,13.19,28.631,12.359zM19.712,17.996l2.729,8.184l-6.94-5.125L8.56,26.18l2.729-8.184l-7.019-5.018l8.627,0.066L15.5,4.82l2.603,8.225l8.627-0.066L19.712,17.996z",
x:2.27070338,y:2.82,x2:28.72944822,y2:28.18,width:26.45874494,height:25.36}},"chevron-right":function(){return{string:"M10.129,22.186 16.316,15.999 10.129,9.812 13.665,6.276 23.389,15.999 13.665,25.725z",x:10.129,y:6.276,x2:23.389,y2:25.725,width:13.26,height:19.449}},"chevron-left":function(){return{string:"M21.871,9.814 15.684,16.001 21.871,22.188 18.335,25.725 8.612,16.001 18.335,6.276z",x:8.612,y:6.276,x2:21.871,y2:25.725,width:13.259,height:19.449}},"small-gear":function(){return{string:"M31.229,17.736c0.064-0.571,0.104-1.148,0.104-1.736s-0.04-1.166-0.104-1.737l-4.377-1.557c-0.218-0.716-0.504-1.401-0.851-2.05l1.993-4.192c-0.725-0.91-1.549-1.734-2.458-2.459l-4.193,1.994c-0.647-0.347-1.334-0.632-2.049-0.849l-1.558-4.378C17.165,0.708,16.588,0.667,16,0.667s-1.166,0.041-1.737,0.105L12.707,5.15c-0.716,0.217-1.401,0.502-2.05,0.849L6.464,4.005C5.554,4.73,4.73,5.554,4.005,6.464l1.994,4.192c-0.347,0.648-0.632,1.334-0.849,2.05l-4.378,1.557C0.708,14.834,0.667,15.412,0.667,16s0.041,1.165,0.105,1.736l4.378,1.558c0.217,0.715,0.502,1.401,0.849,2.049l-1.994,4.193c0.725,0.909,1.549,1.733,2.459,2.458l4.192-1.993c0.648,0.347,1.334,0.633,2.05,0.851l1.557,4.377c0.571,0.064,1.148,0.104,1.737,0.104c0.588,0,1.165-0.04,1.736-0.104l1.558-4.377c0.715-0.218,1.399-0.504,2.049-0.851l4.193,1.993c0.909-0.725,1.733-1.549,2.458-2.458l-1.993-4.193c0.347-0.647,0.633-1.334,0.851-2.049L31.229,17.736zM16,20.871c-2.69,0-4.872-2.182-4.872-4.871c0-2.69,2.182-4.872,4.872-4.872c2.689,0,4.871,2.182,4.871,4.872C20.871,18.689,18.689,20.871,16,20.871z",
x:0.667,y:0.667,x2:31.333,y2:31.333,width:30.666,height:30.666}},"question-box":function(){return{string:"M26.711,14.086L16.914,4.29c-0.778-0.778-2.051-0.778-2.829,0L4.29,14.086c-0.778,0.778-0.778,2.05,0,2.829l9.796,9.796c0.778,0.777,2.051,0.777,2.829,0l9.797-9.797C27.488,16.136,27.488,14.864,26.711,14.086zM16.431,21.799c-0.248,0.241-0.543,0.362-0.885,0.362c-0.343,0-0.638-0.121-0.886-0.362c-0.247-0.241-0.371-0.533-0.371-0.876s0.124-0.638,0.371-0.885c0.248-0.248,0.543-0.372,0.886-0.372c0.342,0,0.637,0.124,0.885,0.372c0.248,0.247,0.371,0.542,0.371,0.885S16.679,21.558,16.431,21.799zM18.911,15.198c-0.721,0.716-1.712,1.147-2.972,1.294v2.027h-0.844v-3.476c0.386-0.03,0.768-0.093,1.146-0.188c0.38-0.095,0.719-0.25,1.019-0.464c0.312-0.227,0.555-0.5,0.729-0.822c0.174-0.322,0.261-0.77,0.261-1.346c0-0.918-0.194-1.623-0.582-2.113c-0.389-0.49-0.956-0.735-1.701-0.735c-0.281,0-0.527,0.042-0.738,0.124s-0.366,0.16-0.464,0.234c0.031,0.146,0.072,0.357,0.124,0.633c0.052,0.275,0.078,0.486,0.078,0.633c0,0.226-0.098,0.433-0.294,0.619c-0.195,0.187-0.479,0.28-0.853,0.28c-0.33,0-0.565-0.113-0.706-0.339s-0.211-0.489-0.211-0.789c0-0.244,0.067-0.484,0.201-0.72c0.135-0.235,0.346-0.463,0.633-0.684c0.245-0.195,0.577-0.364,0.995-0.504c0.419-0.141,0.854-0.211,1.308-0.211c0.647,0,1.223,0.103,1.724,0.308c0.502,0.205,0.914,0.479,1.238,0.822c0.337,0.355,0.586,0.755,0.748,1.198c0.162,0.444,0.243,0.926,0.243,1.446C19.994,13.558,19.633,14.482,18.911,15.198z",
x:3.7065,y:3.7065,x2:27.293875,y2:27.29375,width:23.587375,height:23.58725}},"question-bubble":function(){return{string:"M16,4.938c-7.732,0-14,4.701-14,10.5c0,1.981,0.741,3.833,2.016,5.414L2,25.272l5.613-1.44c2.339,1.316,5.237,2.106,8.387,2.106c7.732,0,14-4.701,14-10.5S23.732,4.938,16,4.938zM16.982,21.375h-1.969v-1.889h1.969V21.375zM16.982,17.469v0.625h-1.969v-0.769c0-2.321,2.641-2.689,2.641-4.337c0-0.752-0.672-1.329-1.553-1.329c-0.912,0-1.713,0.672-1.713,0.672l-1.12-1.393c0,0,1.104-1.153,3.009-1.153c1.81,0,3.49,1.121,3.49,3.009C19.768,15.437,16.982,15.741,16.982,17.469z",
x:2,y:4.938,x2:30,y2:25.938,width:28,height:21}},roadmap:function(){return{string:"M23.188,3.735c0-0.975-0.789-1.766-1.766-1.766s-1.766,0.791-1.766,1.766s1.766,4.267,1.766,4.267S23.188,4.71,23.188,3.735zM20.578,3.734c0-0.466,0.378-0.843,0.844-0.843c0.467,0,0.844,0.377,0.844,0.844c0,0.466-0.377,0.843-0.844,0.843C20.956,4.578,20.578,4.201,20.578,3.734zM25.281,18.496c-0.562,0-1.098,0.046-1.592,0.122L11.1,13.976c0.199-0.181,0.312-0.38,0.312-0.59c0-0.108-0.033-0.213-0.088-0.315l8.41-2.239c0.459,0.137,1.023,0.221,1.646,0.221c1.521,0,2.75-0.485,2.75-1.083c0-0.599-1.229-1.083-2.75-1.083s-2.75,0.485-2.75,1.083c0,0.069,0.021,0.137,0.054,0.202L9.896,12.2c-0.633-0.188-1.411-0.303-2.265-0.303c-2.088,0-3.781,0.667-3.781,1.49c0,0.823,1.693,1.489,3.781,1.489c0.573,0,1.11-0.054,1.597-0.144l11.99,4.866c-0.19,0.192-0.306,0.401-0.306,0.623c0,0.188,0.096,0.363,0.236,0.532L8.695,25.415c-0.158-0.005-0.316-0.011-0.477-0.011c-3.241,0-5.87,1.037-5.87,2.312c0,1.276,2.629,2.312,5.87,2.312c3.241,0,5.87-1.034,5.87-2.312c0-0.22-0.083-0.432-0.229-0.633l10.265-5.214c0.37,0.04,0.753,0.066,1.155,0.066c2.414,0,4.371-0.771,4.371-1.723C29.65,19.268,27.693,18.496,25.281,18.496z",
x:2.348,y:1.969,x2:29.65,y2:30.028,width:27.302,height:28.059}}};glift.displays.gui.getRaphaelBboxes=function(a){for(var b=[],c=0;c<a.length;c++)b.push(a[c].getBBox());return b};glift.displays.gui.applyTransforms=function(a,b){for(var c=0;c<a.length;c++){var d=b[c];d.transform(glift.displays.gui.scaleAndMove(d.getBBox(),a[c]))}};glift.displays.gui.scaleAndMove=function(a,b){return"s"+b.xScale+","+b.yScale+","+a.x+","+a.y+"T"+b.xMove+","+b.yMove};glift.rules={};
(function(){var a=glift.util;glift.rules.goban={getInstance:function(a){return new b(a||19)},getFromMoveTree:function(a,d){var c=new b(a.getIntersections()),k=a.getTreeFromRoot();void 0===d&&(d=[]);c.loadStonesFromMovetree(k);for(var l=0;l<d.length;l++)k.moveDown(d[l]),c.loadStonesFromMovetree(k);return c}};var b=function(a){if(0>=a)throw"Intersections must be greater than 0";this.ints=a;for(var b=[],d=0;d<a;d++){for(var c=[],l=0;l<a;l++)c[l]=glift.enums.states.EMPTY;b[d]=c}this.stones=b};b.prototype=
{intersections:function(){return this.ints},getStone:function(a){return this.stones[a.y()][a.x()]},getAllPlacedStones:function(){for(var b=[],d=0;d<this.stones.length;d++)for(var c=this.stones[d],k=0;k<c.length;k++){var l=a.point(k,d),m=this.getStone(l);(m===glift.enums.states.BLACK||m===glift.enums.states.WHITE)&&b.push({point:l,color:m})}return b},placeable:function(a,b){return this.inBounds(a)&&this.getStone(a)===glift.enums.states.EMPTY},outBounds:function(b){return a.outBounds(b.x(),this.ints)||
a.outBounds(b.y(),this.ints)},inBounds:function(b){return a.inBounds(b.x(),this.ints)&&a.inBounds(b.y(),this.ints)},clearStone:function(a){this._setColor(a,glift.enums.states.EMPTY)},clearSome:function(a){for(var b=1;b<a.length;b++)this.clearStone(a[b])},_setColor:function(a,b){this.stones[a.y()][a.x()]=b},addStone:function(b,h){if(!a.colors.isLegalColor(h))throw"Unknown color: "+h;if(this.outBounds(b)||!this.placeable(b))return new d(!1);this._setColor(b,h);var f=new c,k=a.colors.oppositeColor(h);
this._getCaptures(f,a.point(b.x()+1,b.y()),k);this._getCaptures(f,a.point(b.x()-1,b.y()),k);this._getCaptures(f,a.point(b.x(),b.y()-1),k);this._getCaptures(f,a.point(b.x(),b.y()+1),k);if(0>=f.numCaptures&&(this._getCaptures(f,b,h),0<f.numCaptures))return this.clearStone(b),new d(!1);f=f.getCaptures();this.clearSome(f);return new d(!0,f)},_getCaptures:function(a,b,d){this._findConnected(a,b,d);0>=a.liberties&&a.consideringToCaptures();a.clearExceptCaptures()},_findConnected:function(b,d,c){if(!(void 0!==
b.seen[d.hash()]||this.outBounds(d))){b.seen[d.hash()]=!0;var k=this.getStone(d);if(k===glift.enums.states.EMPTY)b.liberties++;else if(k!==a.colors.oppositeColor(c))if(k===c)b.considering.push(d),this._findConnected(b,a.point(d.x()+1,d.y()),c),this._findConnected(b,a.point(d.x()-1,d.y()),c),this._findConnected(b,a.point(d.x(),d.y()+1),c),this._findConnected(b,a.point(d.x(),d.y()-1),c);else throw"Unknown color error: "+k;}},loadStonesFromMovetree:function(b){for(var d=[glift.enums.states.BLACK,glift.enums.states.WHITE],
c=0;c<d.length;c++)for(var k=b.getProperties().getPlacementsAsPoints(d[c]),l=0;l<k.length;l++)(this.placeable(k[l]),d[c])&&this.addStone(k[l],d[c]);b=b.getProperties().getMove();b!=a.none&&this.addStone(b.point,b.color)},_debug:function(){glift.util.logz(this.stones)}};var c=function(){this.toCapture={};this.numCaptures=0;this.considering=[];this.seen={};this.liberties=0};c.prototype={clearExceptCaptures:function(){this.considering=[];this.seen={};this.liberties=0},consideringToCaptures:function(){for(var a=
0;a<this.considering.length;a++){var b=this.considering[a];void 0===this.toCapture[b.hash()]&&(this.toCapture[b.hash()]=!0,this.numCaptures++)}},addLiberties:function(a){this.liberties+=a},addSeen:function(a){this.seen[a.hash()]=!0},getCaptures:function(){var b=[],d;for(d in this.toCapture)b.push(a.pointFromHash(d));return b}};var d=function(a,b){this.captures=(this.successful=a)?b:[]}})();
(function(){var a=glift.enums;glift.rules.intersections={propertiesToMarks:{CR:a.marks.CIRCLE,LB:a.marks.LABEL,MA:a.marks.XMARK,SQ:a.marks.SQUARE,TR:a.marks.TRIANGLE},getFullBoardData:function(a,c){for(var d={},e={},h=c.getAllPlacedStones(),f=0;f<h.length;f++){var k=h[f].point,l={};l.point=k;l.stone=h[f].color;e[k.hash()]=l}e=this.addCurrentMarks(e,a);d.points=e;a.getProperties().getComment()!==glift.util.none&&(d.comment=a.getProperties().getComment());return d},getChangeData:function(a,c,d){},addCurrentMarks:function(a,
c){for(var d in glift.rules.intersections.propertiesToMarks){var e=glift.rules.intersections.propertiesToMarks[d];if(c.getProperties().contains(d))for(var h=c.getProperties().get(d),f=0;f<h.length;f++){var k={},l=!0;d===glift.sgf.allProperties.LB?(l=glift.sgf.convertFromLabelData(h[f]),k=l.point,l=l.value):k=glift.sgf.sgfCoordToPoint(h[f]);var m=k.hash();void 0===a[m]&&(a[m]={point:k});a[m][e]=l}}return a}}})();
(function(){glift.rules.movenode=function(b,d){return new a(b,d)};var a=function(a,b){this.properties=a||glift.rules.properties();this.children=b||[];this.nodeId={nodeNum:0,varNum:0}};a.prototype={setNodeId:function(a,b){this.nodeId={nodeNum:a,varNum:b};return this},getNodeNum:function(){return this.nodeId.nodeNum},getVarNum:function(){return this.nodeId.varNum},numChildren:function(){return this.children.length},addChild:function(){this.children.push(glift.rules.movenode().setNodeId(this.getNodeNum()+
1,this.numChildren()));return this},getNext:function(a){return void 0===a?this.children[0]:this.children[a]},renumber:function(){b(this,this.nodeId.nodeNum,this.nodeId.varNum);return this}};var b=function(a,d,e){a.setNodeId(d,e);for(e=0;e<a.children.length;e++)b(a.children[e],d+1,e);return a}})();
(function(){var a=glift.util,b=glift.enums;glift.rules.movetree={getInstance:function(a){a=a||19;var b=new c(glift.rules.movenode());b.setIntersections(a);return b},getFromSgf:function(a,b){void 0===b&&(b=[]);if(void 0===a||""===a)return glift.rules.movetree.getInstance(19);for(var h=new c(glift.sgf.parser.parse($.trim(a))),f=0;f<b.length;f++)h.moveDown(b[f]);return h},getFromNode:function(a){return new c(a)},searchMoveTreeDFS:function(a,b){b(a);for(var c=0;c<a.getNode().numChildren();c++)glift.rules.movetree.searchMoveTreeDFS(a.moveDown(c),
b);a.moveUp()}};var c=function(a){this._nodeHistory=[];this._nodeHistory.push(a)};c.prototype={getTreeFromRoot:function(){return glift.rules.movetree.getFromNode(this._nodeHistory[0])},getNode:function(){return this._nodeHistory[this._nodeHistory.length-1]},getProperties:function(){return this.getNode().properties},findNextMove:function(b,c){for(var h=this.getNode().children,f=glift.sgf.colorToToken(c),k={},l=0;l<h.length;l++){var m=h[l];m.properties.contains(f)&&(k[m.properties.getAsPoint(f).hash()]=
m.getVarNum())}return void 0!==k[b.hash()]?k[b.hash()]:a.none},getCurrentPlayer:function(){var d=this.getProperties().getMove();return d===a.none?b.states.BLACK:d.color===b.states.BLACK?b.states.WHITE:b.states.BLACK},moveDown:function(a){a=void 0===a?0:a;void 0!==this.getNode().getNext(a)&&(a=this.getNode().getNext(a),this._nodeHistory.push(a));return this},moveUp:function(){1<this._nodeHistory.length&&this._nodeHistory.pop();return this},moveToRoot:function(){this._nodeHistory=this._nodeHistory.slice(0,
1);return this},addNewNode:function(){this.getNode().addChild();this.moveDown(this.getNode().numChildren()-1);return this},deleteCurrentNode:function(){glift.rules.movetree.getNodeId();VarNum=this.getVarNum();this.moveUp();this.getAllNextNodes();return this},recurse:function(a){glift.rules.movetree.searchMoveTreeDFS(this,a)},recurseFromRoot:function(a){glift.rules.movetree.searchMoveTreeDFS(this.getTreeFromRoot(),a)},toSgf:function(){for(var a in this.getAllProps());},debugLog:function(a){void 0===
a&&(a="  ");glift.util.logz(a+this.getNode(b).getVarNum()+"-"+this.getNode(b).getNodeNum());for(var b=0;b<this.getNode().numChildren();b++)this.moveDown(b),this.debugLog(a),this.moveUp()},setIntersections:function(a){var b=this.getTreeFromRoot(),c=glift.sgf.allProperties;b.getProperties().contains(c.SZ)||this.getProperties().add(c.SZ,a+"");return this},getIntersections:function(){var a=this.getTreeFromRoot(),b=glift.sgf.allProperties;if(a.getNode().properties.contains(b.SZ))return parseInt(a.getNode().properties.get(b.SZ))},
isCorrectPosition:function(){var a=glift.enums.problemResults;if(this.getProperties().isCorrect())return a.CORRECT;for(var b=glift.rules.treepath.flattenMoveTree(this),c={},f=0;f<b.length;f++){for(var k=b[f],l=glift.rules.movetree.getFromNode(this.getNode()),m=!1,n=0;n<k.length;n++)l.moveDown(k[n]),l.getProperties().isCorrect()&&(m=!0);m?c[a.CORRECT]=!0:c[a.INCORRECT]=!0}return c[a.CORRECT]&&!c[a.INCORRECT]?a.CORRECT:c[a.CORRECT]&&c[a.INCORRECT]?a.INDETERMINATE:a.INCORRECT}}})();
(function(){var a=glift.util,b=glift.enums;glift.rules.properties=function(a){return new c(a)};var c=function(a){this.propMap=void 0===a?{}:a};c.prototype={add:function(b,c){if(void 0===glift.sgf.allProperties[b])throw"Can't add undefined properties";"string"!==a.typeOf(c)&&"array"!==a.typeOf(c)&&(c=c.toString());c="string"===a.typeOf(c)?[c]:c;this.contains(b)?this.propMap[b]=this.get(b).concat(c):this.propMap[b]=c;return this},get:function(b){if(void 0===glift.sgf.allProperties[b])return a.debugl("attempted to retrieve a property that is not part of the SGF Spec: "+
b),a.none;if(void 0!==this.propMap[b])return this.propMap[b];a.debugl("no property: "+b+" exists for the current move");return a.none},getDatum:function(b,c){c=void 0!==c&&"number"===typeof c&&0<=c?c:0;var h=this.get(b);return h!==a.none&&1<=h.length?h[c]:a.none},getAsPoint:function(b,c){var h=this.getDatum(b,c);return h!==a.none?glift.sgf.sgfCoordToPoint(h):h},contains:function(b){return this.get(b)!==a.none},remove:function(b){if(this.contains(b)){var c=this.get(b);delete this.propMap[b];return c}return a.none},
replace:function(a,b){this.propMap[a]=b},getPlacementsAsPoints:function(a){var c="";a===b.states.BLACK?c=glift.sgf.allProperties.AB:a===b.states.WHITE&&(c=glift.sgf.allProperties.AW);return""===c||!this.contains(c)?[]:glift.sgf.allSgfCoordsToPoints(this.get(c))},getComment:function(){return this.contains("C")?this.getDatum("C"):a.none},getMove:function(){return this.contains("B")?{color:b.states.BLACK,point:glift.sgf.sgfCoordToPoint(this.getDatum("B"))}:this.contains("W")?{color:b.states.WHITE,point:glift.sgf.sgfCoordToPoint(this.getDatum("W"))}:
a.none},isCorrect:function(){return this.contains("GB")?!0:!1},getAllStones:function(){var b=glift.enums.states,c={},h=b.WHITE;c[b.BLACK]=this.getPlacementsAsPoints(b.BLACK);c[h]=this.getPlacementsAsPoints(b.WHITE);b=this.getMove();b!=a.none&&c[b.color].push(b.point);return c}}})();
glift.rules.treepath={parseInitPosition:function(a){if(void 0===a)return[];if("number"===glift.util.typeOf(a))a=""+a;else{if("array"===glift.util.typeOf(a))return a;if("string"!==glift.util.typeOf(a))return[]}var b=[],c=0;a=a.split("-");for(var d=0;d<a.length;d++){for(var e=a[d].split("."),h=0;h<e[0]-c;h++)b.push(0);c=e[0];for(h=1;h<e.length;h++)b.push(parseInt(e[h])),c++}return b},flattenMoveTree:function(a){for(var b=[],c=0;c<a.getNode().numChildren();c++){a.moveDown(c);var d=glift.rules.treepath._flattenMoveTree(a,
[]);a.moveUp();for(var e=0;e<d.length;e++)b.push(d[e])}return b},_flattenMoveTree:function(a,b){void 0===b&&(b=[]);b.push(a.getNode().getVarNum());for(var c=[],d=0;d<a.getNode().numChildren();d++){a.moveDown(d);var e=glift.rules.treepath._flattenMoveTree(a,b.slice()),c=c.concat(e);a.moveUp(d)}0==c.length&&c.push(b);return c}};
glift.sgf={colorToToken:function(a){if(a===glift.enums.states.WHITE)return"W";if(a===glift.enums.states.BLACK)return"B";throw"Unknown color-to-token conversion for: "+a;},sgfCoordToPoint:function(a){return glift.util.point(a.charCodeAt(0)-97,a.charCodeAt(1)-97)},allSgfCoordsToPoints:function(a){for(var b=[],c=0;c<a.length;c++)b.push(glift.sgf.sgfCoordToPoint(a[c]));return b},convertFromLabelData:function(a){a=a.split(":");return{point:glift.sgf.sgfCoordToPoint(a[0]),value:a[1]}},convertFromLabelArray:function(a){for(var b=
[],c=0;c<a.length;c++)b.push(glift.sgf.convertFromLabelData(a[c]));return b},pointToSgfCoord:function(a){return String.fromCharCode(a.x()+97)+String.fromCharCode(a.y()+97)}};
glift.sgf.allProperties={AB:"AB",AE:"AE",AN:"AN",AP:"AP",AR:"AR",AS:"AS",AW:"AW",B:"B",BL:"BL",BM:"BM",BR:"BR",BS:"BS",BT:"BT",C:"C",CA:"CA",CH:"CH",CP:"CP",CR:"CR",DD:"DD",DM:"DM",DO:"DO",DT:"DT",EL:"EL",EV:"EV",EX:"EX",FF:"FF",FG:"FG",GB:"GB",GC:"GC",GM:"GM",GN:"GN",GW:"GW",HA:"HA",HO:"HO",ID:"ID",IP:"IP",IT:"IT",IY:"IY",KM:"KM",KO:"KO",L:"L",LB:"LB",LN:"LN",LT:"LT",M:"M",MA:"MA",MN:"MN",N:"N",OB:"OB",OM:"OM",ON:"ON",OP:"OP",OT:"OT",OV:"OV",OW:"OW",PB:"PB",PC:"PC",PL:"PL",PM:"PM",PW:"PW",RE:"RE",
RG:"RG",RO:"RO",RU:"RU",SC:"SC",SE:"SE",SI:"SI",SL:"SL",SO:"SO",SQ:"SQ",ST:"ST",SU:"SU",SZ:"SZ",TB:"TB",TC:"TC",TE:"TE",TM:"TM",TR:"TR",TW:"TW",UC:"UC",US:"US",V:"V",VW:"VW",W:"W",WL:"WL",WR:"WR",WS:"WS",WT:"WT"};
glift.sgf.parser=function(){var a={parse:function(a,c){function d(a){var b=a.charCodeAt(0);if(255>=b){a="x";var c=2}else a="u",c=4;a="\\"+a;for(var d=b.toString(16).toUpperCase(),b=d,c=c-d.length,d=0;d<c;d++)b="0"+b;return a+b}function e(a){return'"'+a.replace(/\\/g,"\\\\").replace(/"/g,'\\"').replace(/\r/g,"\\r").replace(/\n/g,"\\n").replace(/[\x80-\uFFFF]/g,d)+'"'}function h(a){g<x||(g>x&&(x=g,A=[]),A.push(a))}function f(){var c="Variations@"+g,d=v[c];if(d)return g=d.nextPos,d.result;var u=d=g;
if("("===a.substr(g,1)){var e="(";g+=1}else e=null,t&&h('"("');if(null!==e){var f=l();if(null!==f){if(")"===a.substr(g,1)){var m=")";g+=1}else m=null,t&&h('")"');if(null!==m){var n=p(),n=null!==n?n:"";if(null!==n){if("("===a.substr(g,1)){var q="(";g+=1}else q=null,t&&h('"("');if(null!==q){var r=l();if(null!==r){if(")"===a.substr(g,1)){var s=")";g+=1}else s=null,t&&h('")"');if(null!==s){var w=p(),w=null!==w?w:"";if(null!==w){var x=k();null!==x?e=[e,f,m,n,q,r,s,w,x]:(e=null,g=u)}else e=null,g=u}else e=
null,g=u}else e=null,g=u}else e=null,g=u}else e=null,g=u}else e=null,g=u}else e=null,g=u}else e=null,g=u;u=null!==e?[e[1],e[5]].concat(e[8]):null;null===u&&(u=null,g=d);null!==u?d=u:(d=g,u=l(),u=null!==u?void 0===u?[]:[u]:null,null===u&&(u=null,g=d),d=null!==u?u:null);v[c]={nextPos:g,result:d};return d}function k(){var c="MoreVars@"+g,d=v[c];if(d)return g=d.nextPos,d.result;var e=d=g;if("("===a.substr(g,1)){var f="(";g+=1}else f=null,t&&h('"("');if(null!==f){var m=l();if(null!==m){if(")"===a.substr(g,
1)){var n=")";g+=1}else n=null,t&&h('")"');if(null!==n){var q=p(),q=null!==q?q:"";if(null!==q){var r=k();null!==r?f=[f,m,n,q,r]:(f=null,g=e)}else f=null,g=e}else f=null,g=e}else f=null,g=e}else f=null,g=e;e=null!==f?[f[1]].concat(f[4]):null;null===e&&(e=null,g=d);null!==e?d=e:(d=g,""===a.substr(g,0)?(e="",g+=0):(e=null,t&&h('""')),e=null!==e?[]:null,null===e&&(e=null,g=d),d=null!==e?e:null);v[c]={nextPos:g,result:d};return d}function l(){var c="Moves@"+g,d=v[c];if(d)return g=d.nextPos,d.result;var e=
d=g;if(";"===a.substr(g,1)){var k=";";g+=1}else k=null,t&&h('";"');if(null!==k){var l=m();if(null!==l){var n=f();null!==n?k=[k,l,n]:(k=null,g=e)}else k=null,g=e}else k=null,g=e;e=null!==k?glift.rules.movenode(glift.rules.properties(k[1]),k[2]):null;null===e&&(e=null,g=d);null!==e?d=e:(d=g,""===a.substr(g,0)?(e="",g+=0):(e=null,t&&h('""')),e=null!==e?void 0:null,null===e&&(e=null,g=d),d=null!==e?e:null);v[c]={nextPos:g,result:d};return d}function m(){var c="Tokens@"+g,d=v[c];if(d)return g=d.nextPos,
d.result;var e=d=g,f=s();if(null!==f){if("["===a.substr(g,1)){var k="[";g+=1}else k=null,t&&h('"["');if(null!==k){var l=r();if(null!==l){if("]"===a.substr(g,1)){var m="]";g+=1}else m=null,t&&h('"]"');if(null!==m){var w=p(),w=null!==w?w:"";if(null!==w){var x=q();if(null!==x){var z=p(),z=null!==z?z:"";if(null!==z){var y=n();null!==y?f=[f,k,l,m,w,x,z,y]:(f=null,g=e)}else f=null,g=e}else f=null,g=e}else f=null,g=e}else f=null,g=e}else f=null,g=e}else f=null,g=e}else f=null,g=e;null!==f?(e=f[7],e[f[0]]=
[f[2]].concat(f[5])):e=null;null===e&&(e=null,g=d);v[c]={nextPos:g,result:e};return e}function n(){var c="MoreTokens@"+g,d=v[c];if(d)return g=d.nextPos,d.result;d=m();if(null===d){d=g;if(""===a.substr(g,0)){var e="";g+=0}else e=null,t&&h('""');e=null!==e?{}:null;null===e&&(e=null,g=d);d=null!==e?e:null}v[c]={nextPos:g,result:d};return d}function r(){var c="Data@"+g,d=v[c];if(d)return g=d.nextPos,d.result;var d=g,e=[];if("\\]"===a.substr(g,2)){var f="\\]";g+=2}else f=null,t&&h('"\\\\]"');null===f&&
(null!==a.substr(g).match(/^[^\]]/)?(f=a.charAt(g),g++):(f=null,t&&h("[^\\]]")),f=null!==f?f:null);for(;null!==f;)e.push(f),"\\]"===a.substr(g,2)?(f="\\]",g+=2):(f=null,t&&h('"\\\\]"')),null===f&&(null!==a.substr(g).match(/^[^\]]/)?(f=a.charAt(g),g++):(f=null,t&&h("[^\\]]")),f=null!==f?f:null);e=null!==e?e.join(""):null;null===e&&(e=null,g=d);v[c]={nextPos:g,result:e};return e}function q(){var c="MoreData@"+g,d=v[c];if(d)return g=d.nextPos,d.result;var e=d=g;if("["===a.substr(g,1)){var f="[";g+=1}else f=
null,t&&h('"["');if(null!==f){var k=r();if(null!==k){if("]"===a.substr(g,1)){var l="]";g+=1}else l=null,t&&h('"]"');if(null!==l){var m=p(),m=null!==m?m:"";if(null!==m){var n=q();null!==n?f=[f,k,l,m,n]:(f=null,g=e)}else f=null,g=e}else f=null,g=e}else f=null,g=e}else f=null,g=e;e=null!==f?[f[1]].concat(f[4]):null;null===e&&(e=null,g=d);null!==e?d=e:(d=g,""===a.substr(g,0)?(e="",g+=0):(e=null,t&&h('""')),e=null!==e?[]:null,null===e&&(e=null,g=d),d=null!==e?e:null);v[c]={nextPos:g,result:d};return d}
function s(){var c="TokenName@"+g,d=v[c];if(d)return g=d.nextPos,d.result;var e=d=g;if(null!==a.substr(g).match(/^[a-zA-Z]/)){var f=a.charAt(g);g++}else f=null,t&&h("[a-zA-Z]");if(null!==f){if(null!==a.substr(g).match(/^[a-zA-Z]/)){var k=a.charAt(g);g++}else k=null,t&&h("[a-zA-Z]");null!==k?f=[f,k]:(f=null,g=e)}else f=null,g=e;null!==f?e=f:(null!==a.substr(g).match(/^[a-zA-Z]/)?(e=a.charAt(g),g++):(e=null,t&&h("[a-zA-Z]")),e=null!==e?e:null);e=null!==e?1===e.length?e[0]:e.join("").toUpperCase():null;
null===e&&(e=null,g=d);v[c]={nextPos:g,result:e};return e}function p(){var c="WhiteSpace@"+g,d=v[c];if(d)return g=d.nextPos,d.result;d=[];if(" "===a.substr(g,1)){var e=" ";g+=1}else e=null,t&&h('" "');null===e&&("\n"===a.substr(g,1)?(e="\n",g+=1):(e=null,t&&h('"\\n"')),e=null!==e?e:null);for(;null!==e;)d.push(e)," "===a.substr(g,1)?(e=" ",g+=1):(e=null,t&&h('" "')),null===e&&("\n"===a.substr(g,1)?(e="\n",g+=1):(e=null,t&&h('"\\n"')),e=null!==e?e:null);v[c]={nextPos:g,result:d};return d}function y(){var c;
a:{c=A;c.sort();for(var d=null,f=[],h=0;h<c.length;h++)c[h]!==d&&(f.push(c[h]),d=c[h]);switch(f.length){case 0:c="end of input";break a;case 1:c=f[0];break a;default:c=f.slice(0,f.length-1).join(", ")+" or "+f[f.length-1]}}d=Math.max(g,x);d=d<a.length?e(a.charAt(d)):"end of input";return"Expected "+c+" but "+d+" found."}function B(){for(var c=1,d=1,e=!1,f=0;f<x;f++){var g=a.charAt(f);"\n"===g?(e||c++,d=1,e=!1):"\r"===g|"\u2028"===g||"\u2029"===g?(c++,d=1,e=!0):(d++,e=!1)}return{line:c,column:d}}var w=
{Data:r,MoreData:q,MoreTokens:n,MoreVars:k,Moves:l,Start:function(){var c="Start@"+g,d=v[c];if(d)return g=d.nextPos,d.result;var e=d=g;if("(;"===a.substr(g,2)){var k="(;";g+=2}else k=null,t&&h('"(;"');if(null!==k){var l=m();if(null!==l){var n=f();if(null!==n){if(")"===a.substr(g,1)){var p=")";g+=1}else p=null,t&&h('")"');null!==p?k=[k,l,n,p]:(k=null,g=e)}else k=null,g=e}else k=null,g=e}else k=null,g=e;e=null!==k?glift.rules.movenode(glift.rules.properties(k[1]),k[2]).renumber():null;null===e&&(e=
null,g=d);v[c]={nextPos:g,result:e};return e},TokenName:s,Tokens:m,Variations:f,WhiteSpace:p};if(void 0!==c){if(void 0===w[c])throw Error("Invalid rule name: "+e(c)+".");}else c="Start";var g=0,t=!0,x=0,A=[],v={},w=w[c]();if(null===w||g!==a.length)throw w=B(),new this.SyntaxError(y(),w.line,w.column);return w},toSource:function(){return this._source},SyntaxError:function(a,c,d){this.name="SyntaxError";this.message=a;this.line=c;this.column=d}};a.SyntaxError.prototype=Error.prototype;return a}();
glift.controllers={controllerMap:{},create:function(a){a=glift.controllers.processOptions(a);if(a.controllerType in glift.controllers.controllerMap)return glift.controllers.controllerMap[a.controllerType](a);throw"No controller found for type: "+a.controllerType;}};
(function(){var a=glift.enums.controllerTypes.BASE;glift.controllers.createBaseController=function(){return new b};glift.controllers.controllerMap[a]=glift.controllers.createBaseController;var b=function(){};b.prototype={addStone:function(){throw"Not Implemented";},initialize:function(a){a=glift.rules;var b=this.sgfString;this.initPosition=a.treepath.parseInitPosition(this.initialPosition);this.movetree=a.movetree.getFromSgf(b,this.initPosition);this.goban=a.goban.getFromMoveTree(this.movetree,this.initPosition);
return this.getEntireBoardState()},getEntireBoardState:function(){return glift.rules.intersections.getFullBoardData(this.movetree,this.goban)},canAddStone:function(a,b){return this.goban.placeable(a,b)},getCurrentPlayer:function(){return this.movetree.getCurrentPlayer()},getIntersections:function(){return this.movetree.getIntersections()}}})();
glift.controllers.processOptions=function(a){var b={controllerType:"STATIC_PROBLEM_STUDY",initialPosition:[],sgfString:""},c;for(c in a){var d=a[c];switch(c){case "controllerType":if("string"==glift.util.typeOf(d)&&d in glift.enums.controllerTypes)b.controllerType=d;else throw"Unknown controllerType: "+d;break;case "initialPosition":b.initialPosition=glift.rules.parseInitPosition(d);break;case "sgfString":if("string"===glift.util.typeOf(d))b.sgfString=d;else throw"Bad type for sgfString: "+d;}}return b};
(function(){var a=glift.util,b=glift.enums.controllerTypes.STATIC_PROBLEM_STUDY;glift.controllers.staticProblemStudy={_create:function(b){var e=glift.util.beget(glift.controllers.createBaseController()),e=a.setMethods(e,c);e.initOptions(b);return e}};glift.controllers.createStaticProblemStudy=function(a){a=glift.controllers.staticProblemStudy._create(a);a.initialize("foo");return a};glift.controllers.controllerMap[b]=glift.controllers.createStaticProblemStudy;var c={initOptions:function(a){this.sgfString=
a.sgfString||"";this.initialPosition=a.initialPosition;return this},addStone:function(b,c){var h=glift.enums.problemResults,f=glift.enums.controllerMessages,k=f.FAILURE,l=f.DONE,m=f.CONTINUE,n=h.CORRECT,r=h.INCORRECT,q=h.INDETERMINATE;if(!this.goban.addStone(b,c).successful)return{message:k,reason:"Cannot add stone"};k=this.movetree.findNextMove(b,c);this.lastPlayed={point:b,color:c};if(k===a.none)return{message:l,result:r};this.movetree.moveDown(k);var k=this.movetree.isCorrectPosition(),s=glift.rules.intersections.getFullBoardData(this.movetree,
this.goban);if(k===n)return{message:l,result:n,data:s};if(k===q)return h=glift.math.getRandomInt(0,this.movetree.getNode().numChildren()-1),this.movetree.moveDown(h),h=this.movetree.getProperties().getMove(),this.goban.addStone(h.point,h.color),s=glift.rules.intersections.getFullBoardData(this.movetree,this.goban),{message:m,result:q,data:s};if(k===h.INCORRECT)return{message:f.DONE,result:r};throw"Unexpected result output: "+k;}}})();
glift.bridge={setDisplayState:function(a,b){var c=glift.enums.marks;b.intersections().clearMarks();for(var d in a.points){var e=a.points[d],h=e.point;if("stone"in e){var f=e.stone;b.intersections().setStoneColor(h,f)}for(var k in c)k in e&&(k===c.LABEL?b.intersections().addMarkPt(h,k,e[k]):b.intersections().addMarkPt(h,k))}}};
glift.bridge.getFromMovetree=function(a){var b=glift.displays.bboxFromPts,c=glift.util.point,d=glift.enums.boardRegions,e=a.getIntersections()-1,h=Math.ceil(e/2),f={},k={},l=0;f[d.TOP_LEFT]=b(c(0,0),c(h+1,h+1));f[d.TOP_RIGHT]=b(c(h-1,0),c(e,h+1));f[d.BOTTOM_LEFT]=b(c(0,h-1),c(h+1,e));f[d.BOTTOM_RIGHT]=b(c(h-1,h-1),c(e,e));a.recurseFromRoot(function(a){a=a.getProperties().getAllStones();for(var b in a)for(var c=a[b],d=0;d<c.length;d++){var e=c[d];l+=1;for(var h in f)f[h].contains(e)&&(void 0===k[h]&&
(k[h]=[]),k[h].push(e))}});return glift.bridge._getRegionFromTracker(k,l)};glift.bridge._getRegionFromTracker=function(a,b){var c=[],d;for(d in a){if(a[d].length===b)return d;c.push(d)}if(2!==c.length)return glift.boardRegions.ALL;var c=glift.util.intersection(glift.util.regions.getComponents(c[0]),glift.util.regions.getComponents(c[1])),e;for(e in c)return e;return glift.boardRegions.ALL};glift.widgets={};
glift.widgets.basicProblem=function(a){var b=glift.createDisplay(a);a.controllerType="STATIC_PROBLEM_STUDY";a=glift.createController(a);glift.bridge.getFromMovetree(a.movetree);glift.bridge.setDisplayState(a.getEntireBoardState(),b);return new glift.widgets._BasicProblem(b,a)};
glift.widgets._BasicProblem=function(a,b){this.display=a;this.controller=b;var c={BLACK:"BLACK_HOVER",WHITE:"WHITE_HOVER"};a.intersections().setEvent("click",function(c){var e=b.getCurrentPlayer();c=b.addStone(c,e);$("#extra_info").text(c.message+"//"+(c.result||""));void 0!==c.data&&glift.bridge.setDisplayState(c.data,a)});a.intersections().setEvent("mouseover",function(d){var e=b.getCurrentPlayer();b.canAddStone(d,e)&&a.intersections().setStoneColor(d,c[e])});a.intersections().setEvent("mouseout",
function(c){var e=b.getCurrentPlayer();b.canAddStone(c,e)&&a.intersections().setStoneColor(c,"EMPTY")})};glift.widgets._BasicProblem.prototype={redraw:function(){this.display.redraw()},destroy:function(){this.display.destroy()},enableAutoResizing:function(){var a=this,b=function(){a.redraw()},c;$(window).resize(function(a){clearTimeout(c);c=setTimeout(b,100)})}};
(function(){glift.widgets.iconBar=function(b){var c=[],d=0,e=0;if(void 0!==b.divId)throw"Must define 'divId' as an option";void 0!==b.icons&&(c=b.icons);void 0!==b.vertMargin&&(d=b.vertMargin);void 0!==b.horzMargin&&(e=b.horzMargin);void 0!==b.theme&&(this.theme=b.theme);for(b=0;b<c.length;b++)if(void 0===glift.displays.gui.icons[c[b]])throw"Icon string undefined in glift.displays.gui.icons ["+c[b]+"]";return(new a(divId,void 0,"DEFAULT",c,d,e)).draw()};var a=function(a,c,d,e,h,f){this.divId=a;this.boundingBox=
c;this.themeName=d;this.subTheme=glift.themes.get(d).icons;this.iconNames=e;this.vertMargin=h;this.horzMargin=f;this.iconObjects={};this.iconButtons={}};a.prototype={draw:function(){for(var a=[],a=0;a<this.iconNames.length;a++){var c=this.iconNames[a];void 0!==this.subTheme[c]?obj.attr(this.subTheme[c]):obj.attr(this.subTheme.DEFAULT);this.iconObjects[c]=obj;raphObjects.push(obj)}a=raph.getBboxes(raphObjects);a=raph.rowCenter(this.boundingBox,a,this.vertMargin,this.horzMargin,0,0).transforms;raph.applyTransforms(a,
raphObjects);for(var d in this.iconObjects)this.iconButtons[d]=glift.displays.raphael.button(this.paper,{name:c},this.iconObjects[d]);return this},setHover:function(a,c,d){this.iconButtons[a].setMouseOver(c).setMouseOut(d)},setClick:function(a,c,d){this.iconButtons[a].setClick(c,d)},getIcon:function(a){return{name:a,obj:this.iconObjects[a],button:this.iconButtons[a]}},forEachIcon:function(a){for(var c=0;c<this.iconNames.length;c++)a(this.getIcon(this.iconNames[c]))},redraw:function(){this.destroy();
this.draw()},destroy:function(){this.forEachIcon(function(a){a.obj.remove();a.button.destroy()});this.iconObjects={};this.iconButtons={};return this}}})();
(function(){glift.widgets.problemSeries=function(a){var b=""+(a.divId||"glift_display"),c="glift_internal_main_"+glift.util.idGenerator.next(),d="glift_internal_footer_"+glift.util.idGenerator.next();a.divId=c;return new ProblemSeries(a,b,c,d)};ProblemSeries=function(a,b,c,d){this.options=a;this.wrapperDiv=b;this.mainDiv=c;this.footerDiv=d;this.iconBar=this.problemDisplay=void 0;this.draw()};ProblemSeries.prototype={draw:function(){this.createDivs();this.resizeDivs();this.problemDisplay=glift.widgets.basicProblem(this.options);
var a=($("#"+this.mainDiv).width()-this.problemDisplay.display.width())/2;this.iconBar=glift.widgets.iconBar({divId:this.footerDiv,vertMargin:5,horzMargin:a,icons:["chevron-left","refresh","chevron-right","roadmap","small-gear"]})},createDivs:function(){$("#"+this.wrapperDiv).append('<div id = "'+this.mainDiv+'"></div>');$("#"+this.wrapperDiv).append('<div id = "'+this.footerDiv+'"></div>');return this},resizeDivs:function(){var a=$("#"+this.wrapperDiv).height();$("#"+this.mainDiv).css({position:"absolute",
width:"100%",height:a-50,top:0});$("#"+this.footerDiv).css({position:"absolute",width:"100%",height:50,"text-align":"center",bottom:0});return this},redraw:function(){this.destroy();this.draw()},destroy:function(){this.problemDisplay&&this.problemDisplay.destroy();this.iconBar&&this.iconBar.destroy();$("#"+this.wrapperDiv).empty();return this}}})();
