/*
 Glift: A Responsive Javascript library for the game Go.

 @copyright Josh Hoak
 @license MIT License (see LICENSE.txt)
 --------------------------------------
 FastClick: polyfill to remove click delays on browsers with touch UIs.

 @version 0.6.11
 @codingstandard ftlabs-jsv2
 @copyright The Financial Times Limited [All Rights Reserved]
 @license MIT License (see LICENSE.txt)
*/
(function(){var a=window.glift||{};a.global={version:"0.8.0",fastClickEnabled:!1,enableFastClick:function(){a.global.fastClickEnabled||(FastClick.attach(document.body),a.global.fastClickEnabled=!0)},debugMode:!1,performanceDebugLevel:"none",perf:{},active:{}};window.glift=a})();
glift.util={logz:function(a){var b=a;if("array"===glift.util.typeOf(a)||"object"===glift.util.typeOf(a))b=JSON.stringify(a);console.log(""+b);return glift.util.none},typeOf:function(a){var b=typeof a;"object"===b&&(a?a instanceof Array&&(b="array"):b="null");return b},isArray:function(a){return a&&"object"===typeof a&&a.constructor===Array},arrayEquals:function(a,b){if(void 0===a||void 0==b||a.length!==b.length)return!1;for(var c=0;c<a.length;c++)if(a[c]!==b[c])return!1;return!0},inBounds:function(a,
b){return a<b&&0<=a},outBounds:function(a,b){return a>=b||0>a},intersection:function(a,b){var c={},d;for(d in a)void 0!==b[d]&&(c[d]=1);return c},getKeyWithDefault:function(a,b,c){void 0===a[b]&&(a[b]=c);return a[b]},sizeOf:function(a){var b=0,c;for(c in a)b+=1;return b},setMethods:function(a,b){for(var c in b)a[c]=b[c].bind(a);return a},beget:function(a){var b=function(){};b.prototype=a;return new b},simpleClone:function(a){if("array"!==glift.util.typeOf(a)&&"object"!==glift.util.typeOf(a))return a;
if(a instanceof Date){var b=new Date;b.setTime(a.getTime());return b}if("array"===glift.util.typeOf(a)){for(var b=[],c=0,d=a.length;c<d;c++)b[c]=glift.util.simpleClone(a[c]);return b}if("object"===glift.util.typeOf(a)){b={};for(c in a)a.hasOwnProperty(c)&&(b[c]=glift.util.simpleClone(a[c]));return b}throw Error("Unable to copy obj! Its type isn't supported.");}};glift.util.debugl=function(a){glift.debugOn&&glift.util.log(a)};
glift.util.log=function(a){("array"===glift.util.typeOf(a)||"object"===glift.util.typeOf(a))&&JSON.stringify(a);void 0!==console&&void 0!==console.log&&console.log(a)};(function(){var a=function(){this.type="none"};a.prototype={toString:function(){return"None"}};glift.util.none=new a})();
glift.util.colors={isLegalColor:function(a){return a===glift.enums.states.BLACK||a===glift.enums.states.WHITE||a===glift.enums.states.EMPTY},oppositeColor:function(a){return a===glift.enums.states.BLACK?glift.enums.states.WHITE:a===glift.enums.states.WHITE?glift.enums.states.BLACK:a}};
glift.enums={states:{BLACK:"BLACK",WHITE:"WHITE",EMPTY:"EMPTY"},boardAlignments:{TOP:"TOP",RIGHT:"RIGHT",CENTER:"CENTER"},directions:{LEFT:"LEFT",RIGHT:"RIGHT",TOP:"TOP",BOTTOM:"BOTTOM"},boardRegions:{LEFT:"LEFT",RIGHT:"RIGHT",TOP:"TOP",BOTTOM:"BOTTOM",TOP_LEFT:"TOP_LEFT",TOP_RIGHT:"TOP_RIGHT",BOTTOM_LEFT:"BOTTOM_LEFT",BOTTOM_RIGHT:"BOTTOM_RIGHT",ALL:"ALL",AUTO:"AUTO"},controllerMessages:{CONTINUE:"CONTINUE",DONE:"DONE",FAILURE:"FAILURE"},marks:{CIRCLE:"CIRCLE",SQUARE:"SQUARE",TRIANGLE:"TRIANGLE",
XMARK:"XMARK",STONE_MARKER:"STONE_MARKER",LABEL:"LABEL",VARIATION_MARKER:"VARIATION_MARKER",CORRECT_VARIATION:"CORRECT_VARIATION"},problemResults:{CORRECT:"CORRECT",INCORRECT:"INCORRECT",INDETERMINATE:"INDETERMINATE",FAILURE:"FAILURE"},displayDataTypes:{PARTIAL:"PARTIAL",FULL:"FULL"},svgElements:{BOARD_BASE:"board_base",BOARD_LINE:"board_line",BUTTON:"button",MARK:"mark",MARK_CONTAINER:"mark_container",GLIFT_ELEMENT:"glift_element",STARPOINT:"starpoint",STONE:"stone",STONE_SHADOW:"stone_shadow",ICON:"icon",
GUIDE_LINE:"guide_line"},showVariations:{ALWAYS:"ALWAYS",NEVER:"NEVER",MORE_THAN_ONE:"MORE_THAN_ONE"},widgetTypes:{CORRECT_VARIATIONS_PROBLEM:"CORRECT_VARIATIONS_PROBLEM",EXAMPLE:"EXAMPLE",GAME_VIEWER:"GAME_VIEWER",STANDARD_PROBLEM:"STANDARD_PROBLEM"},boardComponents:{BOARD:"BOARD",COMMENT_BOX:"COMMENT_BOX",ICONBAR:"ICONBAR"}};(function(){glift.errors={};glift.errors.ParseError=function(a){this.name="ParseError";this.message=a||""};glift.errors.ParseError.prototype=Error()})();
function FastClick(a){var b,c=this;this.trackingClick=!1;this.trackingClickStart=0;this.targetElement=null;this.lastTouchIdentifier=this.touchStartY=this.touchStartX=0;this.touchBoundary=10;this.layer=a;if(!a||!a.nodeType)throw new TypeError("Layer must be a document node");this.onClick=function(){return FastClick.prototype.onClick.apply(c,arguments)};this.onMouse=function(){return FastClick.prototype.onMouse.apply(c,arguments)};this.onTouchStart=function(){return FastClick.prototype.onTouchStart.apply(c,
arguments)};this.onTouchMove=function(){return FastClick.prototype.onTouchMove.apply(c,arguments)};this.onTouchEnd=function(){return FastClick.prototype.onTouchEnd.apply(c,arguments)};this.onTouchCancel=function(){return FastClick.prototype.onTouchCancel.apply(c,arguments)};FastClick.notNeeded(a)||(this.deviceIsAndroid&&(a.addEventListener("mouseover",this.onMouse,!0),a.addEventListener("mousedown",this.onMouse,!0),a.addEventListener("mouseup",this.onMouse,!0)),a.addEventListener("click",this.onClick,
!0),a.addEventListener("touchstart",this.onTouchStart,!1),a.addEventListener("touchmove",this.onTouchMove,!1),a.addEventListener("touchend",this.onTouchEnd,!1),a.addEventListener("touchcancel",this.onTouchCancel,!1),Event.prototype.stopImmediatePropagation||(a.removeEventListener=function(b,c,f){var g=Node.prototype.removeEventListener;"click"===b?g.call(a,b,c.hijacked||c,f):g.call(a,b,c,f)},a.addEventListener=function(b,c,f){var g=Node.prototype.addEventListener;"click"===b?g.call(a,b,c.hijacked||
(c.hijacked=function(a){a.propagationStopped||c(a)}),f):g.call(a,b,c,f)}),"function"===typeof a.onclick&&(b=a.onclick,a.addEventListener("click",function(a){b(a)},!1),a.onclick=null))}FastClick.prototype.deviceIsAndroid=0<navigator.userAgent.indexOf("Android");FastClick.prototype.deviceIsIOS=/iP(ad|hone|od)/.test(navigator.userAgent);FastClick.prototype.deviceIsIOS4=FastClick.prototype.deviceIsIOS&&/OS 4_\d(_\d)?/.test(navigator.userAgent);
FastClick.prototype.deviceIsIOSWithBadTarget=FastClick.prototype.deviceIsIOS&&/OS ([6-9]|\d{2})_\d/.test(navigator.userAgent);FastClick.prototype.needsClick=function(a){switch(a.nodeName.toLowerCase()){case "button":case "select":case "textarea":if(a.disabled)return!0;break;case "input":if(this.deviceIsIOS&&"file"===a.type||a.disabled)return!0;break;case "label":case "video":return!0}return/\bneedsclick\b/.test(a.className)};
FastClick.prototype.needsFocus=function(a){switch(a.nodeName.toLowerCase()){case "textarea":case "select":return!0;case "input":switch(a.type){case "button":case "checkbox":case "file":case "image":case "radio":case "submit":return!1}return!a.disabled&&!a.readOnly;default:return/\bneedsfocus\b/.test(a.className)}};
FastClick.prototype.sendClick=function(a,b){var c,d;document.activeElement&&document.activeElement!==a&&document.activeElement.blur();d=b.changedTouches[0];c=document.createEvent("MouseEvents");c.initMouseEvent("click",!0,!0,window,1,d.screenX,d.screenY,d.clientX,d.clientY,!1,!1,!1,!1,0,null);c.forwardedTouchEvent=!0;a.dispatchEvent(c)};
FastClick.prototype.focus=function(a){var b;this.deviceIsIOS&&a.setSelectionRange&&0!==a.type.indexOf("date")&&"time"!==a.type?(b=a.value.length,a.setSelectionRange(b,b)):a.focus()};FastClick.prototype.updateScrollParent=function(a){var b,c;b=a.fastClickScrollParent;if(!b||!b.contains(a)){c=a;do{if(c.scrollHeight>c.offsetHeight){b=c;a.fastClickScrollParent=c;break}c=c.parentElement}while(c)}b&&(b.fastClickLastScrollTop=b.scrollTop)};
FastClick.prototype.getTargetElementFromEventTarget=function(a){return a.nodeType===Node.TEXT_NODE?a.parentNode:a};
FastClick.prototype.onTouchStart=function(a){var b,c,d;if(1<a.targetTouches.length)return!0;b=this.getTargetElementFromEventTarget(a.target);c=a.targetTouches[0];if(this.deviceIsIOS){d=window.getSelection();if(d.rangeCount&&!d.isCollapsed)return!0;if(!this.deviceIsIOS4){if(c.identifier===this.lastTouchIdentifier)return a.preventDefault(),!1;this.lastTouchIdentifier=c.identifier;this.updateScrollParent(b)}}this.trackingClick=!0;this.trackingClickStart=a.timeStamp;this.targetElement=b;this.touchStartX=
c.pageX;this.touchStartY=c.pageY;200>a.timeStamp-this.lastClickTime&&a.preventDefault();return!0};FastClick.prototype.touchHasMoved=function(a){a=a.changedTouches[0];var b=this.touchBoundary;return Math.abs(a.pageX-this.touchStartX)>b||Math.abs(a.pageY-this.touchStartY)>b?!0:!1};FastClick.prototype.onTouchMove=function(a){if(!this.trackingClick)return!0;if(this.targetElement!==this.getTargetElementFromEventTarget(a.target)||this.touchHasMoved(a))this.trackingClick=!1,this.targetElement=null;return!0};
FastClick.prototype.findControl=function(a){return void 0!==a.control?a.control:a.htmlFor?document.getElementById(a.htmlFor):a.querySelector("button, input:not([type=hidden]), keygen, meter, output, progress, select, textarea")};
FastClick.prototype.onTouchEnd=function(a){var b,c,d=this.targetElement;if(!this.trackingClick)return!0;if(200>a.timeStamp-this.lastClickTime)return this.cancelNextClick=!0;this.cancelNextClick=!1;this.lastClickTime=a.timeStamp;b=this.trackingClickStart;this.trackingClick=!1;this.trackingClickStart=0;this.deviceIsIOSWithBadTarget&&(c=a.changedTouches[0],d=document.elementFromPoint(c.pageX-window.pageXOffset,c.pageY-window.pageYOffset)||d,d.fastClickScrollParent=this.targetElement.fastClickScrollParent);
c=d.tagName.toLowerCase();if("label"===c){if(b=this.findControl(d)){this.focus(d);if(this.deviceIsAndroid)return!1;d=b}}else if(this.needsFocus(d)){if(100<a.timeStamp-b||this.deviceIsIOS&&window.top!==window&&"input"===c)return this.targetElement=null,!1;this.focus(d);if(!this.deviceIsIOS4||"select"!==c)this.targetElement=null,a.preventDefault();return!1}if(this.deviceIsIOS&&!this.deviceIsIOS4&&(b=d.fastClickScrollParent)&&b.fastClickLastScrollTop!==b.scrollTop)return!0;this.needsClick(d)||(a.preventDefault(),
this.sendClick(d,a));return!1};FastClick.prototype.onTouchCancel=function(){this.trackingClick=!1;this.targetElement=null};FastClick.prototype.onMouse=function(a){return!this.targetElement||a.forwardedTouchEvent||!a.cancelable?!0:!this.needsClick(this.targetElement)||this.cancelNextClick?(a.stopImmediatePropagation?a.stopImmediatePropagation():a.propagationStopped=!0,a.stopPropagation(),a.preventDefault(),!1):!0};
FastClick.prototype.onClick=function(a){if(this.trackingClick)return this.targetElement=null,this.trackingClick=!1,!0;if("submit"===a.target.type&&0===a.detail)return!0;a=this.onMouse(a);a||(this.targetElement=null);return a};
FastClick.prototype.destroy=function(){var a=this.layer;this.deviceIsAndroid&&(a.removeEventListener("mouseover",this.onMouse,!0),a.removeEventListener("mousedown",this.onMouse,!0),a.removeEventListener("mouseup",this.onMouse,!0));a.removeEventListener("click",this.onClick,!0);a.removeEventListener("touchstart",this.onTouchStart,!1);a.removeEventListener("touchmove",this.onTouchMove,!1);a.removeEventListener("touchend",this.onTouchEnd,!1);a.removeEventListener("touchcancel",this.onTouchCancel,!1)};
FastClick.notNeeded=function(a){var b;if("undefined"===typeof window.ontouchstart)return!0;if(/Chrome\/[0-9]+/.test(navigator.userAgent))if(FastClick.prototype.deviceIsAndroid){if((b=document.querySelector("meta[name=viewport]"))&&-1!==b.content.indexOf("user-scalable=no"))return!0}else return!0;return"none"===a.style.msTouchAction?!0:!1};FastClick.attach=function(a){return new FastClick(a)};
"undefined"!==typeof define&&define.amd?define(function(){return FastClick}):"undefined"!==typeof module&&module.exports?(module.exports=FastClick.attach,module.exports.FastClick=FastClick):window.FastClick=FastClick;glift.util._IdGenerator=function(a){this.seed=a||0};glift.util._IdGenerator.prototype={next:function(){var a=this.seed+"";this.seed+=1;return a}};glift.util.idGenerator=new glift.util._IdGenerator(0);
glift.keyMappings={_nameToCode:{ARROW_LEFT:37,ARROW_UP:38,ARROW_RIGHT:39,ARROW_:40,BACKSPACE:8,ENTER:13,SHIFT:16,FORWARD_SLASH:191,A:65,B:66,C:67,D:68,E:69,F:70,G:71,H:72,I:73,J:74,K:75},nameToCode:function(a){return glift.keyMappings._nameToCode[a]},_codeToName:void 0,codeToName:function(a){if(void 0===glift.keyMappings._codeToName){var b={},c;for(c in glift.keyMappings._nameToCode)b[glift.keyMappings._nameToCode[c]]=c;glift.keyMappings._codeToName=b}return glift.keyMappings._codeToName[a]}};
glift.math={abs:function(a){return 0<=a?a:-1*a},max:function(a,b){return a>b?a:b},min:function(a,b){return a>b?b:a},isEven:function(a){return 0==a%2?!0:!1},getRandomInt:function(a,b){return Math.floor(Math.random()*(b-a+1))+a}};
glift.util.perfLog=function(a){if(!(void 0===glift.global.performanceDebugLevel||"none"===glift.global.performanceDebugLevel)){var b=glift.util.perfTime(),c=glift.global.perf.last;console.log("Since Major Record: "+(b-glift.global.perf.lastMajor+"ms. "+a));"fine"===glift.global.performanceDebugLevel&&console.log("  Since Last Record: "+(b-c+"ms. "+a));glift.global.perf.last=b}};
glift.util.majorPerfLog=function(a){if(!(void 0===glift.global.performanceDebugLevel||"none"===glift.global.performanceDebugLevel)){var b=glift.util.perfTime();glift.util.perfLog(a);glift.global.perf.lastMajor=b}};glift.util.perfDone=function(){if(!(void 0===glift.global.performanceDebugLevel||"none"===glift.global.performanceDebugLevel)){var a=glift.util.perfTime(),b=glift.global.perf.first;console.log("---Performance Test Complete---");console.log("Since Beginning: "+(a-b)+"ms.")}};
glift.util.perfInit=function(){if(!(void 0===glift.global.performanceDebugLevel||"none"===glift.global.performanceDebugLevel)){var a=glift.util.perfTime();glift.global.perf={first:a,last:a,lastMajor:a}}};glift.util.perfTime=function(){return(new Date).getTime()};
(function(){glift.util.point=function(b,c){return new a(b,c)};glift.util.coordToString=function(a,c){return a+","+c};glift.util.pointFromString=function(a){try{var c=a.split(","),d=parseInt(c[0]),e=parseInt(c[1]);return glift.util.point(d,e)}catch(f){throw"Parsing Error! Couldn't parse a point from: "+a;}};glift.util.pointFromSgfCoord=function(a){if(2!=a.length)throw"Unknown SGF Coord length: "+a.length;return glift.util.point(a.charCodeAt(0)-97,a.charCodeAt(1)-97)};glift.util.pointFromHash=function(a){return glift.util.pointFromString(a)};
var a=function(a,c){this._x=a;this._y=c};a.prototype={x:function(){return this._x},y:function(){return this._y},equals:function(a){return this._x===a.x()&&this._y===a.y()},clone:function(){return glift.util.point(this.x(),this.y())},toSgfCoord:function(){return String.fromCharCode(this.x()+97)+String.fromCharCode(this.y()+97)},hash:function(){return this.toString()},toString:function(){return glift.util.coordToString(this.x(),this.y())},translate:function(a,c){return glift.util.point(this.x()+a,this.y()+
c)},log:function(){glift.util.logz(this.toString())}}})();glift.util.regions={getComponents:function(a){var b=glift.enums.boardRegions,c={};a===b.TOP_LEFT?(c[b.TOP]=1,c[b.LEFT]=1):a===b.TOP_RIGHT?(c[b.TOP]=1,c[b.RIGHT]=1):a===b.BOTTOM_LEFT?(c[b.BOTTOM]=1,c[b.LEFT]=1):a===b.BOTTOM_RIGHT?(c[b.BOTTOM]=1,c[b.RIGHT]=1):a==b.TOP?c[b.TOP]=1:a==b.BOTTOM?c[b.BOTTOM]=1:a==b.LEFT?c[b.LEFT]=1:a==b.RIGHT&&(c[b.RIGHT]=1);return c}};
glift.testUtil={ptlistToMap:function(a){for(var b={},c=0;c<a.length;c++){var d=a[c];void 0!==d.value?b[d.point.hash()]=d:b[d.hash()]=d}return b},assertFullDiv:function(a){ok(0!==d3.selectAll("#"+a+" svg")[0].length,"Div should contain contents")},assertEmptyDiv:function(a){deepEqual(d3.selectAll("#"+a+" svg")[0].length,0,"Div should not contain contents")}};
glift.themes={registered:{},get:function(a){var b=glift.themes.registered;a=!(a in b)?glift.util.none:b[a];return a===glift.util.none?a:glift.themes.deepCopy({},a,b.DEFAULT)},deepCopy:function(a,b,c){for(var d in c){var e=glift.util.typeOf(c[d]),f=c;void 0!==b[d]&&(f=b);switch(e){case "object":a[d]=glift.themes.deepCopy({},b[d]||{},c[d]);break;case "array":for(var e={},f=[],g=c[d].concat(b[d]||[]),h=0;h<g.length;h++){var k=g[h];k in e||(f.push(k),e[k]=1)}a[d]=k;break;default:a[d]=f[d]}}return a},
has:function(a){return a in glift.themes.registered},setGoBoardBackground:function(a,b){if(a)a.board.imagefill=b;else throw"Yikes! Not a theme: cannot set background image.";}};
glift.themes.registered.DEFAULT={board:{fill:"#f5be7e",stroke:"#000000","stroke-width":1},starPoints:{sizeFraction:0.15,fill:"#000000"},lines:{stroke:"#000000","stroke-width":0.5},stones:{shadows:{stroke:"none",fill:"none"},marks:{"font-family":"sans-serif"},EMPTY:{fill:"blue",opacity:0,marks:{fill:"black",stroke:"black",VARIATION_MARKER:{stroke:"#A22",fill:"#A22"},CORRECT_VARIATION:{stroke:"#22D",fill:"#22D"}}},BLACK:{fill:"black",opacity:1,"stroke-width":1,stroke:"black",marks:{fill:"white",stroke:"white",
STONE_MARKER:{fill:"#CCF",opacity:0.6}}},BLACK_HOVER:{fill:"black",opacity:0.5},WHITE:{stroke:"black",fill:"white",opacity:1,"stroke-width":1,marks:{fill:"black",stroke:"black",STONE_MARKER:{fill:"#33F",opacity:0.6}}},WHITE_HOVER:{fill:"white",stroke:"black",opacity:0.5}},icons:{DEFAULT:{fill:"#0000AA",stroke:"black"},DEFAULT_HOVER:{fill:"cyan",stroke:"black"}},defs:{}};
glift.themes.registered.DEPTH={stones:{shadows:{stroke:"none",fill:"#777"},WHITE:{stroke:"white",fill:"white"},WHITE_HOVER:{fill:"white",stroke:"white",opacity:0.5}}};glift.themes.registered.MOODY={board:{fill:"#777777"},stones:{WHITE:{stroke:"white",fill:"white"},WHITE_HOVER:{fill:"white",stroke:"white",opacity:0.5}}};glift.themes.registered.TEXTBOOK={board:{fill:"#FFFFFF"}};glift.themes.registered.TRANSPARENT={board:{fill:"none"}};
glift.displays={create:function(a){glift.util.majorPerfLog("Before environment creation");var b=glift.displays.environment.get(a);glift.util.majorPerfLog("After environment creation");var c=a.theme||"DEFAULT",d=glift.themes.get(c);a.goBoardBackground&&""!==a.goBoardBackground&&glift.themes.setGoBoardBackground(d,a.goBoardBackground);return glift.displays.board.create(b,c,d)}};glift.displays.bboxFromPts=function(a,b){return new glift.displays._BoundingBox(a,b)};
glift.displays.bboxFromDiv=function(a){return glift.displays.bbox(glift.util.point(0,0),$("#"+a).width(),$("#"+a).height())};glift.displays.bbox=function(a,b,c){return new glift.displays._BoundingBox(a,glift.util.point(a.x()+b,a.y()+c))};glift.displays._BoundingBox=function(a,b){this._topLeftPt=a;this._botRightPt=b};
glift.displays._BoundingBox.prototype={topLeft:function(){return this._topLeftPt},botRight:function(){return this._botRightPt},width:function(){return this.botRight().x()-this.topLeft().x()},height:function(){return this.botRight().y()-this.topLeft().y()},top:function(){return this.topLeft().y()},left:function(){return this.topLeft().x()},bottom:function(){return this.botRight().y()},right:function(){return this.botRight().x()},hwRatio:function(){return this.height()/this.width()},center:function(){return glift.util.point(glift.math.abs((this.botRight().x()-
this.topLeft().x())/2)+this.topLeft().x(),glift.math.abs((this.botRight().y()-this.topLeft().y())/2)+this.topLeft().y())},contains:function(a){return a.x()>=this.topLeft().x()&&a.x()<=this.botRight().x()&&a.y()>=this.topLeft().y()&&a.y()<=this.botRight().y()},equals:function(a){return a.topLeft()&&this.topLeft().equals(a.topLeft())&&a.botRight()&&this.botRight().equals(a.botRight())},scale:function(a){var b=this.height()*a,c=this.width()*a;a=glift.util.point(this.topLeft().x()*a,this.topLeft().y()*
a);return glift.displays.bbox(a,c,b)},toString:function(){return this.topLeft().toString()+","+this.botRight().toString()},translate:function(a,b){return glift.displays.bboxFromPts(glift.util.point(this.topLeft().x()+a,this.topLeft().y()+b),glift.util.point(this.botRight().x()+a,this.botRight().y()+b))},hSplit:function(a){return this._splitBox("h",a)},vSplit:function(a){return this._splitBox("v",a)},_splitBox:function(a,b){if("array"!==glift.util.typeOf(b))throw"bboxSplits must be specified as an array. Was: "+
glift.util.typeOf(b);if(!("h"===a||"v"===a))throw"What!? The only splits allowed are 'v' or 'h'.  You supplied: "+a;for(var c=0,d=0;d<b.length;d++)c+=b[d];if(1<=c)throw"The box splits must sum to less than 1, but instead summed to: "+c;b.push(1-c);for(var c=0,e=[],f=this.topLeft().clone(),d=0;d<b.length;d++){var c=d===b.length-1?1:c+b[d],g="h"===a?this.botRight().x():this.topLeft().x()+this.width()*c,h="h"===a?this.topLeft().y()+this.height()*c:this.botRight().y(),g=glift.util.point(g,h);e.push(glift.displays.bboxFromPts(f,
g));g="h"===a?f.x():this.topLeft().x()+this.width()*c;f="h"===a?this.topLeft().y()+this.height()*c:f.y();f=glift.util.point(g,f)}return e}};
(function(){glift.displays.boardPoints=function(b,c,d){return new a(b,c,d)};glift.displays.boardPointsFromLineBox=function(a,c){for(var d=a.spacing,e=d/2,f=a.bbox,g=f.left()+a.extensionBox.left()*d,f=f.top()+a.extensionBox.top()*d,h=a.pointTopLeft.x(),k=a.pointTopLeft.y(),l={},m=0;m<=a.yPoints;m++)for(var q=0;q<=a.xPoints;q++){var n=g+q*d,r=f+m*d,p=glift.util.point(h+q,k+m),n=glift.util.point(n,r);l[p.hash()]={intPt:p,coordPt:n,bbox:glift.displays.bboxFromPts(glift.util.point(n.x()-e,n.y()-e),glift.util.point(n.x()+
e,n.y()+e))}}return glift.displays.boardPoints(l,d,c)};var a=function(a,c,d){this.points=a;this.spacing=c;this.radius=c/2;this.numIntersections=d};a.prototype={getCoords:function(){return this.points},getCoord:function(a){return this.points[a.hash()]},forEach:function(a){for(var c in this.points)a(this.points[c])},data:function(){var a=[];this.forEach(function(c){a.push(c)});return a},hasCoord:function(a){return void 0!==this.points[a.hash()]},starPoints:function(){for(var a=glift.util.point,c={9:[[2,
6],[4]],13:[[3,9],[6]],19:[[3,9,15]]}[this.numIntersections]||[],d=[],e=0;e<c.length;e++)for(var f=c[e],g=0;g<f.length;g++)for(var h=0;h<f.length;h++){var k=a(f[g],f[h]);this.hasCoord(k)&&d.push(k)}return d},_debugDraw:function(a,c){for(var d in this.points){var e=this.points[d].bbox.center().x(),f=this.points[d].bbox.center().y();a.circle(e,f,this.radius).attr({fill:c,opacity:0.3})}}}})();
(function(){glift.displays.cropbox={LINE_EXTENSION:0.5,DEFAULT_EXTENSION:0,OVERFLOW:1.5,create:function(b,c,d,e){return new a(b,c,d,e)},getFromRegion:function(a,c){var d=glift.util,e=glift.enums.boardRegions;a=a||e.ALL;var f=c-1,g=Math.ceil(f/2),h=0,k=0,l=f,m=f,q=this.DEFAULT_EXTENSION,n=this.DEFAULT_EXTENSION,r=this.DEFAULT_EXTENSION,p=this.DEFAULT_EXTENSION;switch(a){case e.LEFT:m=g+1;p=this.LINE_EXTENSION;break;case e.RIGHT:k=g-1;n=this.LINE_EXTENSION;break;case e.TOP:l=g+1;r=this.LINE_EXTENSION;
break;case e.BOTTOM:h=g-1;q=this.LINE_EXTENSION;break;case e.TOP_LEFT:l=g+1;r=this.LINE_EXTENSION;m=g+2;p=this.LINE_EXTENSION;break;case e.TOP_RIGHT:l=g+1;r=this.LINE_EXTENSION;k=g-2;n=this.LINE_EXTENSION;break;case e.BOTTOM_LEFT:h=g-1;q=this.LINE_EXTENSION;m=g+2;p=this.LINE_EXTENSION;break;case e.BOTTOM_RIGHT:h=g-1,q=this.LINE_EXTENSION,k=g-2,n=this.LINE_EXTENSION}e=glift.displays.bboxFromPts(d.point(k,h),d.point(m,l));d=glift.displays.bboxFromPts(d.point(n,q),d.point(p,r));return glift.displays.cropbox.create(e,
d,0,f)}};var a=function(a,c,d,e){this._cbox=a;this._extBox=c};a.prototype={cbox:function(){return this._cbox},extBox:function(){return this._extBox},xPoints:function(){return this.cbox().width()},yPoints:function(){return this.cbox().height()},widthMod:function(){var a=glift.displays.cropbox.OVERFLOW;return this.cbox().width()+this.extBox().topLeft().x()+this.extBox().botRight().x()+a},heightMod:function(){var a=glift.displays.cropbox.OVERFLOW;return this.cbox().height()+this.extBox().topLeft().y()+
this.extBox().botRight().y()+a}}})();
(function(){glift.displays.environment={TOPBAR_SIZE:0.1,BOTTOMBAR_SIZE:0.1,get:function(b){return new a(b)},getInitialized:function(a){return glift.displays.environment.get(a).init()}};var a=function(a){this.divId=a.divId||"glift_display";this.boardRegion=a.boardRegion||glift.enums.boardRegions.ALL;this.intersections=a.intersections||19;a=a.displayConfig||{};this.cropbox=void 0!==a.cropbox?a.cropbox:glift.displays.cropbox.getFromRegion(this.boardRegion,this.intersections);this.widthOverride=this.heightOverride=
!1;void 0!==a.divHeight&&(this.divHeight=a.divHeight,this.heightOverride=!0);void 0!==a.divWidth&&(this.divWidth=a.divWidth,this.widthOverride=!0)};a.prototype={init:function(){(!this.heightOverride||!this.widthOverride)&&this._resetDimensions();var a=this.divHeight,c=this.divWidth,d=this.cropbox,a=glift.displays.bboxFromPts(glift.util.point(0,0),glift.util.point(c,a)),c=glift.displays.getResizedBox(a,d),d=glift.displays.getLineBox(c,d),e=glift.displays.boardPointsFromLineBox(d,this.intersections);
this.divBox=a;this.goBoardBox=c;this.goBoardLineBox=d;this.boardPoints=e;return this},_resetDimensions:function(){var a=glift.displays.bboxFromDiv(this.divId);this.divHeight=a.height();this.divWidth=a.width();return this},_debugDrawAll:function(){var a=Raphael(this.divId,"100%","100%");this.divBox.draw(a,"yellow");this.resizedBox.draw(a,"red");this.goBoardBox.draw(a,"orange");this.goBoardLineBox.bbox.draw(a,"red");this.goBoardLineBox._debugDrawLines(a,"blue");this.boardPoints._debugDraw(a,"green");
this.lineSegments._debugDraw(a,"black")}}})();
(function(){glift.displays.getLineBox=function(b,c){var d=glift.displays.cropbox.OVERFLOW/2,e=b.width()/c.widthMod(),f=b.height()/c.heightMod(),g=f*d,h=e*d,k=f*(c.heightMod()-d),d=e*(c.widthMod()-d),l=b.topLeft().x(),m=b.topLeft().y(),g=glift.displays.bboxFromPts(glift.util.point(h+l,g+m),glift.util.point(d+l,k+m));return new a(g,e,f,c)};var a=function(a,c,d,e){this.bbox=a;this._xSpacing=c;this._ySpacing=d;this.spacing=c;this.extensionBox=e.extBox();this.pointTopLeft=e.cbox().topLeft();this.xPoints=
e.xPoints();this.yPoints=e.yPoints()}})();glift.displays.positionWidget=function(a,b,c,d){for(var e=glift.enums.boardComponents,f={},g=0;g<d.length;g++)f[d[g]]=!0;c=glift.displays.cropbox.getFromRegion(b,c);d={TOP:!0,BOTTOM:!0};return f.hasOwnProperty(e.COMMENT_BOX)?0.45>a.hwRatio()&&d[b]?glift.displays.positionWidgetHorz(a,c,b,f):0.667>a.hwRatio()&&!d[b]?glift.displays.positionWidgetHorz(a,c,b,f):glift.displays.positionWidgetVert(a,c,b,f):glift.displays.positionWidgetVert(a,c,b,f)};
glift.displays.positionWidgetVert=function(a,b,c,d){c=glift.util.point;var e=glift.enums.boardAlignments,f=glift.enums.boardComponents,g={},h=void 0,k=void 0,l=void 0;d.hasOwnProperty(f.COMMENT_BOX)&&d.hasOwnProperty(f.ICONBAR)?(a=a.hSplit([0.7,0.2,0.1]),h=a[0],l=a[1],k=a[2]):d.hasOwnProperty(f.ICONBAR)?(a=a.hSplit([0.9,0.1]),h=a[0],k=a[1]):d.hasOwnProperty(f.COMMENT_BOX)?(a=a.hSplit([0.8,0.2]),h=a[0],l=a[1]):h=a;b=glift.displays.getResizedBox(h,b,e.TOP);g.boardBox=b;l&&(d=l.height(),l=b.width(),
a=b.left(),e=b.bottom(),g.commentBox=glift.displays.bbox(c(a,e),l,d));k&&(k=k.height(),a=b.left(),l=b.width(),b=g.commentBox?g.commentBox.bottom():g.board.bottom(),g.iconBarBox=glift.displays.bbox(c(a,b),l,k));return g};
glift.displays.positionWidgetHorz=function(a,b,c,d){var e=glift.util.point,f=glift.enums.boardAlignments,g=glift.enums.boardComponents;if(!g.hasOwnProperty(g.COMMENT_BOX))throw"The component map must contain a comment box";var h=glift.displays.getResizedBox(a,b,f.RIGHT);c={};var k=0.5*h.width(),l=0.75*h.width(),m=a.width()-h.width(),k=m<k?0.5:m>=k&&m<l?m/h.width():0.75;c.commentBoxPercentage=k;k*=h.width();h=h.width()/(k+h.width());a=a.vSplit([h]);c.leftSide=a[0];b=glift.displays.getResizedBox(a[0],
b,f.RIGHT);a=a[1];c.rightSide=a;e=glift.displays.bboxFromPts(e(a.topLeft().x(),b.topLeft().y()),e(a.botRight().x(),b.botRight().y()));a.width()>0.75*b.width()&&(e=e.vSplit([0.75*b.width()/e.width()])[0]);d.hasOwnProperty(g.ICONBAR)?(d=e.hSplit([0.9]),c.commentBox=d[0],c.iconBarBox=d[1]):c.commentBox=e;c.boardBox=b;return c};
glift.displays.setNotSelectable=function(a){$("#"+a).css({"-webkit-touch-callout":"none","-webkit-user-select":"none","-khtml-user-select":"none","-moz-user-select":"moz-none","-ms-user-select":"none","user-select":"none","-webkit-highlight":"none","-webkit-tap-highlight-color":"rgba(0,0,0,0)",cursor:"default"})};
glift.displays.getResizedBox=function(a,b,c){var d=glift.enums.boardAlignments;c=c||d.CENTER;var e=glift.util,f=glift.displays.getCropDimensions(a.width(),a.height(),b),g=f.width,h=f.height,k=a.width()-g,l=a.height()-h,m=c===d.RIGHT?k:k/2,q=c===d.TOP?0:l/2,n=a.topLeft().x()+m,r=a.topLeft().y()+q;a=glift.displays.bbox(e.point(n,r),g,h);glift.global.debugMode&&(a._debugInfo=function(){return{newDims:f,newWidth:g,newHeight:h,xDiff:k,yDiff:l,xDelta:m,yDelta:q,newLeft:n,newTop:r}});return a};
glift.displays.getCropDimensions=function(a,b,c){var d=b/a;c=c.heightMod()/c.widthMod();var e=b,f=a;d>c?e=a*c:d<c&&(f=b/c);return{height:e,width:f}};glift.displays.board={create:function(a,b,c){return(new glift.displays.board.Display(a,b,c)).draw()}};glift.displays.board.Display=function(a,b,c){this._objectHistory=[];this._environment=a;this._themeName=b;this._theme=c;this._intersections=this._svg=void 0};
glift.displays.board.Display.prototype={intersections:function(){return this._intersections},intersectionPoints:function(){return this._environment.intersections},boardPoints:function(){return this._environment.boardPoints},divId:function(){return this._environment.divId},theme:function(){return this._themeName},boardRegion:function(){return this._environment.boardRegion},width:function(){return this._environment.goBoardBox.width()},height:function(){return this._environment.goBoardBox.height()},
init:function(){void 0===this._svg&&(this.destroy(),this._svg=d3.select("#"+this.divId()).append("svg").attr("width","100%").attr("height","100%"));this._environment.init();return this},draw:function(){this.init();var a=glift.displays.board,b=this._environment,c=b.boardPoints,d=this._theme,e=this._svg,f=this.divId();a.initBlurFilter(f,e);a.boardBase(f,e,b.goBoardBox,d);var b=a.lines(f,e,c,d),g=a.starPoints(f,e,c,d),h=a.shadows(f,e,c,d),k=a.stones(f,e,c,d),l=a.markContainer(f,e,c,d),a=a.buttons(f,
e,c);this._intersections=new glift.displays.board._Intersections(f,e,{lineIds:b,starPointIds:g,stoneShadowIds:h,stoneIds:k,markIds:l,buttons:a},c,d);return this},destroy:function(){this.divId()&&d3.select("#"+this.divId()).selectAll("svg").remove();this._intersections=this._svg=void 0;return this},recreate:function(a){this.destroy();a=glift.displays.processOptions(a);this._environment=glift.displays.environment.get(a);this._themeName=a.theme;this._theme=glift.themes.get(a.theme);return this}};
glift.displays.board.boardBase=function(a,b,c,d){var e=glift.enums.svgElements.BOARD;a=glift.displays.gui.elementId(a,e);d.board.imagefill&&b.selectAll("goBoardRect").data([e]).enter().append("svg:image").attr("x",c.topLeft().x()).attr("y",c.topLeft().y()).attr("width",c.width()).attr("height",c.height()).attr("xlink:href",d.board.imagefill).attr("preserveAspectRatio","none").attr("id",a);b.selectAll("goBoardRect").data([e]).enter().append("rect").attr("x",c.topLeft().x()+"px").attr("y",c.topLeft().y()+
"px").attr("width",c.width()+"px").attr("height",c.height()+"px").attr("height",c.height()+"px").attr("fill",d.board.imagefill?"none":d.board.fill).attr("stroke",d.board.stroke).attr("stroke-width",d.board["stroke-width"]).attr("id",a);return a};
glift.displays.board.buttons=function(a,b,c){var d={},e=glift.enums.svgElements.BUTTON;b.selectAll(e).data(c.data()).enter().append("svg:rect").attr("x",function(a){return a.coordPt.x()-c.radius}).attr("y",function(a){return a.coordPt.y()-c.radius}).attr("width",c.spacing).attr("height",c.spacing).attr("class",e).attr("opacity",0).attr("fill","red").attr("stroke","red").attr("stone_color","EMPTY").attr("id",function(b){var c=glift.displays.gui.elementId(a,e,b.intPt);return d[b.intPt.hash()]=c});return d};
glift.displays.board._Intersections=function(a,b,c,d,e){this.divId=a;this.svg=b;this.theme=e;this.boardPoints=d;this.lineIds=c.lineIds;this.starPointIds=c.starPointIds;this.stoneShadowIds=c.stoneShadowIds;this.stoneIds=c.stoneIds;this.markIds=c.markIds;this.buttons=c.buttons;this.buttonsData=[];for(var f in this.buttons)this.buttonsData.push(glift.util.pointFromString(f))};
glift.displays.board._Intersections.prototype={setStoneColor:function(a,b){var c=a.hash();if(void 0===this.theme.stones[b])throw"Unknown color key ["+b+"]";if(void 0!==this.stoneIds[c]){var d=this.theme.stones[b];this.svg.select("#"+this.stoneIds[c]).attr("fill",d.fill).attr("stroke",d.stroke).attr("stone_color",b).attr("opacity",d.opacity);void 0!==this.stoneShadowIds[c]&&(1===d.opacity?this.svg.select("#"+this.stoneShadowIds[c]).attr("opacity",1):this.svg.select("#"+this.stoneShadowIds[c]).attr("opacity",
0))}return this},addMarkPt:function(a,b,c){glift.displays.board.addMark(this.divId,this.svg,this.boardPoints,this.theme,a,b,c);return this},addGuideLines:function(a){var b=glift.enums.svgElements;this.svg.select("#"+b.GUIDE_LINE).remove();a=this.boardPoints.getCoord(a);var c=this.boardPoints;this.svg.select("."+b.MARK_CONTAINER).append("path").attr("d",glift.displays.board.intersectionLine(a,8*c.radius,c.numIntersections)).attr("stroke-width",3).attr("stroke","blue").attr("id",b.GUIDE_LINE)},clearGuideLines:function(){this.svg.select("#"+
glift.enums.svgElements.GUIDE_LINE).remove()},clearMarks:function(){var a=glift.enums.svgElements;this.svg.selectAll("."+a.STARPOINT).attr("opacity",1);this.svg.selectAll("."+a.BOARD_LINE).attr("opacity",1);this.svg.selectAll("."+a.MARK).remove();this.svg.selectAll("."+a.GUIDE_LINE).remove();return this},clearStones:function(){var a=glift.enums.svgElements;this.svg.selectAll("."+a.STONE).attr("opacity",0).attr("stone_color","EMPTY");this.svg.selectAll("."+a.STONE_SHADOW).attr("opacity",0)},clearAll:function(){this.clearMarks();
this.clearStones()},setEvent:function(a,b){this.svg.selectAll("rect."+glift.enums.svgElements.BUTTON).data(this.buttonsData).on(a,function(a){b(a)})}};
glift.displays.board.lines=function(a,b,c,d){var e={},f=glift.enums.svgElements.BOARD_LINE;b.selectAll(f).data(c.data()).enter().append("path").attr("d",function(a){return glift.displays.board.intersectionLine(a,c.radius,c.numIntersections)}).attr("stroke",d.lines.stroke).attr("stroke-width",d.lines["stroke-width"]).attr("class",f).attr("stroke-linecap","round").attr("id",function(b){var c=glift.displays.gui.elementId(a,f,b.intPt);return e[b.intPt.hash()]=c});return e};
glift.displays.board.intersectionLine=function(a,b,c){var d=c-1;c=a.coordPt;var e=a.intPt;a=glift.displays.board.svgutil;var f=0===e.y()?c.y():c.y()-b,g=e.y()===d?c.y():c.y()+b,h=0===e.x()?c.x():c.x()-b;b=e.x()===d?c.x():c.x()+b;return a.svgMove(c.x(),f)+" "+a.svgLineAbs(c.x(),g)+" "+a.svgMove(h,c.y())+" "+a.svgLineAbs(b,c.y())};glift.displays.board.markContainer=function(a,b,c,d){a=glift.enums.svgElements.MARK_CONTAINER;b.selectAll(a).data([1]).enter().append("g").attr("class",a);return{}};
glift.displays.board.addMark=function(a,b,c,d,e,f,g){var h=glift.displays.board.svgutil,k=glift.enums.svgElements,l=k.MARK,m=k.STONE,q=k.STARPOINT,n=k.BOARD_LINE,k=k.MARK_CONTAINER,r=glift.enums.marks,p=c.getCoord(e).coordPt,s=b.select("#"+glift.displays.gui.elementId(a,m,e)).attr("stone_color"),m=d.stones[s].marks;if("EMPTY"===s&&(f===r.LABEL||f===r.VARIATION_MARKER||f===r.CORRECT_VARIATION))b.select("#"+glift.displays.gui.elementId(a,q,e)).attr("opacity",0),b.select("#"+glift.displays.gui.elementId(a,
n,e)).attr("opacity",0);a=c.radius/8;f===r.LABEL||f==r.VARIATION_MARKER||f==r.CORRECT_VARIATION?(f===r.VARIATION_MARKER?m=m.VARIATION_MARKER:f===r.CORRECT_VARIATION&&(m=m.CORRECT_VARIATION),b.select("."+k).append("text").text(g).attr("fill",m.fill).attr("stroke",m.stroke).attr("class",l).attr("text-anchor","middle").attr("dy",".33em").attr("x",p.x()).attr("y",p.y()).attr("font-family",d.stones.marks["font-family"]).attr("font-size",0.7*c.spacing)):f===r.SQUARE?(c=c.radius/1.41421356237,h=c-a,b.select("."+
k).append("rect").attr("x",p.x()-h).attr("y",p.y()-h).attr("width",2*h).attr("height",2*h).attr("fill","none").attr("stroke-width",2).attr("class",l).attr("stroke",m.stroke)):f===r.XMARK?(c=c.radius/1.41421356237,g=c-a,c=p.translate(-1*g,-1*g),d=p.translate(g,-1*g),f=p.translate(-1*g,g),g=p.translate(g,g),b.select("."+k).append("path").attr("d",h.svgMovePt(p)+" "+h.svgLineAbsPt(c)+" "+h.svgMovePt(p)+" "+h.svgLineAbsPt(d)+" "+h.svgMovePt(p)+" "+h.svgLineAbsPt(f)+" "+h.svgMovePt(p)+" "+h.svgLineAbsPt(g)).attr("stroke-width",
2).attr("class",l).attr("stroke",m.stroke)):f===r.CIRCLE?b.select("."+k).append("circle").attr("cx",p.x()).attr("cy",p.y()).attr("r",c.radius/2).attr("fill","none").attr("stroke-width",2).attr("class",l).attr("stroke",m.stroke):f===r.STONE_MARKER?b.select("."+k).append("circle").attr("cx",p.x()).attr("cy",p.y()).attr("r",c.radius/3).attr("class",l).attr("opacity",m.STONE_MARKER.opacity).attr("fill",m.STONE_MARKER.fill):f===r.TRIANGLE&&(f=c.radius-c.radius/5,c=p.translate(0.866025403785*f,0.5*f),d=
p.translate(-0.866025403785*f,0.5*f),p=p.translate(0,-1*f),b.select("."+k).append("path").attr("fill","none").attr("d",h.svgMovePt(p)+" "+h.svgLineAbsPt(d)+" "+h.svgLineAbsPt(c)+" "+h.svgLineAbsPt(p)).attr("stroke-width",2).attr("class",l).attr("stroke",m.stroke));return this};
glift.displays.board.starPoints=function(a,b,c,d){var e=d.starPoints.sizeFraction*c.spacing,f=c.starPoints(),g=glift.enums.svgElements.STARPOINT,h={};b.selectAll(g).data(f).enter().append("circle").attr("cx",function(a){return c.getCoord(a).coordPt.x()}).attr("cy",function(a){return c.getCoord(a).coordPt.y()}).attr("r",e).attr("class",g).attr("fill",d.starPoints.fill).attr("id",function(b){var c=glift.displays.gui.elementId(a,g,b);return h[b.hash()]=c});return h};
glift.displays.board.stones=function(a,b,c,d){var e=glift.enums.svgElements.STONE,f={};b.selectAll(e).data(c.data()).enter().append("circle").attr("cx",function(a){return a.coordPt.x()}).attr("cy",function(a){return a.coordPt.y()}).attr("r",c.radius-0.5).attr("opacity",0).attr("class",glift.enums.svgElements.STONE).attr("stone_color","EMPTY").attr("fill","blue").attr("id",function(b){b=b.intPt;var c=glift.displays.gui.elementId(a,e,b);return f[b.hash()]=c});return f};
glift.displays.board.shadows=function(a,b,c,d){if(void 0===d.stones.shadows)return{};var e=glift.enums.svgElements.STONE_SHADOW,f={};b.selectAll(e).data(c.data()).enter().append("circle").attr("cx",function(a){return a.coordPt.x()+c.radius/7}).attr("cy",function(a){return a.coordPt.y()+c.radius/7}).attr("r",c.radius-0.4).attr("opacity",0).attr("class",e).attr("fill",d.stones.shadows.fill).attr("id",function(b){b=b.intPt;var c=glift.displays.gui.elementId(a,e,b);return f[b.hash()]=c});return f};
glift.displays.board.initBlurFilter=function(a,b){b.append("svg:defs").append("svg:filter").attr("id",a+"_svg_blur").append("svg:feGaussianBlur").attr("stdDeviation",2)};
glift.displays.board.svgutil={svgMove:function(a,b){return"M"+a+" "+b},svgMovePt:function(a){return glift.displays.board.svgutil.svgMove(a.x(),a.y())},svgLineRel:function(a,b){return"l"+a+" "+b},svgLineRelPt:function(a){return glift.displays.board.svgutil.svgLineRel(a.x(),a.y())},svgLineAbs:function(a,b){return"L"+a+" "+b},svgLineAbsPt:function(a){return glift.displays.board.svgutil.svgLineAbs(a.x(),a.y())}};
glift.displays.gui={elementId:function(a,b,c){a=a+"_"+b;return void 0!==c?void 0!==c.x?a+"_"+c.x()+"_"+c.y():a+"_"+c.toString():a}};
glift.displays.gui.rowCenter=function(a,b,c,d,e,f){var g=a.width()-2*d,h=a.height()-2*c,k=[],l=[],m=0;0>=f&&(f=1E7);for(var q=0;q<b.length;q++){var n=b[q],r=h>g?g/n.width():h/n.height(),p={scale:r},n=n.scale(r);k.push(p);l.push(n);m+=n.width()+e}m-=e;for(q=[];g<m;)p=l.pop(),n=k.pop(),m-=p.width()+e,q.push(n);q=g-m;n=e=p=q/(k.length+1);p>f&&(e=f,n=(q-e*(k.length-1))/2);d=a.left()+d+n;a=a.top()+c;c=[];for(q=0;q<l.length;q++)n=l[q],p=k[q],f=a-n.top(),g=d-n.left(),p.xMove=g,p.yMove=f,c.push(n.translate(g,
f)),d+=n.width()+e;return{transforms:k,bboxes:c}};glift.displays.gui.centerWithin=function(a,b,c,d){var e=a.width()-2*d,f=a.height()-2*c,g=1,g=f/e>b.height()/b.width()?e/b.width():f/b.width();b=b.scale(g);d=a.left()+d;b.width()<e&&(d+=(e-b.width())/2);a=a.top()+c;b.height()<f&&(a+=(f-b.height())/2);f={xMove:d-b.left(),yMove:a-b.top(),scale:g};b=b.translate(f.xMove,f.yMove);return{transform:f,bbox:b}};
(function(){glift.displays.gui.commentBox=function(b,c){return(new a(b,c)).draw()};var a=function(a,c){this.divId=a;this.themeName=c;this.theme=glift.themes.get(c);this.commentBoxObj=void 0};a.prototype={draw:function(){this.commentBoxObj=$("#"+this.divId);var a=$("#"+this.divId).height(),a=14>0.13*a?14:0.13*a;this.commentBoxObj.css({background:"#CCCCFF",border:"1px solid",margin:"auto","font-family":"Baskerville",overflow:"auto","font-size":16<a?16:a,"-webkit-box-sizing":"border-box","-moz-box-sizing":"border-box",
"box-sizing":"border-box",padding:10});return this},setText:function(a){this.commentBoxObj.html("<p>"+a.replace(/\n/g,"<br>")+"</p>")},clearText:function(){this.commentBoxObj.html("")},destroy:function(){this.commentBoxObj.empty()}}})();
(function(){glift.displays.gui.iconBar=function(b){var c=b.divId,d=b.icons||[],e=b.vertMargin||0,f=b.horzMargin||0;b=b.theme||"DEFAULT";if(void 0===c)throw"Must define an options 'divId' as an option";for(var g=0;g<d.length;g++)if(void 0===glift.displays.gui.icons[d[g]])throw"Icon string undefined in glift.displays.gui.icons ["+d[g]+"]";return(new a(c,b,d,e,f)).draw()};var a=function(a,c,d,e,f){this.divId=a;this.themeName=c;this.theme=glift.themes.get(c);this.iconNames=d;this.vertMargin=e;this.horzMargin=
f;this.newIconBboxes={};this.svg=void 0;this.tempIconIds=[]};a.prototype={draw:function(){this.destroy();var a=glift.displays.bboxFromDiv(this.divId),c=d3.select("#"+this.divId).append("svg").attr("width","100%").attr("height","100%"),d=glift.displays.gui,e=[],f=[],g=[],h=glift.util.point;this.svg=c;for(var k=0;k<this.iconNames.length;k++){var l=d.icons[this.iconNames[k]];f.push(l.string);e.push(glift.displays.bboxFromPts(h(l.bbox.x,l.bbox.y),h(l.bbox.x2,l.bbox.y2)));g.push(k)}for(var m=glift.displays.gui.rowCenter(a,
e,this.vertMargin,this.horzMargin,0,0),k=0;k<m.bboxes.length;k++)this.newIconBboxes[this.iconNames[k]]=m.bboxes[k];var q=this;c.selectAll("icons").data(g).enter().append("path").attr("d",function(a){return f[a]}).attr("fill",this.theme.icons.DEFAULT.fill).attr("id",function(a){return q.iconId(q.iconNames[a])}).attr("transform",function(a){return glift.displays.gui.scaleAndMoveString(m.bboxes[a],m.transforms[a])});var n=m.bboxes;c.selectAll("buttons").data(g).enter().append("rect").attr("x",function(a){return n[a].topLeft().x()}).attr("y",
function(a){return n[a].topLeft().y()}).attr("width",function(a){return n[a].width()}).attr("height",function(a){return n[a].height()}).attr("fill","blue").attr("opacity",0).attr("_icon",function(a){return q.iconNames[a]}).attr("id",function(a){return q.buttonId(q.iconNames[a])});return this},addTempIcon:function(a,c,d){var e=glift.displays.gui.icons[c],f=glift.displays.bboxFromPts(glift.util.point(e.bbox.x,e.bbox.y),glift.util.point(e.bbox.x2,e.bbox.y2)),g=this.iconId(c);a=glift.displays.gui.centerWithin(a,
f,2,2);this.svg.append("path").attr("d",e.string).attr("fill",d).attr("id",this.iconId(c)).attr("class","tempIcon").attr("transform",glift.displays.gui.scaleAndMoveString(a.bbox,a.transform));this.tempIconIds.push(g);return this},addTempText:function(a,c,d){var e=0.54*a.width();this.svg.append("text").text(c).attr("fill",d).attr("stroke",d).attr("class","tempIcon").attr("font-family","sans-serif").attr("font-size",e+"px").attr("x",a.center().x()).attr("y",a.center().y()).attr("dy",".33em").attr("style",
"text-anchor: middle; vertical-align: middle;").attr("lengthAdjust","spacing");return this},destroyTempIcons:function(){this.svg.selectAll(".tempIcon").remove();this.tempIconIds=[];return this},iconId:function(a){return glift.displays.gui.elementId(this.divId,glift.enums.svgElements.ICON,a)},buttonId:function(a){return glift.displays.gui.elementId(this.divId,glift.enums.svgElements.BUTTON,a)},setEvent:function(a,c,d){var e=this;d3.select("#"+this.buttonId(c)).on(a,function(){d(e.getIcon(c))});return this},
setHover:function(a,c,d){this.setEvent("mouseover",a,c);this.setEvent("mouseout",a,d)},hasIcon:function(a){return void 0===this.newIconBboxes[a]},getIcon:function(a){return{name:a,iconId:this.iconId(a),newBbox:this.newIconBboxes[a]}},forEachIcon:function(a){for(var c=0;c<this.iconNames.length;c++)a(this.getIcon(this.iconNames[c]))},redraw:function(){this.destroy();this.draw()},destroy:function(){this.divId&&d3.select("#"+this.divId).selectAll("svg").remove();return this}}})();
glift.displays.gui.icons={cross:{string:"M24.778,21.419 19.276,15.917 24.777,10.415 21.949,7.585 16.447,13.087 10.945,7.585 8.117,10.415 13.618,15.917 8.116,21.419 10.946,24.248 16.447,18.746 21.948,24.248z",bbox:{x:8.116,y:7.585,x2:24.778,y2:24.248,width:16.662,height:16.663}},check:{string:"M2.379,14.729 5.208,11.899 12.958,19.648 25.877,6.733 28.707,9.561 12.958,25.308z",bbox:{x:2.379,y:6.733,x2:28.707,y2:25.308,width:26.328,height:18.575}},refresh:{string:"M24.083,15.5c-0.009,4.739-3.844,8.574-8.583,8.583c-4.741-0.009-8.577-3.844-8.585-8.583c0.008-4.741,3.844-8.577,8.585-8.585c1.913,0,3.665,0.629,5.09,1.686l-1.782,1.783l8.429,2.256l-2.26-8.427l-1.89,1.89c-2.072-1.677-4.717-2.688-7.587-2.688C8.826,3.418,3.418,8.826,3.416,15.5C3.418,22.175,8.826,27.583,15.5,27.583S27.583,22.175,27.583,15.5H24.083z",
bbox:{x:3.416,y:3.415,x2:27.583,y2:27.583,width:24.167,height:24.168}},undo:{string:"M12.981,9.073V6.817l-12.106,6.99l12.106,6.99v-2.422c3.285-0.002,9.052,0.28,9.052,2.269c0,2.78-6.023,4.263-6.023,4.263v2.132c0,0,13.53,0.463,13.53-9.823C29.54,9.134,17.952,8.831,12.981,9.073z",bbox:{x:0.875,y:6.817,x2:29.54,y2:27.042158,width:28.665,height:20.225158}},"chevron-right":{string:"M10.129,22.186 16.316,15.999 10.129,9.812 13.665,6.276 23.389,15.999 13.665,25.725z",bbox:{x:10.129,y:6.276,x2:23.389,y2:25.725,
width:13.26,height:19.449}},"chevron-left":{string:"M21.871,9.814 15.684,16.001 21.871,22.188 18.335,25.725 8.612,16.001 18.335,6.276z",bbox:{x:8.612,y:6.276,x2:21.871,y2:25.725,width:13.259,height:19.449}},"small-gear":{string:"M31.229,17.736c0.064-0.571,0.104-1.148,0.104-1.736s-0.04-1.166-0.104-1.737l-4.377-1.557c-0.218-0.716-0.504-1.401-0.851-2.05l1.993-4.192c-0.725-0.91-1.549-1.734-2.458-2.459l-4.193,1.994c-0.647-0.347-1.334-0.632-2.049-0.849l-1.558-4.378C17.165,0.708,16.588,0.667,16,0.667s-1.166,0.041-1.737,0.105L12.707,5.15c-0.716,0.217-1.401,0.502-2.05,0.849L6.464,4.005C5.554,4.73,4.73,5.554,4.005,6.464l1.994,4.192c-0.347,0.648-0.632,1.334-0.849,2.05l-4.378,1.557C0.708,14.834,0.667,15.412,0.667,16s0.041,1.165,0.105,1.736l4.378,1.558c0.217,0.715,0.502,1.401,0.849,2.049l-1.994,4.193c0.725,0.909,1.549,1.733,2.459,2.458l4.192-1.993c0.648,0.347,1.334,0.633,2.05,0.851l1.557,4.377c0.571,0.064,1.148,0.104,1.737,0.104c0.588,0,1.165-0.04,1.736-0.104l1.558-4.377c0.715-0.218,1.399-0.504,2.049-0.851l4.193,1.993c0.909-0.725,1.733-1.549,2.458-2.458l-1.993-4.193c0.347-0.647,0.633-1.334,0.851-2.049L31.229,17.736zM16,20.871c-2.69,0-4.872-2.182-4.872-4.871c0-2.69,2.182-4.872,4.872-4.872c2.689,0,4.871,2.182,4.871,4.872C20.871,18.689,18.689,20.871,16,20.871z",
bbox:{x:0.667,y:0.667,x2:31.333,y2:31.333,width:30.666,height:30.666}},"question-bubble":{string:"M16,4.938c-7.732,0-14,4.701-14,10.5c0,1.981,0.741,3.833,2.016,5.414L2,25.272l5.613-1.44c2.339,1.316,5.237,2.106,8.387,2.106c7.732,0,14-4.701,14-10.5S23.732,4.938,16,4.938zM16.982,21.375h-1.969v-1.889h1.969V21.375zM16.982,17.469v0.625h-1.969v-0.769c0-2.321,2.641-2.689,2.641-4.337c0-0.752-0.672-1.329-1.553-1.329c-0.912,0-1.713,0.672-1.713,0.672l-1.12-1.393c0,0,1.104-1.153,3.009-1.153c1.81,0,3.49,1.121,3.49,3.009C19.768,15.437,16.982,15.741,16.982,17.469z",
bbox:{x:2,y:4.938,x2:30,y2:25.938,width:28,height:21}},roadmap:{string:"M23.188,3.735c0-0.975-0.789-1.766-1.766-1.766s-1.766,0.791-1.766,1.766s1.766,4.267,1.766,4.267S23.188,4.71,23.188,3.735zM20.578,3.734c0-0.466,0.378-0.843,0.844-0.843c0.467,0,0.844,0.377,0.844,0.844c0,0.466-0.377,0.843-0.844,0.843C20.956,4.578,20.578,4.201,20.578,3.734zM25.281,18.496c-0.562,0-1.098,0.046-1.592,0.122L11.1,13.976c0.199-0.181,0.312-0.38,0.312-0.59c0-0.108-0.033-0.213-0.088-0.315l8.41-2.239c0.459,0.137,1.023,0.221,1.646,0.221c1.521,0,2.75-0.485,2.75-1.083c0-0.599-1.229-1.083-2.75-1.083s-2.75,0.485-2.75,1.083c0,0.069,0.021,0.137,0.054,0.202L9.896,12.2c-0.633-0.188-1.411-0.303-2.265-0.303c-2.088,0-3.781,0.667-3.781,1.49c0,0.823,1.693,1.489,3.781,1.489c0.573,0,1.11-0.054,1.597-0.144l11.99,4.866c-0.19,0.192-0.306,0.401-0.306,0.623c0,0.188,0.096,0.363,0.236,0.532L8.695,25.415c-0.158-0.005-0.316-0.011-0.477-0.011c-3.241,0-5.87,1.037-5.87,2.312c0,1.276,2.629,2.312,5.87,2.312c3.241,0,5.87-1.034,5.87-2.312c0-0.22-0.083-0.432-0.229-0.633l10.265-5.214c0.37,0.04,0.753,0.066,1.155,0.066c2.414,0,4.371-0.771,4.371-1.723C29.65,19.268,27.693,18.496,25.281,18.496z",
bbox:{x:2.348,y:1.969,x2:29.65,y2:30.028,width:27.302,height:28.059}},play:{string:"m 58.250001,41.61219 0,40 34.69375,-20.03045 z",bbox:{x:58.250001,y:41.61219,x2:92.94375099999999,y2:81.61219,width:34.693749999999994,height:40}},unplay:{string:"m 74.987245,22.583592 0,39.978487 L 40,42.362183 z",bbox:{x:40,y:22.583592,x2:74.987245,y2:62.562079,width:34.987245,height:39.978487}},end:{string:"M21.167,5.5,21.167,13.681,6.684,5.318,6.684,25.682,21.167,17.318,21.167,25.5,25.5,25.5,25.5,5.5z",bbox:{x:6.684,
y:5.318,x2:25.5,y2:25.682,width:18.816,height:20.364}},start:{string:"M24.316,5.318,9.833,13.682,9.833,5.5,5.5,5.5,5.5,25.5,9.833,25.5,9.833,17.318,24.316,25.682z",bbox:{x:5.5,y:5.318,x2:24.316,y2:25.682,width:18.816,height:20.364}},arrowup:{string:"M23.963,20.834L17.5,9.64c-0.825-1.429-2.175-1.429-3,0L8.037,20.834c-0.825,1.429-0.15,2.598,1.5,2.598h12.926C24.113,23.432,24.788,22.263,23.963,20.834z",bbox:{x:7.684895,y:8.56825,x2:24.315105,y2:23.432,width:16.630209,height:14.86375}},arrowright:{string:"M11.166,23.963L22.359,17.5c1.43-0.824,1.43-2.175,0-3L11.166,8.037c-1.429-0.826-2.598-0.15-2.598,1.5v12.926C8.568,24.113,9.737,24.789,11.166,23.963z",
bbox:{x:8.568,y:7.684457,x2:23.4315,y2:24.315543,width:14.8635,height:16.631086}},arrowleft:{string:"M20.834,8.037L9.641,14.5c-1.43,0.824-1.43,2.175,0,3l11.193,6.463c1.429,0.826,2.598,0.15,2.598-1.5V9.537C23.432,7.887,22.263,7.211,20.834,8.037z",bbox:{x:8.5685,y:7.684457,x2:23.432,y2:24.315543,width:14.8635,height:16.631086}},detour:{string:"M29.342,15.5l-7.556-4.363v2.614H18.75c-1.441-0.004-2.423,1.002-2.875,1.784c-0.735,1.222-1.056,2.561-1.441,3.522c-0.135,0.361-0.278,0.655-0.376,0.817c-1.626,0-0.998,0-2.768,0c-0.213-0.398-0.571-1.557-0.923-2.692c-0.237-0.676-0.5-1.381-1.013-2.071C8.878,14.43,7.89,13.726,6.75,13.75H2.812v3.499c0,0,0.358,0,1.031,0h2.741c0.008,0.013,0.018,0.028,0.029,0.046c0.291,0.401,0.634,1.663,1.031,2.888c0.218,0.623,0.455,1.262,0.92,1.897c0.417,0.614,1.319,1.293,2.383,1.293H11c2.25,0,1.249,0,3.374,0c0.696,0.01,1.371-0.286,1.809-0.657c1.439-1.338,1.608-2.886,2.13-4.127c0.218-0.608,0.453-1.115,0.605-1.314c0.006-0.01,0.012-0.018,0.018-0.025h2.85v2.614L29.342,15.5zM10.173,14.539c0.568,0.76,0.874,1.559,1.137,2.311c0.04,0.128,0.082,0.264,0.125,0.399h2.58c0.246-0.697,0.553-1.479,1.005-2.228c0.252-0.438,0.621-0.887,1.08-1.272H9.43C9.735,14.003,9.99,14.277,10.173,14.539z",
bbox:{x:2.812,y:11.137,x2:29.342,y2:23.37325,width:26.53,height:12.23625}},checkbox:{string:"M26,27.5H6c-0.829,0-1.5-0.672-1.5-1.5V6c0-0.829,0.671-1.5,1.5-1.5h20c0.828,0,1.5,0.671,1.5,1.5v20C27.5,26.828,26.828,27.5,26,27.5zM7.5,24.5h17v-17h-17V24.5z",bbox:{x:4.5,y:4.5,x2:27.5,y2:27.5,width:23,height:23}},edit:{string:"M27.87,7.863L23.024,4.82l-7.889,12.566l4.842,3.04L27.87,7.863zM14.395,21.25l-0.107,2.855l2.527-1.337l2.349-1.24l-4.672-2.936L14.395,21.25zM29.163,3.239l-2.532-1.591c-0.638-0.401-1.479-0.208-1.882,0.43l-0.998,1.588l4.842,3.042l0.999-1.586C29.992,4.481,29.802,3.639,29.163,3.239zM25.198,27.062c0,0.275-0.225,0.5-0.5,0.5h-19c-0.276,0-0.5-0.225-0.5-0.5v-19c0-0.276,0.224-0.5,0.5-0.5h13.244l1.884-3H5.698c-1.93,0-3.5,1.57-3.5,3.5v19c0,1.93,1.57,3.5,3.5,3.5h19c1.93,0,3.5-1.57,3.5-3.5V11.097l-3,4.776V27.062z",
bbox:{x:2.198,y:1.4388,x2:29.80125,y2:30.562,width:27.60325,height:29.12316}},twostones:{string:"m 42.894737,29.335869 c 0,6.540213 -5.301891,11.842106 -11.842105,11.842106 -6.540214,0 -11.842105,-5.301893 -11.842105,-11.842106 0,-6.540214 5.301891,-11.842105 11.842105,-11.842105 6.540214,0 11.842105,5.301891 11.842105,11.842105 z M 31.052632,16.309553 c -7.194236,0 -13.026316,5.83208 -13.026316,13.026316 0,7.194233 5.83208,13.026314 13.026316,13.026314 3.733917,0 7.098575,-1.575815 9.473684,-4.092928 2.375029,2.516206 5.740532,4.092928 9.473684,4.092928 7.194235,0 13.026316,-5.832081 13.026316,-13.026314 0,-7.194236 -5.832081,-13.026316 -13.026316,-13.026316 -3.733152,0 -7.098655,1.56932 -9.473684,4.085526 -2.374906,-2.51483 -5.741698,-4.085526 -9.473684,-4.085526 z",
bbox:{x:18.026316,y:16.309553,x2:63.026316,y2:42.362183,width:45,height:26.05263}},ff:{string:"M25.5,15.5,15.2,9.552,15.2,15.153,5.5,9.552,5.5,21.447,15.2,15.847,15.2,21.447z",bbox:{}},rw:{string:"M5.5,15.499,15.8,21.447,15.8,15.846,25.5,21.447,25.5,9.552,15.8,15.152,15.8,9.552z",bbox:{}}};glift.displays.gui.scaleAndMoveString=function(a,b){return"translate("+b.xMove+","+b.yMove+") scale("+b.scale+")"};glift.displays.gui.DivSplit=function(a,b,c){this.id=a;this.start=b;this.length=c};
glift.displays.gui.splitDiv=function(a,b,c){var d=glift.displays.bboxFromDiv(a),e=0;c?"vertical"!==c&&"horizontal"!==c&&(c="horizontal"):c="horizontal";for(var f=0;f<b.length;f++)e+=b[f];if(1<e||0>e)throw"Percents must sum to a number be between 0 and 1.Was "+e;b.push(1-e);for(var e=[],g="horizontal"===c?d.top():d.left(),d="horizontal"===c?d.height():d.width(),f=0;f<b.length;f++)e.push(new glift.displays.gui.DivSplit("glift_internal_div_"+glift.util.idGenerator.next(),g,d*b[f])),g+=d*b[f];for(f=0;f<
e.length;f++)$("#"+a).append('<div id="'+e[f].id+'"></div>'),b={width:"horizontal"===c?"100%":e[f].length,height:"horizontal"===c?e[f].length:"100%",position:"absolute"},b["horizontal"===c?"top":"left"]=e[f].start,$("#"+e[f].id).css(b);return e};glift.rules={};
(function(){glift.rules.goban={getInstance:function(b){return new a(b||19)},getFromMoveTree:function(b,c){var f=new a(b.getIntersections()),g=b.getTreeFromRoot();c=c||[];var h=[];f.loadStonesFromMovetree(g);for(var k=0;k<c.length;k++)g.moveDown(c[k]),h.push(f.loadStonesFromMovetree(g));return{goban:f,captures:h}}};var a=function(a){if(0>=a)throw"Intersections must be greater than 0";this.ints=a;for(var b=[],c=0;c<a;c++){for(var g=[],h=0;h<a;h++)g[h]=glift.enums.states.EMPTY;b[c]=g}this.stones=b};
a.prototype={intersections:function(){return this.ints},getStone:function(a){return this.stones[a.y()][a.x()]},getAllPlacedStones:function(){for(var a=[],b=0;b<this.stones.length;b++)for(var c=this.stones[b],g=0;g<c.length;g++){var h=glift.util.point(g,b),k=this.getStone(h);(k===glift.enums.states.BLACK||k===glift.enums.states.WHITE)&&a.push({point:h,color:k})}return a},placeable:function(a,b){return this.inBounds(a)&&this.getStone(a)===glift.enums.states.EMPTY},outBounds:function(a){return glift.util.outBounds(a.x(),
this.ints)||glift.util.outBounds(a.y(),this.ints)},inBounds:function(a){return glift.util.inBounds(a.x(),this.ints)&&glift.util.inBounds(a.y(),this.ints)},clearStone:function(a){this._setColor(a,glift.enums.states.EMPTY)},clearSome:function(a){for(var b=0;b<a.length;b++)this.clearStone(a[b])},_setColor:function(a,b){this.stones[a.y()][a.x()]=b},addStone:function(a,e){if(!glift.util.colors.isLegalColor(e))throw"Unknown color: "+e;if(this.outBounds(a)||!this.placeable(a))return new c(!1);this._setColor(a,
e);var f=new b,g=glift.util.colors.oppositeColor(e);this._getCaptures(f,glift.util.point(a.x()+1,a.y()),g);this._getCaptures(f,glift.util.point(a.x()-1,a.y()),g);this._getCaptures(f,glift.util.point(a.x(),a.y()-1),g);this._getCaptures(f,glift.util.point(a.x(),a.y()+1),g);if(0>=f.numCaptures&&(this._getCaptures(f,a,e),0<f.numCaptures))return this.clearStone(a),new c(!1);f=f.getCaptures();this.clearSome(f);return new c(!0,f)},_getCaptures:function(a,b,c){this._findConnected(a,b,c);0>=a.liberties&&a.consideringToCaptures();
a.clearExceptCaptures()},_findConnected:function(a,b,c){var g=glift.util;if(!(void 0!==a.seen[b.hash()]||this.outBounds(b))){a.seen[b.hash()]=!0;var h=this.getStone(b);if(h===glift.enums.states.EMPTY)a.liberties++;else if(h!==g.colors.oppositeColor(c))if(h===c)a.considering.push(b),this._findConnected(a,g.point(b.x()+1,b.y()),c),this._findConnected(a,g.point(b.x()-1,b.y()),c),this._findConnected(a,g.point(b.x(),b.y()+1),c),this._findConnected(a,g.point(b.x(),b.y()-1),c);else throw"Unknown color error: "+
h;}},loadStonesFromMovetree:function(a){for(var b=[glift.enums.states.BLACK,glift.enums.states.WHITE],c={BLACK:[],WHITE:[]},g=0;g<b.length;g++)for(var h=b[g],k=a.properties().getPlacementsAsPoints(h),l=0;l<k.length;l++)this._loadStone({point:k[l],color:h},c);this._loadStone(a.properties().getMove(),c);return c},_loadStone:function(a,b){if(a!==glift.util.none&&void 0!==a.point){var c=this.addStone(a.point,a.color);if(c.successful)for(var g=glift.util.colors.oppositeColor(a.color),h=0;h<c.captures.length;h++)b[g].push(c.captures[h])}},
unloadStones:function(a,b){for(var c in a)for(var g=0;g<a[c].length;g++)this.clearStone(a[c][g]);for(c in b)for(g=0;g<b[c].length;g++)this.addStone(b[c][g],c)},_debug:function(){glift.util.logz(this.stones)}};var b=function(){this.toCapture={};this.numCaptures=0;this.considering=[];this.seen={};this.liberties=0};b.prototype={clearExceptCaptures:function(){this.considering=[];this.seen={};this.liberties=0},consideringToCaptures:function(){for(var a=0;a<this.considering.length;a++){var b=this.considering[a];
void 0===this.toCapture[b.hash()]&&(this.toCapture[b.hash()]=!0,this.numCaptures++)}},addLiberties:function(a){this.liberties+=a},addSeen:function(a){this.seen[a.hash()]=!0},getCaptures:function(){var a=[],b;for(b in this.toCapture)a.push(glift.util.pointFromHash(b));return a}};var c=function(a,b){this.captures=(this.successful=a)?b:[]}})();
(function(){glift.rules.intersections={propertiesToMarks:{CR:glift.enums.marks.CIRCLE,LB:glift.enums.marks.LABEL,MA:glift.enums.marks.XMARK,SQ:glift.enums.marks.SQUARE,TR:glift.enums.marks.TRIANGLE},basePropertyData:function(a,b){var c={stones:{WHITE:[],BLACK:[],EMPTY:[]},marks:{},comment:glift.util.none,lastMove:glift.util.none,nextMoves:[],correctNextMoves:[],captures:[],displayDataType:glift.enums.displayDataTypes.PARTIAL};c.comment=a.properties().getComment();c.lastMove=a.getLastMove();c.marks=
glift.rules.intersections.getCurrentMarks(a);c.nextMoves=a.nextMoves();c.correctNextMoves=void 0!==b?glift.rules.problems.correctNextMoves(a,b):[];return c},getFullBoardData:function(a,b,c){a=glift.rules.intersections.basePropertyData(a,c);a.displayDataType=glift.enums.displayDataTypes.FULL;b=b.getAllPlacedStones();for(c=0;c<b.length;c++){var d=b[c];a.stones[d.color].push(d.point)}return a},nextBoardData:function(a,b,c){c=glift.rules.intersections.basePropertyData(a,c);c.stones=a.properties().getAllStones();
c.stones.EMPTY=[];for(var d in b)for(a=0;a<b[d].length;a++)c.stones.EMPTY.push(b[d][a]);return c},previousBoardData:function(a,b,c,d){a=glift.rules.intersections.basePropertyData(a,d);a.stones=c;a.stones.EMPTY=[];for(var e in b)for(c=0;c<b[e].length;c++)a.stones.EMPTY.push(b[e][c]);return a},getCurrentMarks:function(a){var b={},c;for(c in glift.rules.intersections.propertiesToMarks){var d=glift.rules.intersections.propertiesToMarks[c];if(a.properties().contains(c)){for(var e=[],f=a.properties().getAllValues(c),
g=0;g<f.length;g++)c===glift.sgf.allProperties.LB?e.push(glift.sgf.convertFromLabelData(f[g])):e.push(glift.util.pointFromSgfCoord(f[g]));b[d]=e}}return b}}})();
(function(){glift.rules.movenode=function(b,d){return new a(b,d)};var a=function(a,b){this._properties=a||glift.rules.properties();this.children=b||[];this._nodeId={nodeNum:0,varNum:0}};a.prototype={properties:function(){return this._properties},_setNodeId:function(a,b){this._nodeId={nodeNum:a,varNum:b};return this},getNodeNum:function(){return this._nodeId.nodeNum},getVarNum:function(){return this._nodeId.varNum},numChildren:function(){return this.children.length},addChild:function(){this.children.push(glift.rules.movenode()._setNodeId(this.getNodeNum()+
1,this.numChildren()));return this},getChild:function(a){return void 0===a?this.children[0]:this.children[a]},renumber:function(){b(this,this._nodeId.nodeNum,this._nodeId.varNum);return this}};var b=function(a,d,e){a._setNodeId(d,e);for(e=0;e<a.children.length;e++)b(a.children[e],d+1,e);return a}})();
(function(){var a=glift.util,b=glift.enums;glift.rules.movetree={getInstance:function(a){var b=new c(glift.rules.movenode());void 0!==a&&b.setIntersections(a);return b},getFromSgf:function(a,b){b=b||[];if(void 0===a||""===a)return glift.rules.movetree.getInstance(19);for(var c=glift.sgf.parse(a),g=0;g<b.length;g++)c.moveDown(b[g]);return c},getFromNode:function(a){return new c(a)},searchMoveTreeDFS:function(a,b){b(a);for(var c=0;c<a.node().numChildren();c++)glift.rules.movetree.searchMoveTreeDFS(a.moveDown(c),
b);a.moveUp()}};var c=function(a){this._nodeHistory=[];this._nodeHistory.push(a)};c.prototype={getTreeFromRoot:function(){return glift.rules.movetree.getFromNode(this._nodeHistory[0])},node:function(){return this._nodeHistory[this._nodeHistory.length-1]},properties:function(){return this.node().properties()},findNextMove:function(b,c){for(var f=this.node().children,g=glift.sgf.colorToToken(c),h={},k=0;k<f.length;k++){var l=f[k];l.properties().contains(g)&&""!=l.properties().getOneValue(g)&&(h[l.properties().getAsPoint(g).hash()]=
l.getVarNum())}return void 0!==h[b.hash()]?h[b.hash()]:a.none},getLastMove:function(){return this.properties().getMove()},nextMoves:function(){for(var a=this.node(),b=[],c=0;c<a.numChildren();c++){var g=a.getChild(c).properties().getMove();g!==glift.util.none&&b.push(g)}return b},getCurrentPlayer:function(){var c=this.properties().getMove();return c===a.none?b.states.BLACK:c.color===b.states.BLACK?b.states.WHITE:b.states.BLACK},moveDown:function(a){a=void 0===a?0:a;void 0!==this.node().getChild(a)&&
(a=this.node().getChild(a),this._nodeHistory.push(a));return this},moveUp:function(){1<this._nodeHistory.length&&this._nodeHistory.pop();return this},moveToRoot:function(){this._nodeHistory=this._nodeHistory.slice(0,1);return this},addNode:function(){this.node().addChild();this.moveDown(this.node().numChildren()-1);return this},deleteCurrentNode:function(){throw"Unfinished";},recurse:function(a){glift.rules.movetree.searchMoveTreeDFS(this,a)},recurseFromRoot:function(a){glift.rules.movetree.searchMoveTreeDFS(this.getTreeFromRoot(),
a)},toSgf:function(){for(var a in this.getAllProps());},debugLog:function(a){void 0===a&&(a="  ");glift.util.logz(a+this.node(b).getVarNum()+"-"+this.node(b).getNodeNum());for(var b=0;b<this.node().numChildren();b++)this.moveDown(b),this.debugLog(a),this.moveUp()},setIntersections:function(a){var b=this.getTreeFromRoot(),c=glift.sgf.allProperties;b.properties().contains(c.SZ)||this.properties().add(c.SZ,a+"");return this},getIntersections:function(){var a=this.getTreeFromRoot(),b=glift.sgf.allProperties;
if(a.properties().contains(b.SZ))return parseInt(a.properties().getAllValues(b.SZ))}}})();
glift.rules.problems={isCorrectPosition:function(a,b){var c=glift.enums.problemResults;if(a.properties().matches(b))return c.CORRECT;for(var d=glift.rules.treepath.flattenMoveTree(a),e={},f=0;f<d.length;f++){for(var g=d[f],h=glift.rules.movetree.getFromNode(a.node()),k=!1,l=0;l<g.length;l++)h.moveDown(g[l]),h.properties().matches(b)&&(k=!0);k?e[c.CORRECT]=!0:e[c.INCORRECT]=!0}return e[c.CORRECT]&&!e[c.INCORRECT]?c.CORRECT:e[c.CORRECT]&&e[c.INCORRECT]?c.INDETERMINATE:c.INCORRECT},correctNextMoves:function(a,
b){for(var c=a.nextMoves(),d=glift.enums.problemResults.INCORRECT,e=[],f=0;f<c.length;f++)a.moveDown(f),glift.rules.problems.isCorrectPosition(a,b)!==d&&e.push(c[f]),a.moveUp();return e}};
(function(){var a=glift.util,b=glift.enums;glift.rules.properties=function(a){return new c(a)};var c=function(a){this.propMap=void 0===a?{}:a};c.prototype={add:function(b,c){if(void 0===glift.sgf.allProperties[b])throw"Can't add undefined properties";"string"!==a.typeOf(c)&&"array"!==a.typeOf(c)&&(c=c.toString());c="string"===a.typeOf(c)?[c]:c;this.contains(b)?this.propMap[b]=this.getAllValues(b).concat(c):this.propMap[b]=c;return this},getAllValues:function(b){return void 0===glift.sgf.allProperties[b]?
a.none:void 0!==this.propMap[b]?this.propMap[b]:a.none},getOneValue:function(b,c){c=void 0!==c&&"number"===typeof c&&0<=c?c:0;var f=this.getAllValues(b);return f!==a.none&&1<=f.length?f[c]:a.none},getAsPoint:function(b,c){var f=this.getOneValue(b,c);return f===a.none?f:glift.util.pointFromSgfCoord(f)},contains:function(b){return this.getAllValues(b)!==a.none},remove:function(b){if(this.contains(b)){var c=this.getAllValues(b);delete this.propMap[b];return c}return a.none},set:function(a,b){void 0!==
a&&void 0!==b&&("string"===glift.util.typeOf(b)?this.propMap[a]=[b]:"array"===glift.util.typeOf(b)&&(this.propMap[a]=b));return this},getPlacementsAsPoints:function(a){var c="";a===b.states.BLACK?c=glift.sgf.allProperties.AB:a===b.states.WHITE&&(c=glift.sgf.allProperties.AW);return""===c||!this.contains(c)?[]:glift.sgf.allSgfCoordsToPoints(this.getAllValues(c))},getComment:function(){return this.contains("C")?this.getOneValue("C"):a.none},getMove:function(){var a=glift.enums.states.BLACK,b=glift.enums.states.WHITE;
return this.contains("B")?""===this.getOneValue("B")?{color:a}:{color:a,point:this.getAsPoint("B")}:this.contains("W")?""===this.getOneValue("W")?{color:b}:{color:b,point:this.getAsPoint("W")}:glift.util.none},matches:function(a){for(var b in a)if(this.contains(b)){var c=a[b];if(0===c.length)return!0;for(var g=this.getAllValues(b),h=0;h<g.length;h++)for(var k=0;k<c.length;k++)if(-1!==g[h].indexOf(c[k]))return!0}return!1},getAllStones:function(){var b=glift.enums.states,c={},f=b.WHITE;c[b.BLACK]=this.getPlacementsAsPoints(b.BLACK);
c[f]=this.getPlacementsAsPoints(b.WHITE);b=this.getMove();b!=a.none&&void 0!==b.point&&c[b.color].push(b.point);return c}}})();
glift.rules.treepath={parseInitPosition:function(a){if(void 0===a)return[];if("number"===glift.util.typeOf(a))a=""+a;else{if("array"===glift.util.typeOf(a))return a;if("string"!==glift.util.typeOf(a))return[]}var b=[],c=0;a=a.split("-");for(var d=0;d<a.length;d++){for(var e=a[d].split("."),f=0;f<e[0]-c;f++)b.push(0);c=e[0];for(f=1;f<e.length;f++)b.push(parseInt(e[f])),c++}return b},flattenMoveTree:function(a){for(var b=[],c=0;c<a.node().numChildren();c++){a.moveDown(c);var d=glift.rules.treepath._flattenMoveTree(a,
[]);a.moveUp();for(var e=0;e<d.length;e++)b.push(d[e])}return b},_flattenMoveTree:function(a,b){void 0===b&&(b=[]);b.push(a.node().getVarNum());for(var c=[],d=0;d<a.node().numChildren();d++){a.moveDown(d);var e=glift.rules.treepath._flattenMoveTree(a,b.slice()),c=c.concat(e);a.moveUp(d)}0==c.length&&c.push(b);return c}};
glift.sgf={colorToToken:function(a){if(a===glift.enums.states.WHITE)return"W";if(a===glift.enums.states.BLACK)return"B";throw"Unknown color-to-token conversion for: "+a;},allSgfCoordsToPoints:function(a){for(var b=[],c=0;c<a.length;c++)b.push(glift.util.pointFromSgfCoord(a[c]));return b},convertFromLabelData:function(a){a=a.split(":");return{point:glift.util.pointFromSgfCoord(a[0]),value:a[1]}},convertFromLabelArray:function(a){for(var b=[],c=0;c<a.length;c++)b.push(glift.sgf.convertFromLabelData(a[c]));
return b},pointToSgfCoord:function(a){return String.fromCharCode(a.x()+97)+String.fromCharCode(a.y()+97)}};
glift.sgf.parse=function(a){var b=/\s|\n/,c=/[A-Z]/,d=1,e=glift.rules.movetree.getInstance(),f=[],g=[],h=[],k="",l="",m=0,q=0,n=function(a){glift.sgf.parseError(m,q,l,a)},r=function(){var a=f.join("");f=[];return a},p=function(){0<k.length&&(e.properties().add(k,g),g=[],k="")};(function(){for(var s=0;s<a.length;s++)if(q++,l=a.charAt(s),"\n"===l&&3!==d)m++,q=0;else switch(d){case 1:"("===l||b.test(l)?h.push(e.node().getNodeNum()):";"===l?d=4:b.test(l)||n("Unexpected character");break;case 2:c.test(l)?
(f.push(l),2<f.length&&n("Expected: length two proprety. Found: "+f)):"["===l?(k=r(),void 0===glift.sgf.allProperties[k]&&n("Unknown property: "+k),d=3):b.test(l)?n("Unexpected whitespace in Property"):n("Unexpected character");break;case 3:"]"===l&&"\\"===f[f.length-1]?f.push(l):"]"===l?(g.push(r()),d=4):f.push(l);break;case 4:if(c.test(l))p(),f.push(l),d=2;else if("["===l)0<k.length?d=3:n("Unexpected token.  Orphan property data.");else if("("===l)p(),h.push(e.node().getNodeNum());else if(")"===
l){p();if(0===h.length){for(;0!==e.node().getNodeNum();)e.moveUp();return e}for(var t=h.pop();e.node().getNodeNum()!==t;)e.moveUp()}else";"===l?(p(),e.addNode()):b.test(l)||n("Unknown token");break;default:n("Fatal Error: Unknown State!")}0!==e.node().getNodeNum()&&n("Expected to end up at start.")})();return e};glift.sgf.parseError=function(a,b,c,d){a="SGF Parsing Error: At line ["+a+"], column ["+b+"], char ["+c+"], "+d;glift.util.logz(a);throw a;};
glift.sgf.allProperties={AB:"AB",AE:"AE",AN:"AN",AP:"AP",AR:"AR",AS:"AS",AW:"AW",B:"B",BL:"BL",BM:"BM",BR:"BR",BS:"BS",BT:"BT",C:"C",CA:"CA",CH:"CH",CP:"CP",CR:"CR",DD:"DD",DM:"DM",DO:"DO",DT:"DT",EL:"EL",EV:"EV",EX:"EX",FF:"FF",FG:"FG",GB:"GB",GC:"GC",GM:"GM",GN:"GN",GW:"GW",HA:"HA",HO:"HO",ID:"ID",IP:"IP",IT:"IT",IY:"IY",KM:"KM",KO:"KO",L:"L",LB:"LB",LN:"LN",LT:"LT",M:"M",MA:"MA",MN:"MN",N:"N",OB:"OB",OH:"OH",OM:"OM",ON:"ON",OP:"OP",OT:"OT",OV:"OV",OW:"OW",PB:"PB",PC:"PC",PL:"PL",PM:"PM",PW:"PW",
RE:"RE",RG:"RG",RO:"RO",RU:"RU",SC:"SC",SE:"SE",SI:"SI",SL:"SL",SO:"SO",SQ:"SQ",ST:"ST",SU:"SU",SZ:"SZ",TB:"TB",TC:"TC",TE:"TE",TM:"TM",TR:"TR",TW:"TW",UC:"UC",US:"US",V:"V",VW:"VW",W:"W",WL:"WL",WR:"WR",WS:"WS",WT:"WT"};glift.controllers={};glift.controllers.allCorrectProblem=function(a){var b=glift.util.beget(glift.controllers.base()),b=glift.util.setMethods(b,glift.controllers.AllCorrectProblemMethods);b.initOptions(a);return b};glift.controllers.AllCorrectProblemMethods={};
(function(){glift.controllers.base=function(){return new a};var a=function(){this.sgfString="";this.initialPosition=[];this.problemConditions={};this.goban=this.movetree=this.treepath=void 0};a.prototype={initOptions:function(a){if(void 0===a)throw"Options is undefined!  Can't create controller";this.sgfString=a.sgfString||"";this.initialPosition=a.initialPosition||[];this.problemConditions=a.problemConditions||void 0;this.extraOptions(a);this.initialize();return this},extraOptions:function(a){},
addStone:function(a,c){throw"Not Implemented";},recordCaptures:function(a){this.currentMoveNumber++;this.captureHistory.push(a);return this},initialize:function(){var a=glift.rules;this.treepath=a.treepath.parseInitPosition(this.initialPosition);this.currentMoveNumber=this.treepath.length;this.movetree=a.movetree.getFromSgf(this.sgfString,this.treepath);a=a.goban.getFromMoveTree(this.movetree,this.treepath);this.goban=a.goban;this.captureHistory=a.captures;return this},getEntireBoardState:function(){return glift.rules.intersections.getFullBoardData(this.movetree,
this.goban,this.problemConditions)},getNextBoardState:function(){return glift.rules.intersections.nextBoardData(this.movetree,this.getCaptures(),this.problemConditions)},getCaptures:function(){return 0===this.captureHistory.length?{BLACK:[],WHITE:[]}:this.captureHistory[this.currentMoveNumber-1]},canAddStone:function(a,c){return this.goban.placeable(a,c)},getCurrentPlayer:function(){return this.movetree.getCurrentPlayer()},getIntersections:function(){return this.movetree.getIntersections()},nextMove:function(a){if(void 0!==
this.treepath[this.currentMoveNumber]&&(void 0===a||this.treepath[this.currentMoveNumber]===a))this.movetree.moveDown(this.treepath[this.currentMoveNumber]);else if(a=void 0===a?0:a,0<=a&&a<=this.movetree.nextMoves().length-1)this.setNextVariation(a),this.movetree.moveDown(a);else return glift.util.none;a=this.goban.loadStonesFromMovetree(this.movetree);this.recordCaptures(a);return this.getNextBoardState()},prevMove:function(){if(0===this.currentMoveNumber)return glift.util.none;var a=this.getCaptures(),
c=this.movetree.properties().getAllStones();this.captureHistory=this.captureHistory.slice(0,this.currentMoveNumber-1);this.goban.unloadStones(c,a);this.currentMoveNumber=0===this.currentMoveNumber?this.currentMoveNumber:this.currentMoveNumber-1;this.movetree.moveUp();return glift.rules.intersections.previousBoardData(this.movetree,c,a,this.problemConditions)},setNextVariation:function(a){this.treepath=this.treepath.slice(0,this.currentMoveNumber);this.treepath.push(a%this.movetree.node().numChildren());
return this},toBeginning:function(){this.movetree=this.movetree.getTreeFromRoot();this.goban=glift.rules.goban.getFromMoveTree(this.movetree,[]).goban;this.captureHistory=[];this.currentMoveNumber=0;return this.getEntireBoardState()},toEnd:function(){for(;this.nextMove()!==glift.util.none;);return this.getEntireBoardState()}}})();
(function(){glift.controllers.gameViewer=function(b){var c=glift.util.beget(glift.controllers.base()),c=glift.util.setMethods(c,a);c.initOptions(b);return c};var a={extraOptions:function(a){},addStone:function(a,c){var d=this._possibleNextMoves(),e=a.toString()+"-"+c;return void 0===d[e]?glift.util.none:this.nextMove(d[e])},getNextVariationNumber:function(){return this.currentMoveNumber>this.treepath.length||void 0===this.treepath[this.currentMoveNumber]?0:this.treepath[this.currentMoveNumber]},moveUpVariations:function(){return this.setNextVariation((this.getNextVariationNumber()+
1)%this.movetree.node().numChildren())},moveDownVariations:function(){return this.setNextVariation((this.getNextVariationNumber()-1+ +this.movetree.node().numChildren())%this.movetree.node().numChildren())},_possibleNextMoves:function(){for(var a={},c=this.movetree.nextMoves(),d=0;d<c.length;d++){var e=c[d];a[(void 0!==e.point?e.point.toString():"PASS")+"-"+e.color]=d}return a}}})();
glift.controllers.staticProblem=function(a){var b=glift.util.beget(glift.controllers.base()),b=glift.util.setMethods(b,glift.controllers.StaticProblemMethods);b.initOptions(a);return b};
glift.controllers.StaticProblemMethods={reload:function(){this.initialize()},addStone:function(a,b){var c=glift.enums.problemResults,d=c.CORRECT,e=c.INCORRECT,f=c.INDETERMINATE,c=c.FAILURE,g=this.goban.addStone(a,b);if(g.successful)c={},c[b]=g.captures,this.recordCaptures(c);else return{result:c};c=this.movetree.findNextMove(a,b);if(c===glift.util.none)return this.movetree.addNode(),this.movetree.properties().add(glift.sgf.colorToToken(b),a.toSgfCoord()),d=this.getNextBoardState(),d.result=e,d;this.movetree.moveDown(c);
c=glift.rules.problems.isCorrectPosition(this.movetree,this.problemConditions);if(c===d||c==e)return d=this.getNextBoardState(),d.result=c,d;if(c===f){e=this.getNextBoardState();d=glift.math.getRandomInt(0,this.movetree.node().numChildren()-1);this.movetree.moveDown(d);d=this.movetree.properties().getMove();g=this.goban.addStone(d.point,d.color);c={};c[d.color]=g.captures;this.recordCaptures(c);d=this.getNextBoardState();for(b in e.stones)for(c=0;c<e.stones[b].length;c++)d.stones[b].push(e.stones[b][c]);
d.result=f;return d}throw"Unexpected result output: "+c;}};
glift.bridge={setDisplayState:function(a,b,c){b.intersections().clearMarks();a.displayDataType===glift.enums.displayDataTypes.FULL&&b.intersections().clearAll();for(var d in a.stones)for(var e=0;e<a.stones[d].length;e++){var f=a.stones[d][e];b.intersections().setStoneColor(f,d)}d={};glift.bridge.shouldShowNextMoves(a,c)&&(d=glift.bridge.variationMapping(a.nextMoves));c=glift.enums.marks;for(var g in a.marks)for(e=0;e<a.marks[g].length;e++)f=a.marks[g][e],g===c.LABEL?void 0!==d[f.point.toString()]?
(b.intersections().addMarkPt(f.point,c.VARIATION_MARKER,f.value),delete d[f.point.toString()]):b.intersections().addMarkPt(f.point,c.LABEL,f.value):b.intersections().addMarkPt(f,g);e=1;g=glift.bridge.variationMapping(a.correctNextMoves);for(var h in d)f=d[h],f in g?b.intersections().addMarkPt(f,c.CORRECT_VARIATION,e):b.intersections().addMarkPt(f,c.VARIATION_MARKER,e),e+=1;a.lastMove&&(a.lastMove!==glift.util.none&&void 0!==a.lastMove.point)&&(a=a.lastMove,b.intersections().addMarkPt(a.point,c.STONE_MARKER))},
shouldShowNextMoves:function(a,b){return a.nextMoves&&(1<a.nextMoves.length&&b===glift.enums.showVariations.MORE_THAN_ONE||1<=a.nextMoves.length&&b===glift.enums.showVariations.ALWAYS)},variationMapping:function(a){for(var b={},c=0;c<a.length;c++){var d=a[c];void 0!==d.point&&(b[d.point.toString()]=d.point)}return b}};
glift.bridge.getCropFromMovetree=function(a){var b=glift.displays.bboxFromPts,c=glift.util.point,d=glift.enums.boardRegions,e=a.getIntersections()-1,f=Math.ceil(e/2),g={},h={},k=0;if(19!==a.getIntersections())return glift.enums.boardRegions.ALL;g[d.TOP_LEFT]=b(c(0,0),c(f,f));g[d.TOP_RIGHT]=b(c(f,0),c(e,f));g[d.BOTTOM_LEFT]=b(c(0,f),c(f,e));g[d.BOTTOM_RIGHT]=b(c(f,f),c(e,e));a.recurseFromRoot(function(a){a=a.properties().getAllStones();for(var b in a)for(var c=a[b],d=0;d<c.length;d++){var e=c[d];k+=
1;for(var p in g){var s=g[p];if(!(f===e.x()||f===e.y())&&s.contains(e))void 0===h[p]&&(h[p]=[]),h[p].push(e)}}});return glift.bridge._getRegionFromTracker(h,k)};glift.bridge._getRegionFromTracker=function(a,b){var c=[],d;for(d in a)c.push(d);if(1===c.length)return c[0];if(2!==c.length)return glift.enums.boardRegions.ALL;var c=glift.util.intersection(glift.util.regions.getComponents(c[0]),glift.util.regions.getComponents(c[1])),e;for(e in c)return e;return glift.boardRegions.ALL};
glift.widgets={create:function(a){a=glift.widgets.options.setBaseOptionDefaults(a);a.sgf&&0===a.sgfList.length&&(a.sgfList=[a.sgf]);a.enableFastClick&&glift.global.enableFastClick();return(new glift.widgets.WidgetManager(a.sgfList,a.initialListIndex,a.allowWrapAround,a.sgfDefaults,glift.widgets.options.getDisplayOptions(a))).draw()}};
glift.widgets.BaseWidget=function(a,b,c){this.type=a.type;this.sgfOptions=glift.util.simpleClone(a);this.displayOptions=glift.util.simpleClone(b);this.manager=c;this.totalCorrectAnswers=this.numCorrectAnswers=this.correctNextSet=this.correctness=void 0;this.wrapperDiv=b.divId;this.boardRegion=this.iconBar=this.display=this.controller=void 0};
glift.widgets.BaseWidget.prototype={draw:function(){this.controller=this.sgfOptions.controllerFunc(this.sgfOptions);this.displayOptions.intersections=this.controller.getIntersections();var a=glift.enums.boardComponents,b=[a.BOARD];this.displayOptions.boardRegion=this.sgfOptions.boardRegion===glift.enums.boardRegions.AUTO?glift.bridge.getCropFromMovetree(this.controller.movetree):this.sgfOptions.boardRegion;this.displayOptions.useCommentBar&&b.push(a.COMMENT_BOX);0<this.sgfOptions.icons.length&&b.push(a.ICONBAR);
a=glift.displays.positionWidget(glift.displays.bboxFromDiv(this.wrapperDiv),this.displayOptions.boardRegion,this.displayOptions.intersections,b);a=this._createDivsForPositioning(a,this.wrapperDiv);this.displayOptions.divId=a.boardBoxId;this.display=glift.displays.create(this.displayOptions);a.commentBoxId&&this._createCommentBox(a.commentBoxId);a.iconBarBoxId&&this._createIconBar(a.iconBarBoxId);this._initStoneActions();this._initIconActions();this._initKeyHandlers();this._initProblemData();this.applyBoardData(this.controller.getEntireBoardState());
return this},_createDivsForPositioning:function(a,b){for(var c=["boardBox","iconBarBox","commentBox"],d={},e=0;e<c.length;e++)if(a[c[e]]){var f=d,g=c[e]+"Id",h=a[c[e]],k="glift_internal_div_"+glift.util.idGenerator.next();$("#"+b).append('<div id="'+k+'"></div>');h={top:h.top(),left:h.left(),width:h.width(),height:h.height(),position:"absolute"};$("#"+k).css(h);f[g]=k}return d},_getProblemType:function(){var a=this.controller.movetree.properties(),b=glift.enums.problemTypes;return a.contains("EV")&&
(a=a.getOneValue("EV").toUpperCase(),void 0!==b[a]&&a!==b.AUTO)?a:0===this.controller.movetree.nextMoves().length?b.EXAMPLE:b.STANDARD},_setNotSelectable:function(a){$("#"+a).css({"-webkit-touch-callout":"none","-webkit-user-select":"none","-khtml-user-select":"none","-moz-user-select":"moz-none","-ms-user-select":"none","user-select":"none","-webkit-highlight":"none","-webkit-tap-highlight-color":"rgba(0,0,0,0)",cursor:"default"});return this},_createCommentBox:function(a){this.commentBox=glift.displays.gui.commentBox(a,
this.displayOptions.theme)},_createIconBar:function(a){this.iconBar=glift.displays.gui.iconBar({themeName:this.displayOptions.theme,divId:a,vertMargin:5,horzMargin:5,icons:this.sgfOptions.icons})},_initIconActions:function(){for(var a=this,b=this.displayOptions.iconActions,c=this.sgfOptions.icons,d=0;d<c.length;d++){var e=c[d];if(b.hasOwnProperty(e)){b[e].mouseover=b[e].mouseover||function(a,b,c){a=b.iconBar.iconId(c);d3.select("#"+a).attr("fill","red")};b[e].mouseout=b[e].mouseout||function(a,b,
c){a=b.iconBar.iconId(c);d3.select("#"+a).attr("fill",b.iconBar.theme.icons.DEFAULT.fill)};b[e].touchend=b[e].touchend||function(a,b,c){a.preventDefault&&a.preventDefault();a.stopPropagation&&a.stopPropagation();b.displayOptions.iconActions[c].click(a,b)};for(var f in b[e])(function(b,c,d){a.iconBar.setEvent(b,e,function(){d(d3.event,a,c)})})(f,e,b[e][f])}}},_initStoneActions:function(){var a=this.displayOptions.stoneActions;a.click=this.sgfOptions.stoneClick;var b=this,c;for(c in a)(function(a,c){b.display.intersections().setEvent(a,
function(a){c(d3.event,b,a)})})(c,a[c])},_initKeyHandlers:function(){var a=this;this.keyHandlerFunc=function(b){var c=glift.keyMappings.codeToName(b.which);if(c&&void 0!==a.sgfOptions.keyMappings[c]){for(var c=a.sgfOptions.keyMappings[c].split("."),d=a.displayOptions[c[0]],e=1;e<c.length;e++)d=d[c[e]];d(b,a)}};$("body").keydown(this.keyHandlerFunc)},_initProblemData:function(){if(this.sgfOptions.widgetType===glift.enums.widgetTypes.CORRECT_VARIATIONS_PROBLEM){var a=glift.rules.problems.correctNextMoves(this.controller.movetree,
this.sgfOptions.problemConditions);this.correctNextSet=this.correctNextSet||{};this.numCorrectAnswers=this.numCorrectAnswers||0;this.totalCorrectAnswers=this.totalCorrectAnswers||this.sgfOptions.totalCorrectVariationsOverride||a.length;this.iconBar.addTempText(this.iconBar.getIcon("checkbox").newBbox,this.numCorrectAnswers+"/"+this.totalCorrectAnswers,"#000")}},applyBoardData:function(a){a&&a!==glift.util.none&&(this.setCommentBox(a.comment),glift.bridge.setDisplayState(a,this.display,this.sgfOptions.showVariations))},
setCommentBox:function(a){void 0!==this.commentBox&&(a&&a!==glift.util.none?this.commentBox.setText(a):this.commentBox.clearText());return this},reload:function(){void 0!==this.correctness&&(this.totalCorrectAnswers=this.numCorrectAnswers=this.correctNextSet=void 0);this.redraw()},redraw:function(){this.correctness=void 0;this.destroy();this.draw()},destroy:function(){$("#"+this.wrapperDiv).empty();void 0!==this.keyHandlerFunc&&$("body").unbind("keydown",this.keyHandlerFunc);this.display=this.keyHandlerFunc=
void 0}};glift.widgets.WidgetManager=function(a,b,c,d,e){this.sgfList=a;this.sgfListIndex=b;this.allowWrapAround=c;this.sgfDefaults=d;this.displayOptions=e;this.currentWidget=void 0};
glift.widgets.WidgetManager.prototype={draw:function(){var a=this;this.getSgfString(function(b){a.destroy();a.currentWidget=a.createWidget(b).draw()});return this},getCurrentWidget:function(){return this.currentWidget},getCurrentSgfObj:function(){var a=this.sgfList[this.sgfListIndex];if("string"===glift.util.typeOf(a)){var b={};/^\s*\(;/.test(a)?b.sgfString=a:b.url=a;a=b}a=glift.widgets.options.setSgfOptionDefaults(a,this.sgfDefaults);1<this.sgfList.length&&(this.allowWrapAround?(a.icons.push(this.displayOptions.nextSgfIcon),
a.icons.splice(0,0,this.displayOptions.previousSgfIcon)):0===this.sgfListIndex?a.icons.push(this.displayOptions.nextSgfIcon):(this.sgfListIndex!==this.sgfList.length-1&&a.icons.push(this.displayOptions.nextSgfIcon),a.icons.splice(0,0,this.displayOptions.previousSgfIcon)));return a},getSgfString:function(a){var b=this.getCurrentSgfObj();b.url?this.loadSgfWithAjax(b.url,b,a):a(b)},createWidget:function(a){return new glift.widgets.BaseWidget(a,this.displayOptions,this)},createTemporaryWidget:function(a){this.currentWidget.destroy();
a=glift.widgets.options.setSgfOptionDefaults(a,this.sgfDefaults);this.temporaryWidget=this.createWidget(a).draw()},returnToOriginalWidget:function(){this.temporaryWidget&&this.temporaryWidget.destroy();this.temporaryWidget=void 0;this.currentWidget.draw()},_nextSgfInternal:function(a){1<!this.sgfList.length||(this.allowWrapAround?this.sgfListIndex=(this.sgfListIndex+a+this.sgfList.length)%this.sgfList.length:(this.sgfListIndex+=a,0>this.sgfListIndex?this.sgfListIndex=0:this.sgfListIndex>=this.sgfList.length&&
(this.sgfListIndex=this.sgfList.length-1)),this.draw())},nextSgf:function(){this._nextSgfInternal(1)},prevSgf:function(){this._nextSgfInternal(-1)},destroy:function(){this.currentWidget&&this.currentWidget.destroy();this.currentWidget=void 0;this.temporaryWidget&&this.temporaryWidget.destroy();this.temporaryWidget=void 0;return this},loadSgfWithAjax:function(a,b,c){$.ajax({url:a,dataType:"text",cache:!1,success:function(a){b.sgfString=a;c(b)}})}};
glift.widgets.options={setBaseOptionDefaults:function(a){a=glift.util.simpleClone(a);var b=glift.util.simpleClone(glift.widgets.options.baseOptions),c;for(c in b)if("sgfDefaults"===c){a.sgfDefaults=a.sgfDefaults||{};for(var d in b.sgfDefaults)void 0===a.sgfDefaults[d]&&(a.sgfDefaults[d]=b.sgfDefaults[d])}else void 0===a[c]&&(a[c]=b[c]);return a},setSgfOptionDefaults:function(a,b){if(!a)throw"SGF Obj undefined";if(!b)throw"SGF Defaults undefined";a=glift.util.simpleClone(a);b=glift.util.simpleClone(b);
a.widgetType=a.widgetType||b.widgetType;var c=glift.util.simpleClone(glift.widgets.options[a.widgetType]),d;for(d in b)d in a||(a[d]=d in c?c[d]:b[d]);return a},getDisplayOptions:function(a){var b={},c={sgfList:!0,sgf:!0,initialListIndex:!0,allowWrapAround:!0,sgfDefaults:!0},d;for(d in a)c[d]||(b[d]=a[d]);return b}};
glift.widgets.options.baseOptions={sgf:void 0,sgfDefaults:{widgetType:glift.enums.widgetTypes.GAME_VIEWER,initialPosition:"",boardRegion:glift.enums.boardRegions.AUTO,problemCallback:function(){},problemConditions:{GB:[],C:["Correct","is correct"]},keyMappings:{ARROW_LEFT:"iconActions.chevron-left.click",ARROW_RIGHT:"iconActions.chevron-right.click"},showVariations:void 0,controllerFunc:void 0,icons:void 0,stoneClick:void 0,correctVariationsResetTime:void 0,totalCorrectVariationsOverride:void 0},
sgfList:[],initialListIndex:0,allowWrapAround:!1,divId:"glift_display",goBoardBackground:"",useCommentBar:!0,splitsWithComments:[0.7,0.2],splitsWithoutComments:[0.9],splitsWithOnlyComments:[0.8],theme:"DEFAULT",enableFastClick:!1,previousSgfIcon:"chevron-left",nextSgfIcon:"chevron-right",stoneActions:{click:void 0,mouseover:function(a,b,c){a={BLACK:"BLACK_HOVER",WHITE:"WHITE_HOVER"};var d=b.controller.getCurrentPlayer();b.controller.canAddStone(c,d)&&b.display.intersections().setStoneColor(c,a[d])},
mouseout:function(a,b,c){a=b.controller.getCurrentPlayer();b.controller.canAddStone(c,a)&&b.display&&b.display.intersections().setStoneColor(c,"EMPTY")},touchend:function(a,b,c){a.preventDefault&&a.preventDefault();a.stopPropagation&&a.stopPropagation();b.sgfOptions.stoneClick(a,b,c)}},iconActions:{start:{click:function(a,b){b.applyBoardData(b.controller.toBeginning())}},end:{click:function(a,b){b.applyBoardData(b.controller.toEnd())}},arrowright:{click:function(a,b){b.applyBoardData(b.controller.nextMove())}},
arrowleft:{click:function(a,b){b.applyBoardData(b.controller.prevMove())}},"chevron-right":{click:function(a,b){b.manager.nextSgf()}},"chevron-left":{click:function(a,b){b.manager.prevSgf()}},refresh:{click:function(a,b){b.reload()}},undo:{click:function(a,b){b.manager.returnToOriginalWidget()}},roadmap:{click:function(a,b){var c=b.manager,d={widgetType:glift.enums.widgetTypes.GAME_VIEWER,initialPosition:b.sgfOptions.initialPosition,sgfString:b.sgfOptions.sgfString,showVariations:glift.enums.showVariations.ALWAYS,
problemConditions:glift.util.simpleClone(b.sgfOptions.problemConditions),icons:["start","end","arrowleft","arrowright","undo"]};c.createTemporaryWidget(d)}}}};
glift.widgets.options.CORRECT_VARIATIONS_PROBLEM={stoneClick:function(a,b,c){a=b.controller.getCurrentPlayer();a=b.controller.addStone(c,a);var d=glift.enums.problemResults;if(a.result!==d.FAILURE){b.applyBoardData(a);var e=b.sgfOptions.problemCallback;void 0===b.correctness&&(a.result===d.CORRECT?(b.iconBar.destroyTempIcons(),void 0===b.correctNextSet[c.toString()]&&(b.correctNextSet[c.toString()]=!0,b.numCorrectAnswers++,b.numCorrectAnswers===b.totalCorrectAnswers?(b.correctness=d.CORRECT,b.iconBar.addTempText(b.iconBar.getIcon("checkbox").newBbox,
b.numCorrectAnswers+"/"+b.totalCorrectAnswers,"#0CC"),e(d.CORRECT)):(b.iconBar.addTempText(b.iconBar.getIcon("checkbox").newBbox,b.numCorrectAnswers+"/"+b.totalCorrectAnswers,"#000"),setTimeout(function(){b.controller.initialize();b.applyBoardData(b.controller.getEntireBoardState())},b.sgfOptions.correctVariationsResetTime)))):a.result==d.INCORRECT&&(b.iconBar.destroyTempIcons(),b.iconBar.addTempIcon(b.iconBar.getIcon("checkbox").newBbox,"cross","red"),b.correctness=d.INCORRECT,e(d.INCORRECT)))}},
showVariations:glift.enums.showVariations.NEVER,icons:["refresh","roadmap","checkbox"],controllerFunc:glift.controllers.staticProblem,correctVariationsResetTime:500};glift.widgets.options.EXAMPLE={stoneClick:function(a,b,c){},icons:[],problemConditions:{},showVariations:glift.enums.showVariations.MORE_THAN_ONE,controllerFunc:glift.controllers.gameViewer};
glift.widgets.options.GAME_VIEWER={stoneClick:function(a,b,c){a=b.controller.getCurrentPlayer();c=b.controller.addStone(c,a);b.applyBoardData(c)},keyMappings:{ARROW_LEFT:"iconActions.arrowleft.click",ARROW_RIGHT:"iconActions.arrowright.click"},icons:["start","end","arrowleft","arrowright"],showVariations:glift.enums.showVariations.MORE_THAN_ONE,problemConditions:{},controllerFunc:glift.controllers.gameViewer};
glift.widgets.options.STANDARD_PROBLEM={stoneClick:function(a,b,c){a=b.controller.getCurrentPlayer();c=b.controller.addStone(c,a);a=glift.enums.problemResults;if(c.result!==a.FAILURE){b.applyBoardData(c);var d=b.sgfOptions.problemCallback;void 0===b.correctness&&(c.result===a.CORRECT?(b.iconBar.addTempIcon(b.iconBar.getIcon("checkbox").newBbox,"check","#0CC"),b.correctness=a.CORRECT,d(a.CORRECT)):c.result==a.INCORRECT&&(b.iconBar.destroyTempIcons(),b.iconBar.addTempIcon(b.iconBar.getIcon("checkbox").newBbox,
"cross","red"),b.correctness=a.INCORRECT,d(a.INCORRECT)))}},showVariations:glift.enums.showVariations.NEVER,icons:["refresh","roadmap","checkbox"],controllerFunc:glift.controllers.staticProblem};
