(function(){var b=window.glift||{};b.global={debugMode:!1,performanceDebug:!1,version:"0.1.0",active:{}};window.glift=b})();
glift.util={logz:function(b){var a=b;if("array"===glift.util.typeOf(b)||"object"===glift.util.typeOf(b))a=JSON.stringify(b);console.log(""+a);return glift.util.none},beget:function(b){var a=function(){};a.prototype=b;return new a},typeOf:function(b){var a=typeof b;"object"===a&&(b?b instanceof Array&&(a="array"):a="null");return a},isArray:function(b){return b&&"object"===typeof b&&b.constructor===Array},inBounds:function(b,a){return b<a&&0<=b},outBounds:function(b,a){return b>=a||0>b},intersection:function(b,
a){var c={},d;for(d in b)void 0!==a[d]&&(c[d]=1);return c},getKeyWithDefault:function(b,a,c){void 0===b[a]&&(b[a]=c);return b[a]},sizeOf:function(b){var a=0,c;for(c in b)a+=1;return a},setMethods:function(b,a){for(var c in a)b[c]=a[c].bind(b);return b}};glift.util.debugl=function(b){glift.debugOn&&glift.util.log(b)};glift.util.log=function(b){("array"===glift.util.typeOf(b)||"object"===glift.util.typeOf(b))&&JSON.stringify(b);void 0!==console&&void 0!==console.log&&console.log(b)};
(function(){var b=function(){this.type="none"};b.prototype={toString:function(){return"None"}};glift.util.none=new b})();glift.util.colors={isLegalColor:function(b){return b===glift.enums.states.BLACK||b===glift.enums.states.WHITE||b===glift.enums.states.EMPTY},oppositeColor:function(b){return b===glift.enums.states.BLACK?glift.enums.states.WHITE:b===glift.enums.states.WHITE?glift.enums.states.BLACK:b}};
glift.enums={states:{BLACK:"BLACK",WHITE:"WHITE",EMPTY:"EMPTY"},directions:{LEFT:"LEFT",RIGHT:"RIGHT",TOP:"TOP",BOTTOM:"BOTTOM"},controllerMessages:{CONTINUE:"CONTINUE",DONE:"DONE",FAILURE:"FAILURE"},boardRegions:{LEFT:"LEFT",RIGHT:"RIGHT",TOP:"TOP",BOTTOM:"BOTTOM",TOP_LEFT:"TOP_LEFT",TOP_RIGHT:"TOP_RIGHT",BOTTOM_LEFT:"BOTTOM_LEFT",BOTTOM_RIGHT:"BOTTOM_RIGHT",ALL:"ALL"},marks:{CIRCLE:"CIRCLE",LABEL:"LABEL",SQUARE:"SQUARE",TRIANGLE:"TRIANGLE",XMARK:"XMARK",STONE_MARKER:"STONE_MARKER",VARIATION_MARKER:"VARIATION_MARKER"},
problemResults:{CORRECT:"CORRECT",INCORRECT:"INCORRECT",INDETERMINATE:"INDETERMINATE",FAILURE:"FAILURE"},svgElements:{BOARD_BASE:"board_base",BOARD_LINE:"board_line",BUTTON:"button",MARK:"mark",MARK_CONTAINER:"mark_container",GLIFT_ELEMENT:"glift_element",STARPOINT:"starpoint",STONE:"stone",STONE_SHADOW:"stone_shadow",ICON:"icon"},showVariations:{ALWAYS:"ALWAYS",NEVER:"NEVER",MORE_THAN_ONE:"MORE_THAN_ONE"}};
(function(){glift.errors={};glift.errors.ParseError=function(b){this.name="ParseError";this.message=b||""};glift.errors.ParseError.prototype=Error()})();glift.util._IdGenerator=function(b){this.seed=b||0};glift.util._IdGenerator.prototype={next:function(){var b=this.seed+"";this.seed+=1;return b}};glift.util.idGenerator=new glift.util._IdGenerator(0);
glift.keyMappings={_nameToCode:{ARROW_LEFT:37,ARROW_UP:38,ARROW_RIGHT:39,ARROW_:40,BACKSPACE:8,ENTER:13,SHIFT:16,FORWARD_SLASH:191,A:65,B:66,C:67,D:68,E:69,F:70,G:71,H:72,I:73,J:74,K:75},nameToCode:function(b){return glift.keyMappings._nameToCode[b]},_codeToName:void 0,codeToName:function(b){if(void 0===glift.keyMappings._codeToName){var a={},c;for(c in glift.keyMappings._nameToCode)a[glift.keyMappings._nameToCode[c]]=c;glift.keyMappings._codeToName=a}return glift.keyMappings._codeToName[b]}};
glift.math={abs:function(b){return 0<=b?b:-1*b},max:function(b,a){return b>a?b:a},min:function(b,a){return b>a?a:b},isEven:function(b){return 0==b%2?!0:!1},getRandomInt:function(b,a){return Math.floor(Math.random()*(a-b+1))+b}};
(function(){glift.util.point=function(a,c){return new b(a,c)};glift.util.coordToString=function(a,c){return a+","+c};glift.util.pointFromString=function(a){try{var c=a.split(","),d=parseInt(c[0]),b=parseInt(c[1]);return glift.util.point(d,b)}catch(f){throw"Parsing Error! Couldn't parse a point from: "+a;}};glift.util.pointFromSgfCoord=function(a){if(2!=a.length)throw"Unknown SGF Coord length: "+a.length;return glift.util.point(a.charCodeAt(0)-97,a.charCodeAt(1)-97)};glift.util.pointFromHash=function(a){return glift.util.pointFromString(a)};
var b=function(a,c){this._x=a;this._y=c};b.prototype={x:function(){return this._x},y:function(){return this._y},equals:function(a){return this._x===a.x()&&this._y===a.y()},toSgfCoord:function(){return String.fromCharCode(this.x()+97)+String.fromCharCode(this.y()+97)},hash:function(){return this.toString()},toString:function(){return glift.util.coordToString(this.x(),this.y())},translate:function(a,c){return glift.util.point(this.x()+a,this.y()+c)},log:function(){glift.util.logz(this.toString())}}})();
glift.util.regions={getComponents:function(b){var a=glift.enums.boardRegions,c={};b===a.TOP_LEFT?(c[a.TOP]=1,c[a.LEFT]=1):b===a.TOP_RIGHT?(c[a.TOP]=1,c[a.RIGHT]=1):b===a.BOTTOM_LEFT?(c[a.BOTTOM]=1,c[a.LEFT]=1):b===a.BOTTOM_RIGHT&&(c[a.BOTTOM]=1,c[a.RIGHT]=1);return c}};
glift.testUtil={ptlistToMap:function(b){outMap={};for(var a=0;a<b.length;a++){var c=b[a];void 0!==c.value?outMap[c.point.hash()]=c:outMap[c.hash()]=c}return outMap},assertFullDiv:function(b){ok(0!==d3.selectAll("#"+b+" svg")[0].length,"Div should contain contents")},assertEmptyDiv:function(b){deepEqual(d3.selectAll("#"+b+" svg")[0].length,0,"Div should not contain contents")}};
glift.themes={registered:{},get:function(b){var a=glift.themes.registered;b=!(b in a)?glift.util.none:a[b];return b===glift.util.none?b:glift.themes.deepCopy({},b,a.DEFAULT)},deepCopy:function(b,a,c){for(var d in c){var e=glift.util.typeOf(c[d]),f=c;void 0!==a[d]&&(f=a);switch(e){case "object":b[d]=glift.themes.deepCopy({},a[d]||{},c[d]);break;case "array":for(var e={},f=[],h=c[d].concat(a[d]||[]),k=0;k<h.length;k++){var l=h[k];l in e||(f.push(l),e[l]=1)}b[d]=l;break;default:b[d]=f[d]}}return b},
has:function(b){return b in glift.themes.registered},setGoBoardBackground:function(b,a){if(b)b.board.imagefill=a;else throw"Yikes! Not a theme: cannot set background image.";}};
glift.themes.registered.DEFAULT={board:{fill:"#f5be7e",stroke:"#000000","stroke-width":1},starPoints:{sizeFraction:0.15,fill:"#000000"},lines:{stroke:"#000000","stroke-width":0.5},stones:{shadows:{stroke:"none",fill:"none"},marks:{"font-family":"sans-serif"},EMPTY:{fill:"blue",opacity:0,marks:{fill:"black",stroke:"black",VARIATION_MARKER:{stroke:"",fill:"#822"}}},BLACK:{fill:"black",opacity:1,"stroke-width":1,stroke:"black",marks:{fill:"white",stroke:"white",STONE_MARKER:{fill:"#CCF",opacity:0.6},
VARIATION_MARKER:{stroke:"",fill:"#822"}}},BLACK_HOVER:{fill:"black",opacity:0.5},WHITE:{stroke:"black",fill:"white",opacity:1,"stroke-width":1,marks:{fill:"black",stroke:"black",STONE_MARKER:{fill:"#33F",opacity:0.6},VARIATION_MARKER:{fill:"#DD0000",stroke:"#A22"}}},WHITE_HOVER:{fill:"white",stroke:"black",opacity:0.5}},icons:{DEFAULT:{fill:"#0000AA",stroke:"black"},DEFAULT_HOVER:{fill:"cyan",stroke:"black"}},defs:{}};
glift.themes.registered.DEPTH={stones:{shadows:{stroke:"none",fill:"#555"},WHITE:{stroke:"white",fill:"white"},WHITE_HOVER:{fill:"white",stroke:"white",opacity:0.5}}};glift.themes.registered.MOODY={board:{fill:"#777777"},stones:{WHITE:{stroke:"white",fill:"white"},WHITE_HOVER:{fill:"white",stroke:"white",opacity:0.5}}};glift.themes.registered.TEXTBOOK={board:{fill:"#FFFFFF"}};glift.themes.registered.TRANSPARENT={board:{fill:"none"}};
glift.displays={create:function(b){b=glift.displays.processOptions(b);var a=glift.displays.environment.get(b),c=glift.themes.get(b.theme);b.goBoardBackground&&""!==b.goBoardBackground&&glift.themes.setGoBoardBackground(c,b.goBoardBackground);return glift.displays.board.create(a,b.theme,c)}};
(function(){glift.displays.bboxFromPts=function(a,c){return new b(a,c)};glift.displays.bboxFromDiv=function(a){return glift.displays.bbox(glift.util.point(0,0),$("#"+a).width(),$("#"+a).height())};glift.displays.bbox=function(a,c,d){return new b(a,glift.util.point(a.x()+c,a.y()+d))};var b=function(a,c){this.topLeft=function(){return a};this.botRight=function(){return c};this.center=function(){return glift.util.point(glift.math.abs((c.x()-a.x())/2)+a.x(),glift.math.abs((c.y()-a.y())/2)+a.y())};this.width=
function(){return c.x()-a.x()};this.height=function(){return c.y()-a.y()};this.top=function(){return a.y()};this.left=function(){return a.x()};this.bottom=function(){return c.y()};this.right=function(){return c.x()}};b.prototype={draw:function(a,c){a.rect(this.topLeft().x(),this.topLeft().y(),this.width(),this.height()).attr({fill:c,opacity:0.5})},log:function(){glift.util.logz("TopLeft: "+JSON.stringify(this.topLeft()));glift.util.logz("BotRight: "+JSON.stringify(this.botRight()));glift.util.logz("Width: "+
this.width());glift.util.logz("Height: "+this.height())},contains:function(a){return a.x()>=this.topLeft().x()&&a.x()<=this.botRight().x()&&a.y()>=this.topLeft().y()&&a.y()<=this.botRight().y()},equals:function(a){return a.topLeft()&&this.topLeft().equals(a.topLeft())&&a.botRight()&&this.botRight().equals(a.botRight())},scale:function(a){var c=this.height()*a,d=this.width()*a;a=glift.util.point(this.topLeft().x()*a,this.topLeft().y()*a);return glift.displays.bbox(a,d,c)},toString:function(){return this.topLeft().toString()+
","+this.botRight().toString()},translate:function(a,c){return glift.displays.bboxFromPts(glift.util.point(this.topLeft().x()+a,this.topLeft().y()+c),glift.util.point(this.botRight().x()+a,this.botRight().y()+c))}}})();
(function(){glift.displays.boardPoints=function(a,c,d){return new b(a,c,d)};glift.displays.boardPointsFromLineBox=function(a,c){for(var d=a.spacing,b=d/2,f=a.bbox,h=f.left()+a.extensionBox.left()*d,f=f.top()+a.extensionBox.top()*d,k=a.pointTopLeft.x(),l=a.pointTopLeft.y(),m={},n=0;n<=a.yPoints;n++)for(var r=0;r<=a.xPoints;r++){var q=h+r*d,t=f+n*d,p=glift.util.point(k+r,l+n),q=glift.util.point(q,t);m[p.hash()]={intPt:p,coordPt:q,bbox:glift.displays.bboxFromPts(glift.util.point(q.x()-b,q.y()-b),glift.util.point(q.x()+
b,q.y()+b))}}return glift.displays.boardPoints(m,d,c)};var b=function(a,c,d){this.points=a;this.spacing=c;this.radius=c/2;this.numIntersections=d};b.prototype={getCoords:function(){return this.points},getCoord:function(a){return this.points[a.hash()]},forEach:function(a){for(var c in this.points)a(this.points[c])},data:function(){var a=[];this.forEach(function(c){a.push(c)});return a},hasCoord:function(a){return void 0!==this.points[a.hash()]},starPoints:function(){for(var a=glift.util.point,c={9:[[2,
6],[4]],13:[[3,9],[6]],19:[[3,9,15]]}[this.numIntersections]||[],d=[],b=0;b<c.length;b++)for(var f=c[b],h=0;h<f.length;h++)for(var k=0;k<f.length;k++){var l=a(f[h],f[k]);this.hasCoord(l)&&d.push(l)}return d},_debugDraw:function(a,b){for(var d in this.points){var e=this.points[d].bbox.center().x(),f=this.points[d].bbox.center().y();a.circle(e,f,this.radius).attr({fill:b,opacity:0.3})}}}})();
(function(){glift.displays.cropbox={LINE_EXTENSION:0.5,DEFAULT_EXTENSION:0,OVERFLOW:1.5,create:function(a,c,d,e){return new b(a,c,d,e)},getFromRegion:function(a,b){var d=glift.util,e=glift.enums.boardRegions;a=a||e.ALL;var f=b-1,h=Math.ceil(f/2),k=0,l=0,m=f,n=f,r=this.DEFAULT_EXTENSION,q=this.DEFAULT_EXTENSION,t=this.DEFAULT_EXTENSION,p=this.DEFAULT_EXTENSION;switch(a){case e.LEFT:n=h+1;p=this.LINE_EXTENSION;break;case e.RIGHT:l=h-1;q=this.LINE_EXTENSION;break;case e.TOP:m=h+1;t=this.LINE_EXTENSION;
break;case e.BOTTOM:k=h-1;r=this.LINE_EXTENSION;break;case e.TOP_LEFT:m=h+1;t=this.LINE_EXTENSION;n=h+2;p=this.LINE_EXTENSION;break;case e.TOP_RIGHT:m=h+1;t=this.LINE_EXTENSION;l=h-2;q=this.LINE_EXTENSION;break;case e.BOTTOM_LEFT:k=h-1;r=this.LINE_EXTENSION;n=h+2;p=this.LINE_EXTENSION;break;case e.BOTTOM_RIGHT:k=h-1,r=this.LINE_EXTENSION,l=h-2,p=this.LINE_EXTENSION}e=glift.displays.bboxFromPts(d.point(l,k),d.point(n,m));d=glift.displays.bboxFromPts(d.point(q,r),d.point(p,t));return glift.displays.cropbox.create(e,
d,0,f)}};var b=function(a,b,d,e){var f=glift.displays.cropbox.OVERFLOW;this.cbox=function(){return a};this.extBox=function(){return b};this.xPoints=function(){return a.width()};this.yPoints=function(){return a.height()};this.widthMod=function(){return a.width()+b.topLeft().x()+b.botRight().x()+f};this.heightMod=function(){return a.height()+b.topLeft().y()+b.botRight().y()+f}}})();
(function(){glift.displays.environment={TOPBAR_SIZE:0.1,BOTTOMBAR_SIZE:0.1,get:function(a){return new b(glift.displays.processOptions(a))},getInitialized:function(a){return glift.displays.environment.get(a).init()},environmentCopy:function(a){return new b(glift.displays.processOptions({divId:a.divId,boardRegion:a.boardRegion,intersections:a.intersections}))}};var b=function(a){this.divId=a.divId;this.boardRegion=a.boardRegion;this.intersections=a.intersections;this.cropbox=a.displayConfig._cropbox||
glift.displays.cropbox.getFromRegion(this.boardRegion,this.intersections);this.widthOverride=this.heightOverride=!1;void 0!==a.displayConfig._divHeight&&(this.divHeight=a.displayConfig._divHeight,this.heightOverride=!0);void 0!==a.displayConfig._divWidth&&(this.divWidth=a.displayConfig._divWidth,this.widthOverride=!0)};b.prototype={init:function(){(!this.heightOverride||!this.widthOverride)&&this._resetDimensions();var a=this.divHeight,b=this.divWidth,d=this.cropbox,a=glift.displays.bboxFromPts(glift.util.point(0,
0),glift.util.point(b,a)),b=glift.displays.getResizedBox(a,d),d=glift.displays.getLineBox(b,d),e=glift.displays.boardPointsFromLineBox(d,this.intersections);this.divBox=a;this.goBoardBox=b;this.goBoardLineBox=d;this.boardPoints=e;return this},_resetDimensions:function(){var a=glift.displays.bboxFromDiv(this.divId);this.divHeight=a.height();this.divWidth=a.width();return this},_debugDrawAll:function(){var a=Raphael(this.divId,"100%","100%");this.divBox.draw(a,"yellow");this.resizedBox.draw(a,"red");
this.goBoardBox.draw(a,"orange");this.goBoardLineBox.bbox.draw(a,"red");this.goBoardLineBox._debugDrawLines(a,"blue");this.boardPoints._debugDraw(a,"green");this.lineSegments._debugDraw(a,"black")}}})();
(function(){glift.displays.getLineBox=function(a,c){var d=glift.displays.cropbox.OVERFLOW,e=a.width()/c.widthMod(),f=a.height()/c.heightMod(),h=f*d/2,k=e*d/2,l=f*(c.heightMod()-d/2),d=e*(c.widthMod()-d/2),m=a.topLeft().x(),n=a.topLeft().y(),h=glift.displays.bboxFromPts(glift.util.point(k+m,h+n),glift.util.point(d+m,l+n));return new b(h,e,f,c)};var b=function(a,b,d,e){this.bbox=a;this._xSpacing=b;this._ySpacing=d;this.spacing=b;this.extensionBox=e.extBox();this.pointTopLeft=e.cbox().topLeft();this.xPoints=
e.xPoints();this.yPoints=e.yPoints()};b.prototype={_debugDrawLines:function(a,b){for(var d=this.bbox.left(),e=this.bbox.top();d<=this.bbox.right();d+=this.spacing,e+=this.spacing)a.rect(d,e,this.spacing,this.spacing).attr({fill:b,opacity:0.5})}}})();
glift.displays.processOptions=function(b){var a={intersections:19,divId:"glift_display",theme:"DEFAULT",boardRegion:"ALL",displayConfig:{},goBoardBackground:""},c;for(c in b){var d=b[c];switch(c){case "intersections":if("number"==glift.util.typeOf(d)&&0<d)a.intersections=d;else throw"Intersection value : "+c;break;case "theme":if(glift.themes.has(d))a.theme=d;else throw"Unknown theme: "+d;break;case "divId":if(null!==document.getElementById(d))a.divId=d;else throw"Could not find div with id: "+d;
break;case "boardRegion":if(void 0!==glift.enums.boardRegions[d])a.boardRegion=d;else throw"Unknown board region: "+d;break;case "displayConfig":if("object"===glift.util.typeOf(d))a.displayConfig=d;else throw"displayConfig not an object: "+d;break;case "goBoardBackground":if("string"===glift.util.typeOf(d))a.goBoardBackground=d;else throw"goBoardBackground not a string: "+d;}}return a};
glift.displays.getResizedBox=function(b,a){var c=glift.util,d=glift.displays.getCropDimensions(b.width(),b.height(),a),e=d.width(),f=d.height(),h=b.width()-e,k=b.height()-f,l=0===h?0:h/2,m=0===k?0:k/2,n=b.topLeft().x()+l,r=b.topLeft().y()+m,c=glift.displays.bbox(c.point(n,r),e,f);glift.global.debugMode&&(c._debugInfo=function(){return{newDims:d,newWidth:e,newHeight:f,xDiff:h,yDiff:k,xDelta:l,yDelta:m,newLeft:n,newTop:r}});return c};
glift.displays.getCropDimensions=function(b,a,c){var d=a/b;c=c.heightMod()/c.widthMod();var e=a,f=b;d>c?e=b*c:d<c&&(f=a/c);return{height:function(){return e},width:function(){return f}}};glift.displays.board={create:function(b,a,c){return(new glift.displays.board.Display(b,a,c)).draw()}};
glift.displays.board.Display=function(b,a,c){this._objectHistory=[];this._environment=b;this._themeName=a;this._theme=c;this._stones=void 0;this.stones=function(){return this._stones};this._intersections=this._svg=void 0;this.intersections=function(){return this._intersections};this.intersectionPoints=function(){return this._environment.intersections};this.boardPoints=function(){return this._environment.boardPoints};this.divId=function(){return this._environment.divId};this.theme=function(){return this._themeName};
this.boardRegion=function(){return this._environment.boardRegion};this.width=function(){return this._environment.goBoardBox.width()};this.height=function(){return this._environment.goBoardBox.height()}};
glift.displays.board.Display.prototype={init:function(){void 0===this._svg&&(this.destroy(),this._svg=d3.select("#"+this.divId()).style("-webkit-touch-callout","none").style("-webkit-user-select","none").style("-khtml-user-select","none").style("-moz-user-select","moz-none").style("-ms-user-select","none").style("user-select","none").style("cursor","default"),this._svg=d3.select("#"+this.divId()).append("svg").attr("width","100%").attr("height","100%"));this._environment.init();return this},draw:function(){this.init();
var b=glift.displays.board,a=this._environment,c=a.boardPoints,d=this._theme,e=this._svg,f=this.divId();b.initBlurFilter(f,e);b.boardBase(f,e,a.goBoardBox,d);var a=b.lines(f,e,c,d),h=b.starPoints(f,e,c,d),k=b.shadows(f,e,c,d),l=b.stones(f,e,c,d),m=b.markContainer(f,e,c,d),b=b.buttons(f,e,c);this._intersections=glift.displays.board.intersections(f,e,{lineIds:a,starPointIds:h,stoneShadowIds:k,stoneIds:l,markIds:m,buttons:b},c,d);return this},destroy:function(){this.divId()&&d3.select("#"+this.divId()).selectAll("svg").remove();
this._intersections=this._svg=void 0;return this},recreate:function(b){this.destroy();b=glift.displays.processOptions(b);this._environment=glift.displays.environment.get(b);this._themeName=b.theme;this._theme=glift.themes.get(b.theme);return this},redraw:function(){this.draw()}};
glift.displays.board.boardBase=function(b,a,c,d){var e=glift.enums.svgElements.BOARD;b=glift.displays.gui.elementId(b,e);d.board.imagefill&&a.selectAll("goBoardRect").data([e]).enter().append("svg:image").attr("x",c.topLeft().x()).attr("y",c.topLeft().y()).attr("width",c.width()).attr("height",c.height()).attr("xlink:href",d.board.imagefill).attr("preserveAspectRatio","none").attr("id",b);a.selectAll("goBoardRect").data([e]).enter().append("rect").attr("x",c.topLeft().x()+"px").attr("y",c.topLeft().y()+
"px").attr("width",c.width()+"px").attr("height",c.height()+"px").attr("height",c.height()+"px").attr("fill",d.board.imagefill?"none":d.board.fill).attr("stroke",d.board.stroke).attr("stroke-width",d.board["stroke-width"]).attr("id",b);return b};
glift.displays.board.buttons=function(b,a,c){var d={},e=glift.enums.svgElements.BUTTON;a.selectAll(e).data(c.data()).enter().append("svg:rect").attr("x",function(a){return a.coordPt.x()-c.radius}).attr("y",function(a){return a.coordPt.y()-c.radius}).attr("width",c.spacing).attr("height",c.spacing).attr("class",e).attr("opacity",0).attr("fill","red").attr("stroke","red").attr("stone_color","EMPTY").attr("id",function(a){var c=glift.displays.gui.elementId(b,e,a.intPt);return d[a.intPt.hash()]=c});return d};
glift.displays.board.intersections=function(b,a,c,d,e){return new glift.displays.board._Intersections(b,a,c,d,e)};glift.displays.board._Intersections=function(b,a,c,d,e){this.divId=b;this.svg=a;this.theme=e;this.boardPoints=d;this.lineIds=c.lineIds;this.starPointIds=c.starPointIds;this.stoneShadowIds=c.stoneShadowIds;this.stoneIds=c.stoneIds;this.markIds=c.markIds;this.buttons=c.buttons;this.buttonsData=[];for(var f in this.buttons)this.buttonsData.push(glift.util.pointFromString(f))};
glift.displays.board._Intersections.prototype={setStoneColor:function(b,a){var c=b.hash();if(void 0===this.theme.stones[a])throw"Unknown color key ["+a+"]";if(void 0!==this.stoneIds[c]){var d=this.theme.stones[a];this.svg.select("#"+this.stoneIds[c]).attr("fill",d.fill).attr("stroke",d.stroke).attr("stone_color",a).attr("opacity",d.opacity);void 0!==this.stoneShadowIds[c]&&(1===d.opacity?this.svg.select("#"+this.stoneShadowIds[c]).attr("opacity",1):this.svg.select("#"+this.stoneShadowIds[c]).attr("opacity",
0))}return this},addMarkPt:function(b,a,c){glift.displays.board.addMark(this.divId,this.svg,this.boardPoints,this.theme,b,a,c);return this},addMark:function(b,a,c,d){this.addMarkPt(glift.util.point(b,a),c,d);return this},clearMarks:function(){var b=glift.enums.svgElements;this.svg.selectAll("."+b.STARPOINT).attr("opacity",1);this.svg.selectAll("."+b.BOARD_LINE).attr("opacity",1);this.svg.selectAll("."+b.MARK).remove();return this},clearStones:function(){var b=glift.enums.svgElements;this.svg.selectAll("."+
b.STONE).attr("opacity",0).attr("stone_color","EMPTY");this.svg.selectAll("."+b.STONE_SHADOW).attr("opacity",0)},clearAll:function(){this.clearMarks();this.clearStones()},setEvent:function(b,a){this.svg.selectAll("rect."+glift.enums.svgElements.BUTTON).data(this.buttonsData).on(b,function(b){a(b)})}};
glift.displays.board.lines=function(b,a,c,d){var e={},f=glift.enums.svgElements.BOARD_LINE;a.selectAll(f).data(c.data()).enter().append("path").attr("d",function(a){return glift.displays.board.intersectionLine(a,c.radius,c.numIntersections,d)}).attr("stroke",d.lines.stroke).attr("stroke-width",d.lines["stroke-width"]).attr("class",f).attr("stroke-linecap","round").attr("id",function(a){var d=glift.displays.gui.elementId(b,f,a.intPt);return e[a.intPt.hash()]=d});return e};
glift.displays.board.intersectionLine=function(b,a,c){var d=c-1;c=b.coordPt;var e=b.intPt;b=glift.displays.board.svgutil;var f=0===e.y()?c.y():c.y()-a,h=e.y()===d?c.y():c.y()+a,k=0===e.x()?c.x():c.x()-a;a=e.x()===d?c.x():c.x()+a;return b.svgMove(c.x(),f)+" "+b.svgLineAbs(c.x(),h)+" "+b.svgMove(k,c.y())+" "+b.svgLineAbs(a,c.y())};glift.displays.board.markContainer=function(b,a,c,d){b=glift.enums.svgElements.MARK_CONTAINER;a.selectAll(b).data([1]).enter().append("g").attr("class",b);return{}};
glift.displays.board.addMark=function(b,a,c,d,e,f,h){var k=glift.displays.board.svgutil,l=glift.enums.svgElements,m=l.MARK,n=l.STONE,r=l.STARPOINT,q=l.BOARD_LINE,l=l.MARK_CONTAINER,t=glift.enums.marks,p=c.getCoord(e).coordPt;glift.displays.gui.elementId(b,m,e);var x=a.select("#"+glift.displays.gui.elementId(b,n,e)).attr("stone_color"),n=d.stones[x].marks;if("EMPTY"===x&&(f===t.LABEL||f===t.VARIATION_MARKER))a.select("#"+glift.displays.gui.elementId(b,r,e)).attr("opacity",0),a.select("#"+glift.displays.gui.elementId(b,
q,e)).attr("opacity",0);b=c.radius/8;f===t.LABEL||f==t.VARIATION_MARKER?(f===t.VARIATION_MARKER&&(n=n.VARIATION_MARKER),a.select("."+l).append("text").text(h).attr("fill",n.fill).attr("stroke",n.stroke).attr("class",m).attr("text-anchor","middle").attr("dy",".35em").attr("x",p.x()).attr("y",p.y()).attr("font-family",d.stones.marks["font-family"]).attr("font-size",0.7*c.spacing)):f===t.SQUARE?(c=c.radius/1.41421356237,k=c-b,a.select("."+l).append("rect").attr("x",p.x()-k).attr("y",p.y()-k).attr("width",
2*k).attr("height",2*k).attr("fill","none").attr("stroke-width",2).attr("class",m).attr("stroke",n.stroke)):f===t.XMARK?(c=c.radius/1.41421356237,h=c-b,c=p.translate(-1*h,-1*h),d=p.translate(h,-1*h),f=p.translate(-1*h,h),h=p.translate(h,h),a.select("."+l).append("path").attr("d",k.svgMovePt(p)+" "+k.svgLineAbsPt(c)+" "+k.svgMovePt(p)+" "+k.svgLineAbsPt(d)+" "+k.svgMovePt(p)+" "+k.svgLineAbsPt(f)+" "+k.svgMovePt(p)+" "+k.svgLineAbsPt(h)).attr("stroke-width",2).attr("class",m).attr("stroke",n.stroke)):
f===t.CIRCLE?a.select("."+l).append("circle").attr("cx",p.x()).attr("cy",p.y()).attr("r",c.radius/2).attr("fill","none").attr("stroke-width",2).attr("class",m).attr("stroke",n.stroke):f===t.STONE_MARKER?a.select("."+l).append("circle").attr("cx",p.x()).attr("cy",p.y()).attr("r",c.radius/3).attr("class",m).attr("opacity",n.STONE_MARKER.opacity).attr("fill",n.STONE_MARKER.fill):f===t.TRIANGLE&&(f=c.radius-c.radius/5,c=p.translate(0.866025403785*f,0.5*f),d=p.translate(-0.866025403785*f,0.5*f),p=p.translate(0,
-1*f),a.select("."+l).append("path").attr("fill","none").attr("d",k.svgMovePt(p)+" "+k.svgLineAbsPt(d)+" "+k.svgLineAbsPt(c)+" "+k.svgLineAbsPt(p)).attr("stroke-width",2).attr("class",m).attr("stroke",n.stroke));return this};
glift.displays.board.starPoints=function(b,a,c,d){var e=d.starPoints.sizeFraction*c.spacing,f=c.starPoints(),h=glift.enums.svgElements.STARPOINT,k={};a.selectAll(h).data(f).enter().append("circle").attr("cx",function(a){return c.getCoord(a).coordPt.x()}).attr("cy",function(a){return c.getCoord(a).coordPt.y()}).attr("r",e).attr("class",h).attr("fill",d.starPoints.fill).attr("id",function(a){var d=glift.displays.gui.elementId(b,h,a);return k[a.hash()]=d});return k};
glift.displays.board.stones=function(b,a,c,d){var e=glift.enums.svgElements.STONE,f={};a.selectAll(e).data(c.data()).enter().append("circle").attr("cx",function(a){return a.coordPt.x()}).attr("cy",function(a){return a.coordPt.y()}).attr("r",c.radius-0.2).attr("opacity",0).attr("class",glift.enums.svgElements.STONE).attr("stone_color","EMPTY").attr("fill","blue").attr("id",function(a){a=a.intPt;var d=glift.displays.gui.elementId(b,e,a);return f[a.hash()]=d});return f};
glift.displays.board.shadows=function(b,a,c,d){if(void 0===d.stones.shadows)return{};var e=glift.enums.svgElements.STONE_SHADOW,f={};a.selectAll(e).data(c.data()).enter().append("circle").attr("cx",function(a){return a.coordPt.x()+c.radius/7}).attr("cy",function(a){return a.coordPt.y()+c.radius/7}).attr("r",c.radius-0.4).attr("opacity",0).attr("class",e).attr("fill",d.stones.shadows.fill).attr("stroke",d.stones.shadows.stroke).attr("id",function(a){a=a.intPt;var d=glift.displays.gui.elementId(b,e,
a);return f[a.hash()]=d});return f};glift.displays.board.initBlurFilter=function(b,a){a.append("svg:defs").append("svg:filter").attr("id",b+"_svg_blur").append("svg:feGaussianBlur").attr("stdDeviation",2)};
glift.displays.board.svgutil={svgMove:function(b,a){return"M"+b+" "+a},svgMovePt:function(b){return glift.displays.board.svgutil.svgMove(b.x(),b.y())},svgLineRel:function(b,a){return"l"+b+" "+a},svgLineRelPt:function(b){return glift.displays.board.svgutil.svgLineRel(b.x(),b.y())},svgLineAbs:function(b,a){return"L"+b+" "+a},svgLineAbsPt:function(b){return glift.displays.board.svgutil.svgLineAbs(b.x(),b.y())}};
glift.displays.gui={elementId:function(b,a,c){b=b+"_"+a;return void 0!==c?void 0!==c.x?b+"_"+c.x()+"_"+c.y():b+"_"+c.toString():b},splitDiv:function(b,a,c){var d=glift.displays.bboxFromDiv(b),e=0;c?"vertical"!==c&&"horizontal"!==c&&(c="horizontal"):c="horizontal";for(var f=0;f<a.length;f++)e+=a[f];if(1<e||0>e)throw"Percents must sum to a number be between 0 and 1.Was "+e;a.push(1-e);for(var e=[],h="horizontal"===c?d.top():d.left(),d="horizontal"===c?d.height():d.width(),f=0;f<a.length;f++)e.push({id:"glift_internal_div_"+
glift.util.idGenerator.next(),start:h,length:d*a[f]}),h+=d*a[f];for(f=0;f<e.length;f++)$("#"+b).append('<div id="'+e[f].id+'"></div>'),a={width:"horizontal"===c?"100%":e[f].length,height:"horizontal"===c?e[f].length:"100%",position:"absolute"},a["horizontal"===c?"top":"left"]=e[f].start,$("#"+e[f].id).css(a);return e}};
glift.displays.gui.rowCenter=function(b,a,c,d,e,f){var h=b.width()-2*d,k=b.height()-2*c,l=[],m=[],n=0;0>=f&&(f=1E7);for(var r=0;r<a.length;r++){var q=a[r],t=k>h?h/q.width():k/q.height(),p={scale:t},q=q.scale(t);l.push(p);m.push(q);n+=q.width()+e}n-=e;for(r=[];h<n;)p=m.pop(),q=l.pop(),n-=p.width()+e,r.push(q);r=h-n;q=e=p=r/(l.length+1);p>f&&(e=f,q=(r-e*(l.length-1))/2);d=b.left()+d+q;b=b.top()+c;c=[];for(r=0;r<m.length;r++)q=m[r],p=l[r],f=b-q.top(),h=d-q.left(),p.xMove=h,p.yMove=f,c.push(q.translate(h,
f)),d+=q.width()+e;return{transforms:l,bboxes:c}};glift.displays.gui.centerWithin=function(b,a,c,d){var e=b.width()-2*d,f=b.height()-2*c,h=1,h=f/e>a.height()/a.width()?e/a.width():f/a.width();a=a.scale(h);d=b.left()+d;a.width()<e&&(d+=(e-a.width())/2);b=b.top()+c;a.height()<f&&(b+=(f-a.height())/2);f={xMove:d-a.left(),yMove:b-a.top(),scale:h};a=a.translate(f.xMove,f.yMove);return{transform:f,bbox:a}};
(function(){glift.displays.gui.commentBox=function(a,c,d,e,f){return(new b(a,c,d,e,f)).draw()};var b=function(a,b,d,e,f){this.divId=a;this.displayWidth=b;this.boundingWidth=d;this.themeName=e;this.theme=glift.themes.get(e);this.useBoardImage=f;this.commentBoxObj=void 0};b.prototype={draw:function(){this.commentBoxObj=$("#"+this.divId);var a=$("#"+this.divId).height(),b=this.theme.board["stroke-width"];this.commentBoxObj.css({background:"#CCCCFF",border:"1px solid",left:(this.boundingWidth-this.displayWidth)/
2-b,width:this.displayWidth-22+1*b,height:a-22,margin:"auto","font-family":"Baskerville",overflow:"auto",padding:10});return this},setText:function(a){this.commentBoxObj.html("<p>"+a.replace(/\n/g,"<br><p>"))},clearText:function(){this.commentBoxObj.html("")},destroy:function(){this.commentBoxObj.empty()}}})();
(function(){glift.displays.gui.iconBar=function(a){var c=a.divId,d=[],e=0,f=0;themeName="DEFAULT";if(void 0===c)throw"Must define 'divId' as an option";void 0!==a.icons&&(d=a.icons);void 0!==a.vertMargin&&(e=a.vertMargin);void 0!==a.horzMargin&&(f=a.horzMargin);void 0!==a.theme&&(this.themeName=a.theme);for(a=0;a<d.length;a++)if(void 0===glift.displays.gui.icons[d[a]])throw"Icon string undefined in glift.displays.gui.icons ["+d[a]+"]";return(new b(c,themeName,d,e,f)).draw()};var b=function(a,b,d,
e,f){this.divId=a;this.themeName=b;this.theme=glift.themes.get(b);this.iconNames=d;this.vertMargin=e;this.horzMargin=f;this.events={};this.newIconBboxes={};this.svg=void 0;this.tempIconIds=[]};b.prototype={draw:function(){this.destroy();var a=glift.displays.bboxFromDiv(this.divId),b=d3.select("#"+this.divId).append("svg").attr("width","100%").attr("height","100%"),d=glift.displays.gui,e=[],f=[],h=[],k=glift.util.point;this.svg=b;for(var l=0;l<this.iconNames.length;l++){var m=d.icons[this.iconNames[l]];
f.push(m.string);e.push(glift.displays.bboxFromPts(k(m.bbox.x,m.bbox.y),k(m.bbox.x2,m.bbox.y2)));h.push(l)}for(var n=glift.displays.gui.rowCenter(a,e,this.vertMargin,this.horzMargin,0,0),l=0;l<n.bboxes.length;l++)this.newIconBboxes[this.iconNames[l]]=n.bboxes[l];var r=this;b.selectAll("icons").data(h).enter().append("path").attr("d",function(a){return f[a]}).attr("fill",this.theme.icons.DEFAULT.fill).attr("id",function(a){return r.iconId(r.iconNames[a])}).attr("transform",function(a){return glift.displays.gui.scaleAndMoveString(n.bboxes[a],
n.transforms[a])});var q=n.bboxes;b.selectAll("buttons").data(h).enter().append("rect").attr("x",function(a){return q[a].topLeft().x()}).attr("y",function(a){return q[a].topLeft().y()}).attr("width",function(a){return q[a].width()}).attr("height",function(a){return q[a].height()}).attr("fill","blue").attr("opacity",0).attr("_icon",function(a){return r.iconNames[a]}).attr("id",function(a){return r.buttonId(r.iconNames[a])});return this},addTempIcon:function(a,b,d){var e=glift.displays.gui.icons[a],
f=glift.displays.bboxFromPts(glift.util.point(e.bbox.x,e.bbox.y),glift.util.point(e.bbox.x2,e.bbox.y2)),h=this.iconId(a);b=glift.displays.gui.centerWithin(b,f,2,2);this.svg.append("path").attr("d",e.string).attr("fill",d).attr("id",this.iconId(a)).attr("transform",glift.displays.gui.scaleAndMoveString(b.bbox,b.transform));this.tempIconIds.push(h);return this},destroyTempIcons:function(){for(var a=0;a<this.tempIconIds.length;a++)this.svg.select("#"+this.tempIconIds[a]).remove();this.tempIconIds=[];
return this},iconId:function(a){return glift.displays.gui.elementId(this.divId,glift.enums.svgElements.ICON,a)},buttonId:function(a){return glift.displays.gui.elementId(this.divId,glift.enums.svgElements.BUTTON,a)},setEvent:function(a,b,d){var e=this;this.events[b]=d;d3.select("#"+e.buttonId(b)).on(a,function(){d(e.getIcon(b))});return this},forceEvent:function(a){if(void 0!==this.events[a])this.events[a]();return this},setHover:function(a,b,d){this.setEvent("mouseover",a,b);this.setEvent("mouseout",
a,d)},getIcon:function(a){return{name:a,iconId:this.iconId(a),newBbox:this.newIconBboxes[a]}},forEachIcon:function(a){for(var b=0;b<this.iconNames.length;b++)a(this.getIcon(this.iconNames[b]))},redraw:function(){this.destroy();this.draw()},destroy:function(){this.divId&&d3.select("#"+this.divId).selectAll("svg").remove();this.events={};return this}}})();
glift.displays.gui.icons={cross:{string:"M24.778,21.419 19.276,15.917 24.777,10.415 21.949,7.585 16.447,13.087 10.945,7.585 8.117,10.415 13.618,15.917 8.116,21.419 10.946,24.248 16.447,18.746 21.948,24.248z",bbox:{x:8.116,y:7.585,x2:24.778,y2:24.248,width:16.662,height:16.663}},check:{string:"M2.379,14.729 5.208,11.899 12.958,19.648 25.877,6.733 28.707,9.561 12.958,25.308z",bbox:{x:2.379,y:6.733,x2:28.707,y2:25.308,width:26.328,height:18.575}},refresh:{string:"M24.083,15.5c-0.009,4.739-3.844,8.574-8.583,8.583c-4.741-0.009-8.577-3.844-8.585-8.583c0.008-4.741,3.844-8.577,8.585-8.585c1.913,0,3.665,0.629,5.09,1.686l-1.782,1.783l8.429,2.256l-2.26-8.427l-1.89,1.89c-2.072-1.677-4.717-2.688-7.587-2.688C8.826,3.418,3.418,8.826,3.416,15.5C3.418,22.175,8.826,27.583,15.5,27.583S27.583,22.175,27.583,15.5H24.083z",
bbox:{x:3.416,y:3.415,x2:27.583,y2:27.583,width:24.167,height:24.168}},undo:{string:"M12.981,9.073V6.817l-12.106,6.99l12.106,6.99v-2.422c3.285-0.002,9.052,0.28,9.052,2.269c0,2.78-6.023,4.263-6.023,4.263v2.132c0,0,13.53,0.463,13.53-9.823C29.54,9.134,17.952,8.831,12.981,9.073z",bbox:{x:0.875,y:6.817,x2:29.54,y2:27.042158,width:28.665,height:20.225158}},"chevron-right":{string:"M10.129,22.186 16.316,15.999 10.129,9.812 13.665,6.276 23.389,15.999 13.665,25.725z",bbox:{x:10.129,y:6.276,x2:23.389,y2:25.725,
width:13.26,height:19.449}},"chevron-left":{string:"M21.871,9.814 15.684,16.001 21.871,22.188 18.335,25.725 8.612,16.001 18.335,6.276z",bbox:{x:8.612,y:6.276,x2:21.871,y2:25.725,width:13.259,height:19.449}},"small-gear":{string:"M31.229,17.736c0.064-0.571,0.104-1.148,0.104-1.736s-0.04-1.166-0.104-1.737l-4.377-1.557c-0.218-0.716-0.504-1.401-0.851-2.05l1.993-4.192c-0.725-0.91-1.549-1.734-2.458-2.459l-4.193,1.994c-0.647-0.347-1.334-0.632-2.049-0.849l-1.558-4.378C17.165,0.708,16.588,0.667,16,0.667s-1.166,0.041-1.737,0.105L12.707,5.15c-0.716,0.217-1.401,0.502-2.05,0.849L6.464,4.005C5.554,4.73,4.73,5.554,4.005,6.464l1.994,4.192c-0.347,0.648-0.632,1.334-0.849,2.05l-4.378,1.557C0.708,14.834,0.667,15.412,0.667,16s0.041,1.165,0.105,1.736l4.378,1.558c0.217,0.715,0.502,1.401,0.849,2.049l-1.994,4.193c0.725,0.909,1.549,1.733,2.459,2.458l4.192-1.993c0.648,0.347,1.334,0.633,2.05,0.851l1.557,4.377c0.571,0.064,1.148,0.104,1.737,0.104c0.588,0,1.165-0.04,1.736-0.104l1.558-4.377c0.715-0.218,1.399-0.504,2.049-0.851l4.193,1.993c0.909-0.725,1.733-1.549,2.458-2.458l-1.993-4.193c0.347-0.647,0.633-1.334,0.851-2.049L31.229,17.736zM16,20.871c-2.69,0-4.872-2.182-4.872-4.871c0-2.69,2.182-4.872,4.872-4.872c2.689,0,4.871,2.182,4.871,4.872C20.871,18.689,18.689,20.871,16,20.871z",
bbox:{x:0.667,y:0.667,x2:31.333,y2:31.333,width:30.666,height:30.666}},"question-bubble":{string:"M16,4.938c-7.732,0-14,4.701-14,10.5c0,1.981,0.741,3.833,2.016,5.414L2,25.272l5.613-1.44c2.339,1.316,5.237,2.106,8.387,2.106c7.732,0,14-4.701,14-10.5S23.732,4.938,16,4.938zM16.982,21.375h-1.969v-1.889h1.969V21.375zM16.982,17.469v0.625h-1.969v-0.769c0-2.321,2.641-2.689,2.641-4.337c0-0.752-0.672-1.329-1.553-1.329c-0.912,0-1.713,0.672-1.713,0.672l-1.12-1.393c0,0,1.104-1.153,3.009-1.153c1.81,0,3.49,1.121,3.49,3.009C19.768,15.437,16.982,15.741,16.982,17.469z",
bbox:{x:2,y:4.938,x2:30,y2:25.938,width:28,height:21}},roadmap:{string:"M23.188,3.735c0-0.975-0.789-1.766-1.766-1.766s-1.766,0.791-1.766,1.766s1.766,4.267,1.766,4.267S23.188,4.71,23.188,3.735zM20.578,3.734c0-0.466,0.378-0.843,0.844-0.843c0.467,0,0.844,0.377,0.844,0.844c0,0.466-0.377,0.843-0.844,0.843C20.956,4.578,20.578,4.201,20.578,3.734zM25.281,18.496c-0.562,0-1.098,0.046-1.592,0.122L11.1,13.976c0.199-0.181,0.312-0.38,0.312-0.59c0-0.108-0.033-0.213-0.088-0.315l8.41-2.239c0.459,0.137,1.023,0.221,1.646,0.221c1.521,0,2.75-0.485,2.75-1.083c0-0.599-1.229-1.083-2.75-1.083s-2.75,0.485-2.75,1.083c0,0.069,0.021,0.137,0.054,0.202L9.896,12.2c-0.633-0.188-1.411-0.303-2.265-0.303c-2.088,0-3.781,0.667-3.781,1.49c0,0.823,1.693,1.489,3.781,1.489c0.573,0,1.11-0.054,1.597-0.144l11.99,4.866c-0.19,0.192-0.306,0.401-0.306,0.623c0,0.188,0.096,0.363,0.236,0.532L8.695,25.415c-0.158-0.005-0.316-0.011-0.477-0.011c-3.241,0-5.87,1.037-5.87,2.312c0,1.276,2.629,2.312,5.87,2.312c3.241,0,5.87-1.034,5.87-2.312c0-0.22-0.083-0.432-0.229-0.633l10.265-5.214c0.37,0.04,0.753,0.066,1.155,0.066c2.414,0,4.371-0.771,4.371-1.723C29.65,19.268,27.693,18.496,25.281,18.496z",
bbox:{x:2.348,y:1.969,x2:29.65,y2:30.028,width:27.302,height:28.059}},play:{string:"M6.684,25.682L24.316,15.5L6.684,5.318V25.682z",bbox:{x:6.684,y:5.318,x2:24.316,y2:25.682,width:17.632,height:20.364}},end:{string:"M21.167,5.5,21.167,13.681,6.684,5.318,6.684,25.682,21.167,17.318,21.167,25.5,25.5,25.5,25.5,5.5z",bbox:{x:6.684,y:5.318,x2:25.5,y2:25.682,width:18.816,height:20.364}},start:{string:"M24.316,5.318,9.833,13.682,9.833,5.5,5.5,5.5,5.5,25.5,9.833,25.5,9.833,17.318,24.316,25.682z",bbox:{x:5.5,
y:5.318,x2:24.316,y2:25.682,width:18.816,height:20.364}},arrowup:{string:"M23.963,20.834L17.5,9.64c-0.825-1.429-2.175-1.429-3,0L8.037,20.834c-0.825,1.429-0.15,2.598,1.5,2.598h12.926C24.113,23.432,24.788,22.263,23.963,20.834z",bbox:{x:7.684895,y:8.56825,x2:24.315105,y2:23.432,width:16.630209,height:14.86375}},arrowright:{string:"M11.166,23.963L22.359,17.5c1.43-0.824,1.43-2.175,0-3L11.166,8.037c-1.429-0.826-2.598-0.15-2.598,1.5v12.926C8.568,24.113,9.737,24.789,11.166,23.963z",bbox:{x:8.568,y:7.684457,
x2:23.4315,y2:24.315543,width:14.8635,height:16.631086}},arrowleft:{string:"M20.834,8.037L9.641,14.5c-1.43,0.824-1.43,2.175,0,3l11.193,6.463c1.429,0.826,2.598,0.15,2.598-1.5V9.537C23.432,7.887,22.263,7.211,20.834,8.037z",bbox:{x:8.5685,y:7.684457,x2:23.432,y2:24.315543,width:14.8635,height:16.631086}},detour:{string:"M29.342,15.5l-7.556-4.363v2.614H18.75c-1.441-0.004-2.423,1.002-2.875,1.784c-0.735,1.222-1.056,2.561-1.441,3.522c-0.135,0.361-0.278,0.655-0.376,0.817c-1.626,0-0.998,0-2.768,0c-0.213-0.398-0.571-1.557-0.923-2.692c-0.237-0.676-0.5-1.381-1.013-2.071C8.878,14.43,7.89,13.726,6.75,13.75H2.812v3.499c0,0,0.358,0,1.031,0h2.741c0.008,0.013,0.018,0.028,0.029,0.046c0.291,0.401,0.634,1.663,1.031,2.888c0.218,0.623,0.455,1.262,0.92,1.897c0.417,0.614,1.319,1.293,2.383,1.293H11c2.25,0,1.249,0,3.374,0c0.696,0.01,1.371-0.286,1.809-0.657c1.439-1.338,1.608-2.886,2.13-4.127c0.218-0.608,0.453-1.115,0.605-1.314c0.006-0.01,0.012-0.018,0.018-0.025h2.85v2.614L29.342,15.5zM10.173,14.539c0.568,0.76,0.874,1.559,1.137,2.311c0.04,0.128,0.082,0.264,0.125,0.399h2.58c0.246-0.697,0.553-1.479,1.005-2.228c0.252-0.438,0.621-0.887,1.08-1.272H9.43C9.735,14.003,9.99,14.277,10.173,14.539z",
bbox:{x:2.812,y:11.137,x2:29.342,y2:23.37325,width:26.53,height:12.23625}},checkbox:{string:"M26,27.5H6c-0.829,0-1.5-0.672-1.5-1.5V6c0-0.829,0.671-1.5,1.5-1.5h20c0.828,0,1.5,0.671,1.5,1.5v20C27.5,26.828,26.828,27.5,26,27.5zM7.5,24.5h17v-17h-17V24.5z",bbox:{x:4.5,y:4.5,x2:27.5,y2:27.5,width:23,height:23}},edit:{string:"M27.87,7.863L23.024,4.82l-7.889,12.566l4.842,3.04L27.87,7.863zM14.395,21.25l-0.107,2.855l2.527-1.337l2.349-1.24l-4.672-2.936L14.395,21.25zM29.163,3.239l-2.532-1.591c-0.638-0.401-1.479-0.208-1.882,0.43l-0.998,1.588l4.842,3.042l0.999-1.586C29.992,4.481,29.802,3.639,29.163,3.239zM25.198,27.062c0,0.275-0.225,0.5-0.5,0.5h-19c-0.276,0-0.5-0.225-0.5-0.5v-19c0-0.276,0.224-0.5,0.5-0.5h13.244l1.884-3H5.698c-1.93,0-3.5,1.57-3.5,3.5v19c0,1.93,1.57,3.5,3.5,3.5h19c1.93,0,3.5-1.57,3.5-3.5V11.097l-3,4.776V27.062z",
bbox:{x:2.198,y:1.4388,x2:29.80125,y2:30.562,width:27.60325,height:29.12316}}};glift.displays.gui.scaleAndMoveString=function(b,a){return"translate("+a.xMove+","+a.yMove+") scale("+a.scale+")"};glift.rules={};
(function(){glift.rules.goban={getInstance:function(a){return new b(a||19)},getFromMoveTree:function(a,c){var f=new b(a.getIntersections()),h=a.getTreeFromRoot();c=c||[];var k=[];f.loadStonesFromMovetree(h);for(var l=0;l<c.length;l++)h.moveDown(c[l]),k.push(f.loadStonesFromMovetree(h));return{goban:f,captures:k}}};var b=function(a){if(0>=a)throw"Intersections must be greater than 0";this.ints=a;for(var b=[],c=0;c<a;c++){for(var h=[],k=0;k<a;k++)h[k]=glift.enums.states.EMPTY;b[c]=h}this.stones=b};
b.prototype={intersections:function(){return this.ints},getStone:function(a){return this.stones[a.y()][a.x()]},getAllPlacedStones:function(){for(var a=[],b=0;b<this.stones.length;b++)for(var c=this.stones[b],h=0;h<c.length;h++){var k=glift.util.point(h,b),l=this.getStone(k);(l===glift.enums.states.BLACK||l===glift.enums.states.WHITE)&&a.push({point:k,color:l})}return a},placeable:function(a,b){return this.inBounds(a)&&this.getStone(a)===glift.enums.states.EMPTY},outBounds:function(a){return glift.util.outBounds(a.x(),
this.ints)||glift.util.outBounds(a.y(),this.ints)},inBounds:function(a){return glift.util.inBounds(a.x(),this.ints)&&glift.util.inBounds(a.y(),this.ints)},clearStone:function(a){this._setColor(a,glift.enums.states.EMPTY)},clearSome:function(a){for(var b=0;b<a.length;b++)this.clearStone(a[b])},_setColor:function(a,b){this.stones[a.y()][a.x()]=b},addStone:function(b,e){if(!glift.util.colors.isLegalColor(e))throw"Unknown color: "+e;if(this.outBounds(b)||!this.placeable(b))return new c(!1);this._setColor(b,
e);var f=new a,h=glift.util.colors.oppositeColor(e);this._getCaptures(f,glift.util.point(b.x()+1,b.y()),h);this._getCaptures(f,glift.util.point(b.x()-1,b.y()),h);this._getCaptures(f,glift.util.point(b.x(),b.y()-1),h);this._getCaptures(f,glift.util.point(b.x(),b.y()+1),h);if(0>=f.numCaptures&&(this._getCaptures(f,b,e),0<f.numCaptures))return this.clearStone(b),new c(!1);f=f.getCaptures();this.clearSome(f);return new c(!0,f)},_getCaptures:function(a,b,c){this._findConnected(a,b,c);0>=a.liberties&&a.consideringToCaptures();
a.clearExceptCaptures()},_findConnected:function(a,b,c){var h=glift.util;if(!(void 0!==a.seen[b.hash()]||this.outBounds(b))){a.seen[b.hash()]=!0;var k=this.getStone(b);if(k===glift.enums.states.EMPTY)a.liberties++;else if(k!==h.colors.oppositeColor(c))if(k===c)a.considering.push(b),this._findConnected(a,h.point(b.x()+1,b.y()),c),this._findConnected(a,h.point(b.x()-1,b.y()),c),this._findConnected(a,h.point(b.x(),b.y()+1),c),this._findConnected(a,h.point(b.x(),b.y()-1),c);else throw"Unknown color error: "+
k;}},loadStonesFromMovetree:function(a){for(var b=[glift.enums.states.BLACK,glift.enums.states.WHITE],c={BLACK:[],WHITE:[]},h=0;h<b.length;h++)for(var k=b[h],l=a.properties().getPlacementsAsPoints(k),m=0;m<l.length;m++)this._loadStone({point:l[m],color:k},c);this._loadStone(a.properties().getMove(),c);return c},_loadStone:function(a,b){if(a!==glift.util.none){var c=this.addStone(a.point,a.color);if(c.successful)for(var h=glift.util.colors.oppositeColor(a.color),k=0;k<c.captures.length;k++)b[h].push(c.captures[k])}},
unloadStones:function(a,b){for(var c in a)for(var h=0;h<a[c].length;h++)this.clearStone(a[c][h]);for(c in b)for(h=0;h<b[c].length;h++)this.addStone(b[c][h],c)},_debug:function(){glift.util.logz(this.stones)}};var a=function(){this.toCapture={};this.numCaptures=0;this.considering=[];this.seen={};this.liberties=0};a.prototype={clearExceptCaptures:function(){this.considering=[];this.seen={};this.liberties=0},consideringToCaptures:function(){for(var a=0;a<this.considering.length;a++){var b=this.considering[a];
void 0===this.toCapture[b.hash()]&&(this.toCapture[b.hash()]=!0,this.numCaptures++)}},addLiberties:function(a){this.liberties+=a},addSeen:function(a){this.seen[a.hash()]=!0},getCaptures:function(){var a=[],b;for(b in this.toCapture)a.push(glift.util.pointFromHash(b));return a}};var c=function(a,b){this.captures=(this.successful=a)?b:[]}})();
(function(){glift.rules.intersections={propertiesToMarks:{CR:glift.enums.marks.CIRCLE,LB:glift.enums.marks.LABEL,MA:glift.enums.marks.XMARK,SQ:glift.enums.marks.SQUARE,TR:glift.enums.marks.TRIANGLE},basePropertyData:function(b){var a={stones:{WHITE:[],BLACK:[],EMPTY:[]},marks:{},comment:glift.util.none,lastMove:glift.util.none,nextMoves:[],captures:[]};a.comment=b.properties().getComment();a.lastMove=b.getLastMove();a.marks=glift.rules.intersections.getCurrentMarks(b);a.nextMoves=b.nextMoves();return a},
getFullBoardData:function(b,a){for(var c=glift.rules.intersections.basePropertyData(b),d=a.getAllPlacedStones(),e=0;e<d.length;e++){var f=d[e];c.stones[f.color].push(f.point)}return c},nextBoardData:function(b,a){var c=glift.rules.intersections.basePropertyData(b);c.stones=b.properties().getAllStones();c.stones.EMPTY=[];for(var d in a)for(var e=0;e<a[d].length;e++)c.stones.EMPTY.push(a[d][e]);return c},previousBoardData:function(b,a,c){b=glift.rules.intersections.basePropertyData(b);b.stones=c;b.stones.EMPTY=
[];for(var d in a)for(c=0;c<a[d].length;c++)b.stones.EMPTY.push(a[d][c]);return b},getCurrentMarks:function(b){var a={},c;for(c in glift.rules.intersections.propertiesToMarks){var d=glift.rules.intersections.propertiesToMarks[c];if(b.properties().contains(c)){for(var e=[],f=b.properties().get(c),h=0;h<f.length;h++)c===glift.sgf.allProperties.LB?e.push(glift.sgf.convertFromLabelData(f[h])):e.push(glift.util.pointFromSgfCoord(f[h]));a[d]=e}}return a}}})();
(function(){glift.rules.movenode=function(a,d){return new b(a,d)};var b=function(a,b){this._properties=a||glift.rules.properties();this.children=b||[];this._nodeId={nodeNum:0,varNum:0}};b.prototype={properties:function(){return this._properties},_setNodeId:function(a,b){this._nodeId={nodeNum:a,varNum:b};return this},getNodeNum:function(){return this._nodeId.nodeNum},getVarNum:function(){return this._nodeId.varNum},numChildren:function(){return this.children.length},addChild:function(){this.children.push(glift.rules.movenode()._setNodeId(this.getNodeNum()+
1,this.numChildren()));return this},getChild:function(a){return void 0===a?this.children[0]:this.children[a]},renumber:function(){a(this,this._nodeId.nodeNum,this._nodeId.varNum);return this}};var a=function(b,d,e){b._setNodeId(d,e);for(e=0;e<b.children.length;e++)a(b.children[e],d+1,e);return b}})();
(function(){var b=glift.util,a=glift.enums;glift.rules.movetree={getInstance:function(a){return(new c(glift.rules.movenode())).setIntersections(a||19)},getFromSgf:function(a,b){b=b||[];if(void 0===a||""===a)return glift.rules.movetree.getInstance(19);for(var f=new c(glift.sgf.parser.parse($.trim(a))),h=0;h<b.length;h++)f.moveDown(b[h]);return f},getFromNode:function(a){return new c(a)},searchMoveTreeDFS:function(a,b){b(a);for(var c=0;c<a.node().numChildren();c++)glift.rules.movetree.searchMoveTreeDFS(a.moveDown(c),
b);a.moveUp()}};var c=function(a){this._nodeHistory=[];this._nodeHistory.push(a)};c.prototype={getTreeFromRoot:function(){return glift.rules.movetree.getFromNode(this._nodeHistory[0])},node:function(){return this._nodeHistory[this._nodeHistory.length-1]},properties:function(){return this.node().properties()},findNextMove:function(a,c){for(var f=this.node().children,h=glift.sgf.colorToToken(c),k={},l=0;l<f.length;l++){var m=f[l];m.properties().contains(h)&&(k[m.properties().getAsPoint(h).hash()]=m.getVarNum())}return void 0!==
k[a.hash()]?k[a.hash()]:b.none},getLastMove:function(){return this.properties().getMove()},nextMoves:function(){for(var a=this.node(),b=[],c=0;c<a.numChildren();c++){var h=a.getChild(c).properties().getMove();h!==glift.util.none&&b.push(h)}return b},getCurrentPlayer:function(){var c=this.properties().getMove();return c===b.none?a.states.BLACK:c.color===a.states.BLACK?a.states.WHITE:a.states.BLACK},moveDown:function(a){a=void 0===a?0:a;void 0!==this.node().getChild(a)&&(a=this.node().getChild(a),this._nodeHistory.push(a));
return this},moveUp:function(){1<this._nodeHistory.length&&this._nodeHistory.pop();return this},moveToRoot:function(){this._nodeHistory=this._nodeHistory.slice(0,1);return this},addNode:function(){this.node().addChild();this.moveDown(this.node().numChildren()-1);return this},deleteCurrentNode:function(){throw"Unfinished";},recurse:function(a){glift.rules.movetree.searchMoveTreeDFS(this,a)},recurseFromRoot:function(a){glift.rules.movetree.searchMoveTreeDFS(this.getTreeFromRoot(),a)},toSgf:function(){for(var a in this.getAllProps());
},debugLog:function(a){void 0===a&&(a="  ");glift.util.logz(a+this.node(b).getVarNum()+"-"+this.node(b).getNodeNum());for(var b=0;b<this.node().numChildren();b++)this.moveDown(b),this.debugLog(a),this.moveUp()},setIntersections:function(a){var b=this.getTreeFromRoot(),c=glift.sgf.allProperties;b.properties().contains(c.SZ)||this.properties().add(c.SZ,a+"");return this},getIntersections:function(){var a=this.getTreeFromRoot(),b=glift.sgf.allProperties;if(a.node().properties().contains(b.SZ))return parseInt(a.node().properties().get(b.SZ))},
isCorrectPosition:function(){var a=glift.enums.problemResults;if(this.properties().isCorrect())return a.CORRECT;for(var b=glift.rules.treepath.flattenMoveTree(this),c={},h=0;h<b.length;h++){for(var k=b[h],l=glift.rules.movetree.getFromNode(this.node()),m=!1,n=0;n<k.length;n++)l.moveDown(k[n]),l.properties().isCorrect()&&(m=!0);m?c[a.CORRECT]=!0:c[a.INCORRECT]=!0}return c[a.CORRECT]&&!c[a.INCORRECT]?a.CORRECT:c[a.CORRECT]&&c[a.INCORRECT]?a.INDETERMINATE:a.INCORRECT}}})();
(function(){var b=glift.util,a=glift.enums;glift.rules.properties=function(a){return new c(a)};var c=function(a){this.propMap=void 0===a?{}:a};c.prototype={add:function(a,c){if(void 0===glift.sgf.allProperties[a])throw"Can't add undefined properties";"string"!==b.typeOf(c)&&"array"!==b.typeOf(c)&&(c=c.toString());c="string"===b.typeOf(c)?[c]:c;this.contains(a)?this.propMap[a]=this.get(a).concat(c):this.propMap[a]=c;return this},get:function(a){if(void 0===glift.sgf.allProperties[a])return b.debugl("attempted to retrieve a property that is not part of the SGF Spec: "+
a),b.none;if(void 0!==this.propMap[a])return this.propMap[a];b.debugl("no property: "+a+" exists for the current move");return b.none},getDatum:function(a,c){c=void 0!==c&&"number"===typeof c&&0<=c?c:0;var f=this.get(a);return f!==b.none&&1<=f.length?f[c]:b.none},getAsPoint:function(a,c){var f=this.getDatum(a,c);return f===b.none?f:glift.util.pointFromSgfCoord(f)},contains:function(a){return this.get(a)!==b.none},remove:function(a){if(this.contains(a)){var c=this.get(a);delete this.propMap[a];return c}return b.none},
replace:function(a,b){this.propMap[a]=b},getPlacementsAsPoints:function(b){var c="";b===a.states.BLACK?c=glift.sgf.allProperties.AB:b===a.states.WHITE&&(c=glift.sgf.allProperties.AW);return""===c||!this.contains(c)?[]:glift.sgf.allSgfCoordsToPoints(this.get(c))},getComment:function(){return this.contains("C")?this.getDatum("C"):b.none},getMove:function(){return this.contains("B")?{color:a.states.BLACK,point:this.getAsPoint("B")}:this.contains("W")?{color:a.states.WHITE,point:this.getAsPoint("W")}:
b.none},isCorrect:function(){return this.contains("GB")?!0:!1},getAllStones:function(){var a=glift.enums.states,c={},f=a.WHITE;c[a.BLACK]=this.getPlacementsAsPoints(a.BLACK);c[f]=this.getPlacementsAsPoints(a.WHITE);a=this.getMove();a!=b.none&&c[a.color].push(a.point);return c}}})();
glift.rules.treepath={parseInitPosition:function(b){if(void 0===b)return[];if("number"===glift.util.typeOf(b))b=""+b;else{if("array"===glift.util.typeOf(b))return b;if("string"!==glift.util.typeOf(b))return[]}var a=[],c=0;b=b.split("-");for(var d=0;d<b.length;d++){for(var e=b[d].split("."),f=0;f<e[0]-c;f++)a.push(0);c=e[0];for(f=1;f<e.length;f++)a.push(parseInt(e[f])),c++}return a},flattenMoveTree:function(b){for(var a=[],c=0;c<b.node().numChildren();c++){b.moveDown(c);var d=glift.rules.treepath._flattenMoveTree(b,
[]);b.moveUp();for(var e=0;e<d.length;e++)a.push(d[e])}return a},_flattenMoveTree:function(b,a){void 0===a&&(a=[]);a.push(b.node().getVarNum());for(var c=[],d=0;d<b.node().numChildren();d++){b.moveDown(d);var e=glift.rules.treepath._flattenMoveTree(b,a.slice()),c=c.concat(e);b.moveUp(d)}0==c.length&&c.push(a);return c}};
glift.sgf={colorToToken:function(b){if(b===glift.enums.states.WHITE)return"W";if(b===glift.enums.states.BLACK)return"B";throw"Unknown color-to-token conversion for: "+b;},allSgfCoordsToPoints:function(b){for(var a=[],c=0;c<b.length;c++)a.push(glift.util.pointFromSgfCoord(b[c]));return a},convertFromLabelData:function(b){b=b.split(":");return{point:glift.util.pointFromSgfCoord(b[0]),value:b[1]}},convertFromLabelArray:function(b){for(var a=[],c=0;c<b.length;c++)a.push(glift.sgf.convertFromLabelData(b[c]));
return a},pointToSgfCoord:function(b){return String.fromCharCode(b.x()+97)+String.fromCharCode(b.y()+97)}};
glift.sgf.allProperties={AB:"AB",AE:"AE",AN:"AN",AP:"AP",AR:"AR",AS:"AS",AW:"AW",B:"B",BL:"BL",BM:"BM",BR:"BR",BS:"BS",BT:"BT",C:"C",CA:"CA",CH:"CH",CP:"CP",CR:"CR",DD:"DD",DM:"DM",DO:"DO",DT:"DT",EL:"EL",EV:"EV",EX:"EX",FF:"FF",FG:"FG",GB:"GB",GC:"GC",GM:"GM",GN:"GN",GW:"GW",HA:"HA",HO:"HO",ID:"ID",IP:"IP",IT:"IT",IY:"IY",KM:"KM",KO:"KO",L:"L",LB:"LB",LN:"LN",LT:"LT",M:"M",MA:"MA",MN:"MN",N:"N",OB:"OB",OM:"OM",ON:"ON",OP:"OP",OT:"OT",OV:"OV",OW:"OW",PB:"PB",PC:"PC",PL:"PL",PM:"PM",PW:"PW",RE:"RE",
RG:"RG",RO:"RO",RU:"RU",SC:"SC",SE:"SE",SI:"SI",SL:"SL",SO:"SO",SQ:"SQ",ST:"ST",SU:"SU",SZ:"SZ",TB:"TB",TC:"TC",TE:"TE",TM:"TM",TR:"TR",TW:"TW",UC:"UC",US:"US",V:"V",VW:"VW",W:"W",WL:"WL",WR:"WR",WS:"WS",WT:"WT"};
glift.sgf.parser=function(){var b={parse:function(a,b){function d(a){var b=a.charCodeAt(0);if(255>=b){a="x";var c=2}else a="u",c=4;a="\\"+a;for(var d=b.toString(16).toUpperCase(),b=d,c=c-d.length,d=0;d<c;d++)b="0"+b;return a+b}function e(a){return'"'+a.replace(/\\/g,"\\\\").replace(/"/g,'\\"').replace(/\r/g,"\\r").replace(/\n/g,"\\n").replace(/[\x80-\uFFFF]/g,d)+'"'}function f(a){g<w||(g>w&&(w=g,y=[]),y.push(a))}function h(){var b="Variations@"+g,c=u[b];if(c)return g=c.nextPos,c.result;var d=c=g;
if("("===a.substr(g,1)){var e="(";g+=1}else e=null,s&&f('"("');if(null!==e){var h=l();if(null!==h){if(")"===a.substr(g,1)){var m=")";g+=1}else m=null,s&&f('")"');if(null!==m){var n=p(),n=null!==n?n:"";if(null!==n){if("("===a.substr(g,1)){var q="(";g+=1}else q=null,s&&f('"("');if(null!==q){var r=l();if(null!==r){if(")"===a.substr(g,1)){var t=")";g+=1}else t=null,s&&f('")"');if(null!==t){var v=p(),v=null!==v?v:"";if(null!==v){var w=k();null!==w?e=[e,h,m,n,q,r,t,v,w]:(e=null,g=d)}else e=null,g=d}else e=
null,g=d}else e=null,g=d}else e=null,g=d}else e=null,g=d}else e=null,g=d}else e=null,g=d}else e=null,g=d;d=null!==e?[e[1],e[5]].concat(e[8]):null;null===d&&(d=null,g=c);null!==d?c=d:(c=g,d=l(),d=null!==d?void 0===d?[]:[d]:null,null===d&&(d=null,g=c),c=null!==d?d:null);u[b]={nextPos:g,result:c};return c}function k(){var b="MoreVars@"+g,c=u[b];if(c)return g=c.nextPos,c.result;var d=c=g;if("("===a.substr(g,1)){var e="(";g+=1}else e=null,s&&f('"("');if(null!==e){var h=l();if(null!==h){if(")"===a.substr(g,
1)){var m=")";g+=1}else m=null,s&&f('")"');if(null!==m){var n=p(),n=null!==n?n:"";if(null!==n){var q=k();null!==q?e=[e,h,m,n,q]:(e=null,g=d)}else e=null,g=d}else e=null,g=d}else e=null,g=d}else e=null,g=d;d=null!==e?[e[1]].concat(e[4]):null;null===d&&(d=null,g=c);null!==d?c=d:(c=g,""===a.substr(g,0)?(d="",g+=0):(d=null,s&&f('""')),d=null!==d?[]:null,null===d&&(d=null,g=c),c=null!==d?d:null);u[b]={nextPos:g,result:c};return c}function l(){var b="Moves@"+g,c=u[b];if(c)return g=c.nextPos,c.result;var d=
c=g;if(";"===a.substr(g,1)){var e=";";g+=1}else e=null,s&&f('";"');if(null!==e){var k=m();if(null!==k){var l=h();null!==l?e=[e,k,l]:(e=null,g=d)}else e=null,g=d}else e=null,g=d;d=null!==e?glift.rules.movenode(glift.rules.properties(e[1]),e[2]):null;null===d&&(d=null,g=c);null!==d?c=d:(c=g,""===a.substr(g,0)?(d="",g+=0):(d=null,s&&f('""')),d=null!==d?void 0:null,null===d&&(d=null,g=c),c=null!==d?d:null);u[b]={nextPos:g,result:c};return c}function m(){var b="Tokens@"+g,c=u[b];if(c)return g=c.nextPos,
c.result;var d=c=g,e=t();if(null!==e){if("["===a.substr(g,1)){var h="[";g+=1}else h=null,s&&f('"["');if(null!==h){var k=r();if(null!==k){if("]"===a.substr(g,1)){var l="]";g+=1}else l=null,s&&f('"]"');if(null!==l){var m=p(),m=null!==m?m:"";if(null!==m){var v=q();if(null!==v){var w=p(),w=null!==w?w:"";if(null!==w){var x=n();null!==x?e=[e,h,k,l,m,v,w,x]:(e=null,g=d)}else e=null,g=d}else e=null,g=d}else e=null,g=d}else e=null,g=d}else e=null,g=d}else e=null,g=d}else e=null,g=d;null!==e?(d=e[7],d[e[0]]=
[e[2]].concat(e[5])):d=null;null===d&&(d=null,g=c);u[b]={nextPos:g,result:d};return d}function n(){var b="MoreTokens@"+g,c=u[b];if(c)return g=c.nextPos,c.result;c=m();if(null===c){c=g;if(""===a.substr(g,0)){var d="";g+=0}else d=null,s&&f('""');d=null!==d?{}:null;null===d&&(d=null,g=c);c=null!==d?d:null}u[b]={nextPos:g,result:c};return c}function r(){var b="Data@"+g,c=u[b];if(c)return g=c.nextPos,c.result;var c=g,d=[];if("\\]"===a.substr(g,2)){var e="\\]";g+=2}else e=null,s&&f('"\\\\]"');null===e&&
(null!==a.substr(g).match(/^[^\]]/)?(e=a.charAt(g),g++):(e=null,s&&f("[^\\]]")),e=null!==e?e:null);for(;null!==e;)d.push(e),"\\]"===a.substr(g,2)?(e="\\]",g+=2):(e=null,s&&f('"\\\\]"')),null===e&&(null!==a.substr(g).match(/^[^\]]/)?(e=a.charAt(g),g++):(e=null,s&&f("[^\\]]")),e=null!==e?e:null);d=null!==d?d.join(""):null;null===d&&(d=null,g=c);u[b]={nextPos:g,result:d};return d}function q(){var b="MoreData@"+g,c=u[b];if(c)return g=c.nextPos,c.result;var d=c=g;if("["===a.substr(g,1)){var e="[";g+=1}else e=
null,s&&f('"["');if(null!==e){var h=r();if(null!==h){if("]"===a.substr(g,1)){var k="]";g+=1}else k=null,s&&f('"]"');if(null!==k){var l=p(),l=null!==l?l:"";if(null!==l){var m=q();null!==m?e=[e,h,k,l,m]:(e=null,g=d)}else e=null,g=d}else e=null,g=d}else e=null,g=d}else e=null,g=d;d=null!==e?[e[1]].concat(e[4]):null;null===d&&(d=null,g=c);null!==d?c=d:(c=g,""===a.substr(g,0)?(d="",g+=0):(d=null,s&&f('""')),d=null!==d?[]:null,null===d&&(d=null,g=c),c=null!==d?d:null);u[b]={nextPos:g,result:c};return c}
function t(){var b="TokenName@"+g,c=u[b];if(c)return g=c.nextPos,c.result;var d=c=g;if(null!==a.substr(g).match(/^[a-zA-Z]/)){var e=a.charAt(g);g++}else e=null,s&&f("[a-zA-Z]");if(null!==e){if(null!==a.substr(g).match(/^[a-zA-Z]/)){var h=a.charAt(g);g++}else h=null,s&&f("[a-zA-Z]");null!==h?e=[e,h]:(e=null,g=d)}else e=null,g=d;null!==e?d=e:(null!==a.substr(g).match(/^[a-zA-Z]/)?(d=a.charAt(g),g++):(d=null,s&&f("[a-zA-Z]")),d=null!==d?d:null);d=null!==d?1===d.length?d[0]:d.join("").toUpperCase():null;
null===d&&(d=null,g=c);u[b]={nextPos:g,result:d};return d}function p(){var b="WhiteSpace@"+g,c=u[b];if(c)return g=c.nextPos,c.result;c=[];if(" "===a.substr(g,1)){var d=" ";g+=1}else d=null,s&&f('" "');null===d&&("\n"===a.substr(g,1)?(d="\n",g+=1):(d=null,s&&f('"\\n"')),d=null!==d?d:null);for(;null!==d;)c.push(d)," "===a.substr(g,1)?(d=" ",g+=1):(d=null,s&&f('" "')),null===d&&("\n"===a.substr(g,1)?(d="\n",g+=1):(d=null,s&&f('"\\n"')),d=null!==d?d:null);u[b]={nextPos:g,result:c};return c}function x(){var b;
a:{b=y;b.sort();for(var c=null,d=[],f=0;f<b.length;f++)b[f]!==c&&(d.push(b[f]),c=b[f]);switch(d.length){case 0:b="end of input";break a;case 1:b=d[0];break a;default:b=d.slice(0,d.length-1).join(", ")+" or "+d[d.length-1]}}c=Math.max(g,w);c=c<a.length?e(a.charAt(c)):"end of input";return"Expected "+b+" but "+c+" found."}function z(){for(var b=1,c=1,d=!1,e=0;e<w;e++){var f=a.charAt(e);"\n"===f?(d||b++,c=1,d=!1):"\r"===f|"\u2028"===f||"\u2029"===f?(b++,c=1,d=!0):(c++,d=!1)}return{line:b,column:c}}var v=
{Data:r,MoreData:q,MoreTokens:n,MoreVars:k,Moves:l,Start:function(){var b="Start@"+g,c=u[b];if(c)return g=c.nextPos,c.result;var d=c=g;if("(;"===a.substr(g,2)){var e="(;";g+=2}else e=null,s&&f('"(;"');if(null!==e){var k=m();if(null!==k){var l=h();if(null!==l){if(")"===a.substr(g,1)){var n=")";g+=1}else n=null,s&&f('")"');null!==n?e=[e,k,l,n]:(e=null,g=d)}else e=null,g=d}else e=null,g=d}else e=null,g=d;d=null!==e?glift.rules.movenode(glift.rules.properties(e[1]),e[2]).renumber():null;null===d&&(d=
null,g=c);u[b]={nextPos:g,result:d};return d},TokenName:t,Tokens:m,Variations:h,WhiteSpace:p};if(void 0!==b){if(void 0===v[b])throw Error("Invalid rule name: "+e(b)+".");}else b="Start";var g=0,s=!0,w=0,y=[],u={},v=v[b]();if(null===v||g!==a.length)throw v=z(),new this.SyntaxError(x(),v.line,v.column);return v},toSource:function(){return this._source},SyntaxError:function(a,b,d){this.name="SyntaxError";this.message=a;this.line=b;this.column=d}};b.SyntaxError.prototype=Error.prototype;return b}();
glift.controllers={};
(function(){glift.controllers.base=function(){return new b};var b=function(){this.sgfString="";this.initialPosition=[];this.goban=this.movetree=this.treepath=void 0};b.prototype={initOptions:function(a){this.sgfString=a.sgfString;this.initialPosition=a.initialPosition;this.extraOptions(a);this.initialize();return this},extraOptions:function(a){},addStone:function(a,b){throw"Not Implemented";},recordCaptures:function(a){this.currentMoveNumber++;this.captureHistory.push(a);return this},initialize:function(){var a=
glift.rules;this.treepath=a.treepath.parseInitPosition(this.initialPosition);this.currentMoveNumber=this.treepath.length;this.movetree=a.movetree.getFromSgf(this.sgfString,this.treepath);a=a.goban.getFromMoveTree(this.movetree,this.treepath);this.goban=a.goban;this.captureHistory=a.captures;return this},getEntireBoardState:function(){return glift.rules.intersections.getFullBoardData(this.movetree,this.goban)},getNextBoardState:function(){return glift.rules.intersections.nextBoardData(this.movetree,
this.getCaptures())},getCaptures:function(){return 0===this.captureHistory.length?{BLACK:[],WHITE:[]}:this.captureHistory[this.currentMoveNumber-1]},canAddStone:function(a,b){return this.goban.placeable(a,b)},getCurrentPlayer:function(){return this.movetree.getCurrentPlayer()},getIntersections:function(){return this.movetree.getIntersections()},nextMove:function(a){if(void 0!==this.treepath[this.currentMoveNumber]&&(void 0===a||this.treepath[this.currentMoveNumber]===a))this.movetree.moveDown(this.treepath[this.currentMoveNumber]);
else if(a=void 0===a?0:a,0<=a&&a<=this.movetree.nextMoves().length-1)this.setNextVariation(a),this.movetree.moveDown(a);else return glift.util.none;a=this.goban.loadStonesFromMovetree(this.movetree);this.recordCaptures(a);return this.getNextBoardState()},prevMove:function(){if(0===this.currentMoveNumber)return glift.util.none;var a=this.getCaptures(),b=this.movetree.properties().getAllStones();this.captureHistory=this.captureHistory.slice(0,this.currentMoveNumber-1);this.goban.unloadStones(b,a);this.currentMoveNumber=
0===this.currentMoveNumber?this.currentMoveNumber:this.currentMoveNumber-1;this.movetree.moveUp();return glift.rules.intersections.previousBoardData(this.movetree,b,a)},setNextVariation:function(a){this.treepath=this.treepath.slice(0,this.currentMoveNumber);this.treepath.push(a%this.movetree.node().numChildren());return this}}})();
(function(){glift.controllers.gameViewer=function(a){a=glift.controllers.processOptions(a);var c=glift.util.beget(glift.controllers.base()),c=glift.util.setMethods(c,b);c.initOptions(a);return c};var b={extraOptions:function(a){},addStone:function(a,b){var d=this._possibleNextMoves(),e=a.toString()+"-"+b;return void 0===d[e]?glift.util.none:this.nextMove(d[e])},getNextVariationNumber:function(){return this.currentMoveNumber>this.treepath.length||void 0===this.treepath[this.currentMoveNumber]?0:this.treepath[this.currentMoveNumber]},
moveUpVariations:function(){return this.setNextVariation((this.getNextVariationNumber()+1)%this.movetree.node().numChildren())},moveDownVariations:function(){return this.setNextVariation((this.getNextVariationNumber()-1+ +this.movetree.node().numChildren())%this.movetree.node().numChildren())},toBeginning:function(){this.movetree=this.movetree.getTreeFromRoot();this.goban=glift.rules.goban.getFromMoveTree(this.movetree,[]).goban;this.captureHistory=[];this.currentMoveNumber=0;return this.getEntireBoardState()},
toEnd:function(){for(;this.nextMove()!==glift.util.none;);return this.getEntireBoardState()},_possibleNextMoves:function(){for(var a={},b=this.movetree.nextMoves(),d=0;d<b.length;d++){var e=b[d];a[e.point.toString()+"-"+e.color]=d}return a}}})();
glift.controllers.processOptions=function(b){var a={initialPosition:[],sgfString:""},c;for(c in b){var d=b[c];switch(c){case "initialPosition":if("string"===glift.util.typeOf(d))a.initialPosition=glift.treepath.rules.parseInitPosition(d);else if("array"===glift.util.typeOf(d))a.initialPosition=d;else throw"Unknown type for option initialPosition: "+d;break;case "sgfString":if("string"===glift.util.typeOf(d))a.sgfString=d;else throw"Bad type for sgfString -- was expecting an SGF string: "+d;}}return a};
(function(){glift.controllers.staticProblem=function(a){a=glift.controllers.processOptions(a);var c=glift.util.beget(glift.controllers.base()),c=glift.util.setMethods(c,b);c.initOptions(a);return c};var b={reload:function(){this.initialize()},addStone:function(a,b){var d=glift.enums.problemResults,e=d.CORRECT,f=d.INCORRECT,h=d.INDETERMINATE,d=d.FAILURE,k=this.goban.addStone(a,b);if(k.successful)d={},d[b]=k.captures,this.recordCaptures(d);else return{result:d};d=this.movetree.findNextMove(a,b);if(d===
glift.util.none)return this.movetree.addNode(),this.movetree.properties().add(glift.sgf.colorToToken(b),a.toSgfCoord()),e=this.getNextBoardState(),e.result=f,e;this.movetree.moveDown(d);d=this.movetree.isCorrectPosition();if(d===e||d==f)return e=this.getNextBoardState(),e.result=d,e;if(d===h){f=this.getNextBoardState();e=glift.math.getRandomInt(0,this.movetree.node().numChildren()-1);this.movetree.moveDown(e);e=this.movetree.properties().getMove();k=this.goban.addStone(e.point,e.color);d={};d[e.color]=
k.captures;this.recordCaptures(d);e=this.getNextBoardState();for(b in f.stones)for(d=0;d<f.stones[b].length;d++)e.stones[b].push(f.stones[b][d]);e.result=h;return e}throw"Unexpected result output: "+d;}}})();
glift.bridge={setDisplayState:function(b,a,c){a.intersections().clearMarks();for(var d in b.stones)for(var e=0;e<b.stones[d].length;e++){var f=b.stones[d][e];a.intersections().setStoneColor(f,d)}d=glift.enums.marks;for(var h in b.marks)for(e=0;e<b.marks[h].length;e++)f=b.marks[h][e],h===d.LABEL?a.intersections().addMarkPt(f.point,h,f.value):a.intersections().addMarkPt(f,h);if(b.nextMoves&&(1<b.nextMoves.length&&c===glift.enums.showVariations.MORE_THAN_ONE||1<=b.nextMoves.length&&c===glift.enums.showVariations.ALWAYS))for(e=
0;e<b.nextMoves.length;e++)c=b.nextMoves[e],a.intersections().addMarkPt(c.point,d.VARIATION_MARKER,e+1);b.lastMove&&b.lastMove!==glift.util.none&&(b=b.lastMove,a.intersections().addMarkPt(b.point,d.STONE_MARKER))}};
glift.bridge.getCropFromMovetree=function(b){var a=glift.displays.bboxFromPts,c=glift.util.point,d=glift.enums.boardRegions,e=b.getIntersections()-1,f=Math.ceil(e/2),h={},k={},l=0;h[d.TOP_LEFT]=a(c(0,0),c(f+1,f+1));h[d.TOP_RIGHT]=a(c(f-1,0),c(e,f+1));h[d.BOTTOM_LEFT]=a(c(0,f-1),c(f+1,e));h[d.BOTTOM_RIGHT]=a(c(f-1,f-1),c(e,e));b.recurseFromRoot(function(a){a=a.properties().getAllStones();for(var b in a)for(var c=a[b],d=0;d<c.length;d++){var e=c[d];l+=1;for(var f in h)h[f].contains(e)&&(void 0===k[f]&&
(k[f]=[]),k[f].push(e))}});return glift.bridge._getRegionFromTracker(k,l)};glift.bridge._getRegionFromTracker=function(b,a){var c=[],d;for(d in b){if(b[d].length===a)return d;c.push(d)}if(2!==c.length)return glift.boardRegions.ALL;var c=glift.util.intersection(glift.util.regions.getComponents(c[0]),glift.util.regions.getComponents(c[1])),e;for(e in c)return e;return glift.boardRegions.ALL};glift.widgets={};
(function(){glift.widgets.baseWidget=function(a){return(new b(glift.widgets.defaultOptions(a))).draw()};var b=function(a){this.options=a;this.wrapperDiv=a.divId;this.controller=a.controller;this.iconBar=this.display=void 0};b.prototype={draw:function(){this.divInfo=glift.displays.gui.splitDiv(this.wrapperDiv,this.options.useCommentBar?[0.7,0.2]:[0.9],"horizontal");this.goboxDivId=this.divInfo[0].id;this.options.divId=this.goboxDivId;this.display=glift.displays.create(this.options);var a=$("#"+this.goboxDivId).width();
this.options.useCommentBar&&(this.commentBoxId=this.divInfo[1].id,this._createCommentBox(a));this.iconBarId=this.options.useCommentBar?this.divInfo[2].id:this.divInfo[1].id;this._createIconBar(a);this._initStoneActions();this._initIconActions();this._initKeyHandlers();this.applyFullBoardData(this.controller.getEntireBoardState());return this},_createCommentBox:function(a){this.commentBox=glift.displays.gui.commentBox(this.commentBoxId,this.display.width(),a,this.options.theme,void 0!==this.options.goBoardBackground)},
_createIconBar:function(a){a=(a-this.display.width())/2;this.iconBar=glift.displays.gui.iconBar({themeName:this.options.themeName,divId:this.iconBarId,vertMargin:5,horzMargin:a,icons:this.options.icons})},_initIconActions:function(){var a=this,b=this.options.actions.icons,d;for(d in b){b[d].mouseover=b[d].mouseover||function(a,b){var c=a.iconBar.iconId(b);d3.select("#"+c).attr("fill","red")};b[d].mouseout=b[d].mouseout||function(a,b){var c=a.iconBar.iconId(b);d3.select("#"+c).attr("fill",a.iconBar.theme.icons.DEFAULT.fill)};
for(var e in b[d])(function(b,c,e){a.iconBar.setEvent(b,d,function(){e(a,c)})})(e,d,b[d][e])}},_initStoneActions:function(){var a=this.options.actions.stones,b=this,d;for(d in a)(function(a,d){b.display.intersections().setEvent(a,function(a){d(b,a)})})(d,a[d])},_initKeyHandlers:function(){var a=this;$("body").keydown(function(b){if((b=glift.keyMappings.codeToName(b.which))&&void 0!==a.options.keyMapping[b]){b=a.options.keyMapping[b].split(".");for(var d=a.options.actions[b[0]],e=1;e<b.length;e++)d=
d[b[e]];d(a)}})},applyPartialData:function(a){this._applyBoardData(a,!1)},applyFullBoardData:function(a){this._applyBoardData(a,!0)},_applyBoardData:function(a,b){a&&a!==glift.util.none&&(this.setCommentBox(a),b&&this.display.intersections().clearAll(),glift.bridge.setDisplayState(a,this.display,this.options.showVariations))},setCommentBox:function(a){this.commentBox&&(a.comment&&a.comment!==glift.util.none?this.commentBox.setText(a.comment):this.commentBox.clearText())},redraw:function(){this.destroy();
this.draw()},destroy:function(){$("#"+this.wrapperDiv).empty();this.display=void 0}}})();
glift.widgets.basicProblem=function(b){b.controller=glift.controllers.staticProblem(b);b.boardRegion=b.boardRegion||glift.bridge.getCropFromMovetree(b.controller.movetree);b.showVariations=glift.enums.showVariations.NEVER;b.useCommentBar=!1;b.keyMapping={};b.icons=b.icons||["play","refresh","roadmap","checkbox"];b.actions={};b.actions.stones={};b.actions.stones.mouseup=function(a,b){var d=a.controller.getCurrentPlayer(),d=a.controller.addStone(b,d),e=glift.enums.problemResults;d.result!==e.FAILURE&&
(a.applyPartialData(d),void 0===a.correctness&&(d.result===e.CORRECT?(a.iconBar.addTempIcon("check",a.iconBar.getIcon("checkbox").newBbox,"#0CC"),a.correctness=e.CORRECT):d.result==e.INCORRECT&&(a.iconBar.addTempIcon("cross",a.iconBar.getIcon("checkbox").newBbox,"red"),a.correctness=e.INCORRECT)))};b.actions.icons=b.actions.icons||{play:{mouseup:function(a){}},refresh:{mouseup:function(a){a.controller.reload();a.correctness=void 0;a.iconBar.destroyTempIcons();a.applyFullBoardData(a.controller.getEntireBoardState())}},
roadmap:{mouseup:function(a){a.problemControllor=a.controller;a.problemOptions=a.options;a.destroy();a.options=glift.widgets.defaultOptions({divId:a.options.divId,theme:a.options.theme,sgfString:a.options.sgfString,showVariations:glift.enums.showVariations.ALWAYS,iconExtensions:["undo"],actionExtensions:{icons:{undo:{mouseup:function(a){a.destroy();a.options=a.problemOptions;a.controller=a.problemControllor;a.draw()}}}}});a.controller=glift.controllers.gameViewer(a.options);a.options.boardRegion=
glift.bridge.getCropFromMovetree(a.options.controller.movetree);a.draw()}}};glift.widgets.extendIconActions(b);return glift.widgets.baseWidget(b)};
glift.widgets.defaultOptions=function(b){b.controller=b.controller||glift.controllers.gameViewer(b);b.divId=b.divId||"glift_display";b.theme=b.theme||"DEFAULT";b.boardRegion=b.boardRegion||"ALL";b.keyMapping=b.keyMapping||{ARROW_LEFT:"icons.arrowleft.mouseup",ARROW_RIGHT:"icons.arrowright.mouseup"};b.showVariations=b.showVariations||glift.enums.showVariations.MORE_THAN_ONE;b.useCommentBar=void 0===b.useCommentBar?!0:b.useCommentBar;b.actions=b.actions||{};b.actions.stones=b.actions.stones||{};var a=
{BLACK:"BLACK_HOVER",WHITE:"WHITE_HOVER"};b.actions.stones.mouseup=b.actions.stones.mouseup||function(a,b){var e=a.controller.getCurrentPlayer(),e=a.controller.addStone(b,e);a.applyPartialData(e)};b.actions.stones.mouseover=b.actions.stones.mouseover||function(b,d){var e=b.controller.getCurrentPlayer();b.controller.canAddStone(d,e)&&b.display.intersections().setStoneColor(d,a[e])};b.actions.stones.mouseout=b.actions.stones.mouseout||function(a,b){var e=a.controller.getCurrentPlayer();a.controller.canAddStone(b,
e)&&a.display.intersections().setStoneColor(b,"EMPTY")};b.icons=b.icons||["start","end","arrowleft","arrowright"];b.actions.icons=b.actions.icons||{start:{mouseup:function(a){var b=a.controller.toBeginning();a.applyFullBoardData(b)}},end:{mouseup:function(a){var b=a.controller.toEnd();a.applyFullBoardData(b)}},arrowright:{mouseup:function(a){var b=a.controller.nextMove();a.applyPartialData(b)}},arrowleft:{mouseup:function(a){var b=a.controller.prevMove();a.applyPartialData(b)}}};glift.widgets.extendIconActions(b);
return b};glift.widgets.extendIconActions=function(b){void 0!==b.iconExtensions&&(b.icons=b.icons.concat(b.iconExtensions));if(void 0!==b.actionExtensions&&void 0!==b.actionExtensions.icons)for(var a in b.actionExtensions.icons)b.actions.icons[a]=b.actionExtensions.icons[a]};
